- .vscode/extensions.json
- previously recommended extension was removed, using most active fork now
closes #21
> chore: change recommended Visual Studio Code stylelint extension (#21)

- src/app/core/store/restore/restore.effects.ts
> fix: universal EmptyError in console

- src/app/core/services/cookies/cookies.service.spec.ts
- src/app/core/services/cookies/cookies.service.ts
- src/app/core/store/restore/restore.effects.spec.ts
- src/app/core/store/restore/restore.effects.ts
Currently the functional cookie keeping the apiToken for later user or basket recovery is only saved when the cookie banner was accepted. This way however one cannot complete a checkout with redirect successfully.
Issue Number: 
no issue reported, yet
Functional cookies are always written, which should not cause legal issues, if there is a remark in the policy.
> fix: always write apiToken cookie as it is a functional cookie

- src/app/shared/forms/containers/login-form/login-form.container.html
- src/assets/i18n/fr_FR.json
Alignment of forgot password link is wrong for mobile view and in case of french localization also for tablet view.
Issue Number: ISREST-937
Alignment of forgot password link is correct for mobile view and french localization.
> fix: wrong alignment of forgot password link (ISREST-937)

- src/app/extensions/quoting/store/quote-request/quote-request.effects.spec.ts
- src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
quote-requests currently loaded in components (quote-widget.container.ts & quote-list-page.container.ts)
quote-requests should load on login and/or page-refresh (F5)
> fix: load quote-requests on login and page refresh

- src/app/core/services/basket/basket-payment.service.spec.ts
- src/app/core/services/basket/basket-payment.service.ts
- src/app/core/services/order/order.service.spec.ts
- src/app/core/services/order/order.service.ts
The PWA is always localized in English when the user comes back after he was redirected to an external payment provider.
Issue Number: 
(ISREST-883)
The PWA is always localized in the user's language when the user comes back after he was redirected to an external payment provider.
> fix: reopen the pwa in the user's language after coming back from payment redirect

- src/app/core/facades/checkout.facade.ts
- src/app/core/models/address/address.helper.spec.ts
- src/app/core/models/address/address.helper.ts
- src/app/core/store/checkout/basket/basket.selectors.ts
- src/app/core/utils/dev/html-query-utils.ts
- src/app/pages/account-addresses/account-addresses-page.module.ts
- src/app/pages/checkout-address/checkout-address-page.container.html
- src/app/pages/checkout-address/checkout-address-page.container.ts
- src/app/pages/checkout-address/checkout-address-page.module.ts
- src/app/pages/checkout-address/components/checkout-address-anonymous/checkout-address-anonymous.component.spec.ts
- src/app/pages/checkout-address/components/checkout-address-anonymous/checkout-address-anonymous.component.ts
- src/app/pages/checkout-address/components/checkout-address/checkout-address.component.html
- src/app/pages/checkout-address/components/checkout-address/checkout-address.component.spec.ts
- src/app/pages/checkout-address/components/checkout-address/checkout-address.component.ts
- src/app/pages/registration/registration-page.module.ts
- src/app/shared/checkout/containers/basket-invoice-address-widget/basket-invoice-address-widget.container.html
- src/app/shared/checkout/containers/basket-invoice-address-widget/basket-invoice-address-widget.container.spec.ts
- src/app/shared/checkout/containers/basket-invoice-address-widget/basket-invoice-address-widget.container.ts
- src/app/shared/checkout/containers/basket-shipping-address-widget/basket-shipping-address-widget.container.html
- src/app/shared/checkout/containers/basket-shipping-address-widget/basket-shipping-address-widget.container.spec.ts
- src/app/shared/checkout/containers/basket-shipping-address-widget/basket-shipping-address-widget.container.ts
- src/app/shared/shared.module.ts
- Refactoring (no functional changes, no API changes)
For a customer project it is necessary to transform the 5-step checkout into a 4-step checkout. In this particular case the addresses-step is not used, instead invoice addresses should be selected in the payment step and shipping-addresses are selected in the shipment step.
To make this possible, the components for selecting addresses are transformed into widgets.
Issue Number: 
Address selection components are refactored into two widgets responsible for selecting invoice and shipping addresses on their own.
No
> refactor: componentize address forms on checkout address step

- src/app/core/facades/shopping.facade.ts
- src/app/core/store/shopping/promotions/promotions.selectors.spec.ts
- src/app/core/store/shopping/promotions/promotions.selectors.ts
- src/app/shared/components/basket/basket-promotion/basket-promotion.component.spec.ts
- src/app/shared/components/product/product-promotion/product-promotion.component.spec.ts
- Bugfix
Promotions are not correctly memoized. When a promotion is edited during the runtime of the PWA, the memoization does not correctly re-fetch data from the store.
Promotions are correctly memoized.
> fix: repair memoization of promotion selectors

- src/app/core/models/seo-attribute/seo-attribute.model.ts
- src/app/core/pipes/product-route.pipe.ts
- src/app/extensions/seo/store/seo/seo.effects.ts
Issue Number: ISREST-932
canonical link support
> feat: seo canonical link support

- src/app/pages/account/account-navigation/account-navigation.component.html
- src/app/pages/account/account-navigation/account-navigation.component.ts
- src/app/pages/account/account-page.module.ts
- src/app/shared/components/common/breadcrumb/breadcrumb.component.html
Issue Number: ISREST-863
account overview as root account page in breadcrumb and path
> fix: account overview as root account page

- src/app/core/directives/server-html.directive.ts
Anchor scrolling / fragment navigation on a pages with content fetched via ICM CMS REST API doesn't work as expected. The ishServerHtml directive does not handle such links with only the a given anchor correctly, but will reload the application to a wrong route instead of scrolling on the current page. Complete routes with fragment navigation work as expected.
Such links do not work:
```<a href="#Software" title="Software">Software</a>```
These links would work:
```<a href="page://systempage.termsAndConditions.pagelet2-Page#OtherDocuments" title="OtherDocuments">Other Documents</a>```
This can be tested with the "Terms & Conditions" ICM demo content.
The ishServerHtml directive handles links like `<a href="#Software"` as anchor links and scrolls on the current page to the according …
> add anchor scrolling / fragment navigation for serverHtml content

- src/app/core/store/user/user.effects.spec.ts
[x] Bugfix  
[x] CI-related changes  
Issue Number: #95
`user.effects.spec.ts` log some errors to console.error
"Unhandled Promise rejection: Cannot match any routes. URL Segment: 'account/profile'"
looks like logging without throwing an error
clean output for ci
[x] No
> fix: missing route in user effects RouterTestingModule #95

- src/app/shared/cms/cms.module.ts
- src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.html
- src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.spec.ts
- src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.ts
- src/app/shared/shared.module.ts
Added PWA rendering support for CMS Landing Page components (e.g. Responsive Starter Store Homepage content). These components are basically caching wrappers in the classic ICM storefront. But with the support in the PWA content within such Landing Page components can be rendered too.
> feat: add support for CMS Landing Page components

- src/app/core/models/product/product.mapper.spec.ts
- src/app/core/models/product/product.mapper.ts
[x] Feature  
Issue Number: 
Closes #91 
While localized calls to the `/products/<sku>` REST resource return the product attribute values as localized values the attribute names are still returned in English. This will then result in a language mix in localized storefronts.
The attribute values as well as the attribute names should be returned in the requested locale with the `/products/<sku>` call.
[ ] Yes  
[x] No
> feat: localized product attributes

- schematics/src/service/factory_spec.ts
- schematics/src/service/files/__name@dasherize__/__name@dasherize__.service.__tsext__
- src/app/core/store/checkout/viewconf/viewconf.effects.ts
- src/app/core/store/contact/contact/contact.effects.ts
- src/app/pages/basket/shopping-basket/shopping-basket.component.ts
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
- src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.ts
- src/app/shared/components/basket/basket-info/basket-info.component.ts
- src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.ts
- tsconfig.json
- tslint-rules/dist/ishOrderedImportsRule.js
- tslint-rules/src/ishOrderedImportsRule.ts
- tslint.json
[x] Bugfix  
[ ] Feature  
[x] Refactoring (no functional changes, no API changes)  
[x] Build-related changes  
[ ] Other: 
Sometimes VSCode+tslint removes imports of decorators although they are not unused.
[ ] Yes  
[x] No
> fix: Angular decorator imports are removed on save

- e2e/cypress/integration/pages/account/quote-list.page.ts
- e2e/cypress/integration/pages/header.module.ts
- e2e/cypress/integration/pages/shopping/quote-request.dialog.ts
- e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
- src/app/core/facades/message.facade.ts
- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.spec.ts
- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.ts
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
"Save Quote Request" within a quote request modal dialog links to quote request details in my account area. The user loses his context.
(Issue Number: ISREST-940)
Click on "Save Quote Request" - closes modal and display success toast "Your quote request [name] has been saved." Then the user can continue shopping and easily adding another product to this quote request.
[x] No
> fix: save quote request from modal links to my account

- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
- src/app/pages/account/account-page.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Bugfix  
_Issue Number: ISREST-945 - Rename "Thank you for your quote" page_
**Current Behavior**
Heading: Thank you for your quote => user submitted no quote, it is a quote request
**Expected Behavior**
Heading: Thank you for your quote request
_Issue Number: ISREST-944 - Quoting - Thank you for your quote request displays additional info message with duplicated content_
**Current Behavior**
"Thank you for your quote request" page displays an additional info message, which displays the same content like the page.
**Expected Behavior**
Remove duplicated content regarding the quote request state on this page.
_Quote Detail page (in comparison to the Quote Request Detail page) does not display a complete breadcrumb_
**Current Behavior**
Home/ My Account/ Quotes
**Expected Behavior** …
> fix: minor quoting issues

- src/app/extensions/quoting/facades/quoting.facade.ts
- src/app/extensions/quoting/pages/quote-edit/quote-edit-page.component.spec.ts
- src/app/extensions/quoting/pages/quote-edit/quote-edit-page.component.ts
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.spec.ts
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.ts
- src/app/extensions/quoting/store/quote/quote.actions.ts
- src/app/extensions/quoting/store/quote/quote.effects.spec.ts
- src/app/extensions/quoting/store/quote/quote.effects.ts
- src/app/extensions/quoting/store/quote/quote.reducer.ts
- src/app/shared/components/basket/line-item-description/line-item-description.component.html
- src/app/shared/components/basket/line-item-description/line-item-description.component.ts
- src/app/shared/components/basket/line-item-list/line-item-list.component.ts
- src/app/shared/components/common/error-message/error-message.component.html
- src/app/shared/components/common/error-message/error-message.component.spec.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
Confusing error message is displayed: "400: Bad Request (Adding specified item finished with an error.)"
(Issue Number: ISREST-948)
* Error message should display: The quote cannot be added to the shopping cart. It contains invalid products.
* show Availability 
* remove "Add to Cart" button
* Add product to quote request
* Submit quote request
* Submit quote via backoffice
* Set product to out of stock or offline
* View responded quote
[x] No
> fix: error messages quote-edit

- e2e/cypress/integration/specs/quoting/quote-handling-anonymous.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
- src/app/extensions/quoting/facades/quoting.facade.ts
- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.spec.ts
- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.ts
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
- src/app/extensions/quoting/store/quote-request/quote-request.actions.ts
- src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Bugfix  
"Submit Quote Request" links to quote request details in my account area. The user loses his context.
(Issue Number: ISREST-941)
Click on "Submit Quote Request" - closes modal and shows "Thank you for your quote request" in a new modal. 
(Additional: Behaviour of "Create new QuoteRequest from QuoteRequest" in Dialog)
[ ] Yes  
[x] No
> fix: quote dialog submit behaviour

- src/app/core/models/product/__snapshots__/product.mapper.spec.ts.snap
- src/app/core/models/product/product.interface.ts
- src/app/core/models/product/product.mapper.spec.ts
- src/app/core/models/product/product.mapper.ts
- src/app/core/services/products/products.service.spec.ts
- src/app/core/services/products/products.service.ts
[x] Bugfix  
[ ] Feature  
[ ] Other: 
Product labels for products (like 'Sale' and 'Topseller') are not displayed on product list page until product detail page of the product has been opened.
Issue Number: #73 
Product labels are always displayed on product list page.
[ ] Yes  
[x] No
> fix: display of product labels for product lists (#73)

- src/app/core/services/products/products.service.ts
PR Type
[x] Bugfix
[ ] Feature
[ ] Other:
What Is the Current Behavior?
Product labels for products (like 'Sale' and 'Topseller') are not displayed on search result page.
What Is the New Behavior?
Product labels are displayed on search result page.
Does this PR Introduce a Breaking Change?
[ ] Yes
[x] No
> fix: display product labels on search result page

- src/app/core/guards/login.guard.ts
- src/app/pages/forgot-password/update-password/update-password.component.ts
[x] Bugfix  
change password (forgot password) open login dialog on success 
change password (forgot password) redirects to login page on success 
[ ] Yes  
[x] No
> fix: change password redirects to login page on success

- src/app/core/facades/app.facade.ts
- src/app/pages/product/product-detail-actions/product-detail-actions.component.html
- src/app/pages/product/product-detail-actions/product-detail-actions.component.ts
- src/app/pages/product/product-detail/product-detail.component.html
- src/app/pages/product/product-detail/product-detail.component.ts
- src/app/pages/product/product-page.component.html
- src/app/pages/product/product-page.component.ts
[x] Bugfix
Issue Number: 
Closes #128
- removed currentUrl$ from AppFacade
- use document.URL for sharing link
[ ] Yes  
[x] No
Decided to use [document.URL](https://caniuse.com/#feat=mdn-api_document_url) so it works both for SSR and Client Application
> fix: set correct URL for sharing product page via email

- .vscode/extensions.json
[ ] Bugfix  
[ ] Feature  
[x] Other: VSCode config
removed extensions:
`stringham.move-ts` - native support
`asvetliakov.snapshot-tools` - prefer jest inline snapshots
`orta.vscode-jest` - slows down most of the time instead of helping
> chore: update recommended vscode extensions

- src/app/core/routing/category/category.route.ts
[x] Bugfix  
[ ] Feature  
[x] Refactoring (no functional changes, no API changes)  
[ ] Other: 
the categorie matcher should match the category.  
/Gift-Cards-&-Certificates-**cat**specials.GiftCardsCertifi**cat**es matches "es" instead of "specials.GiftCardsCertificates"
(Issue Number: ISREST-1018)
[ ] Yes  
[x] No
> refactor: matcher for category url rewrite

- e2e/cypress/integration/specs/cms/server-html.mock.e2e-spec.ts
- src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.spec.ts
- src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.ts
[x] Bugfix  
[ ] Feature  
[ ] Other: 
Issue Number: #151
The ContentPageletEntryPoint id will be correctly used from data.id
[ ] Yes  
[x] No
> fix: use data.id for ContentPageletEntryPoint id (#151)

- src/app/shell/header/search-box/search-box.component.html
[x] Bugfix  
searchbox shows "null" on first page load.
searchbox shows empty string on first page load.
[ ] Yes  
[x] No
> fix: searchbox prevent "null"

- src/app/core/store/content/content-store.module.ts
- src/app/core/store/content/includes/includes.actions.ts
- src/app/core/store/content/includes/includes.effects.spec.ts
- src/app/core/store/content/includes/includes.effects.ts
- src/app/core/store/content/includes/includes.reducer.ts
- src/app/core/store/content/pagelets/index.ts
- src/app/core/store/content/pagelets/pagelets.actions.ts
- src/app/core/store/content/pagelets/pagelets.effects.spec.ts
- src/app/core/store/content/pagelets/pagelets.effects.ts
- src/app/core/store/content/pagelets/pagelets.reducer.ts
- src/app/core/store/content/pages/pages.actions.ts
- src/app/core/store/content/pages/pages.effects.spec.ts
- src/app/core/store/content/pages/pages.effects.ts
- src/app/core/store/content/pages/pages.reducer.ts
**Steps to Reproduce the Bug**
To repeat the but, you should reduce your Request speed, eg. by using the devtools
1. add a new PageVariant to the About Us page, only visible for Registered Users
2. Open PWA, navigate to "About us" -> default view
3. Login, goto "About us" -> registered only view
4. Logout
5. goto "About us" 
**Actual Behavior**
the page will show the registered only view until the default view is loaded from the server.
This could lead to some security issues, if content is visible for unauthorized targets.
This bug should not only affect pages, but includes and all their children as well 
**Expected Behavior**
the page will show only the default view
> fix: remove personalized content from store

- src/app/shared/components/common/loading/loading.component.scss
closes #166
[x] Bugfix  
[ ] Feature  
[ ] Other: 
The loading animation is not visible for scroll able pages (like order list with many entries).
The loading animation is visible in any case where it is needed.
[ ] Yes  
[X] No
> fix: fix loading animation display for scrollable pages (#166)

- e2e/cypress/integration/specs/checkout/checkout-payments.b2c.e2e-spec.ts
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
[ ] Bugfix  
[x] Feature  
[ ] Other: 
There is no possibility to remove a payment instrument on checkout payment page after you have added one.
Issue Number: ISREST-1024
There is a link to delete a payment instrument on checkout payment page. If the payment instrument is saved at the customer's profile it is also deleted from the profile.
[ ] Yes  
[x] No
> feat: delete payment instrument link on checkout payment page

- src/app/core/models/basket/basket.interface.ts
- src/app/core/models/basket/basket.mapper.spec.ts
- src/app/core/models/basket/basket.mapper.ts
- src/app/core/models/basket/basket.model.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
[x] Bugfix  
[ ] Feature  
[ ] Other: 
The user has exactly one invoice and shipping address.
The user adds some products to the basket and starts the checkout process.
He logs out, adds some products to the basket as anonymous user and starts the checkout process.
On the first checkout page he logs in.
An error occurred (basket not found).
There is a console error that requests failed.
Issue Number: ISREST-1032
There is no error any more, neither on screen nor in the console.
[ ] Yes  
[x] No
> fix: prevent error after login on checkout address page

- src/app/shared/components/common/loading/loading.component.scss
Reverting changes of pull request #170. Needs to be fixed in a different way that will not break all other cases that were fine before. See reopend #166 for explanation.
> Revert "fix: fix loading animation display for longer pages (#166, #170)"

- src/app/core/interceptors/auth.interceptor.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.effects.ts
[x] Bugfix
The e2e test `e2e/cypress/integration/specs/system/retain-authentication.b2c.e2e-spec.ts` detected a race-condition where the ReST API call for getting the user's wishlists is made with the wrong authentication token when feverishly refreshing the page and waiting for the user to be restored from the cookie.
Getting wishlists is debounced for a second. This also prevents hammering the ICM.
[ ] Yes  
[x] No
> fix: prevent wishlist request for anonymous user

- e2e/test-universal.sh
- src/app/core/facades/app.facade.ts
- src/app/core/guards/auth.guard.spec.ts
- src/app/core/guards/auth.guard.ts
- src/app/pages/login/login-page.component.html
- src/app/pages/login/login-page.component.spec.ts
- src/app/pages/login/login-page.component.ts
[x] Bugfix  
[x] Feature  
When coming to the PWA the user sees the login-page while the user is potentially restoring when apiToken cookie is available.
Loading animation is displayed while the above process is taking place.
[ ] Yes  
[x] No
> feat: display loading animation while restoring user on first navigation

- src/app/core/store/configuration/configuration.effects.spec.ts
- src/app/core/store/configuration/configuration.effects.ts
[x] Bugfix
race-condition using ngx-translate ngx-translate/core/issues/1030
Closes #207
[ ] Yes  
[x] No
Community Contribution 🎉
> fix: prevent mixed locale due to race condition using ngx-translate service use with SSR

- src/app/core/models/payment-method/payment-method.mapper.ts
[x] Bugfix  
On the checkout payment page the Concardis direct debit payment method does not display the mandate text. This leads to the effect that this payment method can not apply for the basket.
Furthermore, when setting the PWA to German/EUR we get the error ": Cannot read the property 'value' of undefined" on the payment page.
Issue Number: [233](https://github.com/intershop/intershop-pwa/issues/233) -> ISREST-1035, ISREST-1036
The mandate text is displayed on the Concardis direct debit payment method.
[ ] Yes  
[ x] No
> fix: Concardis DirectDebit cannot be assigned to basket

- src/app/core/store/user/user.effects.ts
[x] Bugfix
Triggering logins multiple times sends request for each login and a server session is created.
Login is only triggered once and further login attempts are ignored while another one is running.
[ ] Yes
[x] No
> fix: use exhaustMap for user login to prevent creating multiple sessions

- src/app/core/store/checkout/basket/basket-validation.effects.spec.ts
- src/app/core/store/checkout/basket/basket-validation.effects.ts
[x] Bugfix  
[ ] Feature  
[ ] Other: 
If the order creation fails after submitting the order, e.g. because of a failed payment authorization, the loading spinner remains on page until the next operation on the basket has been executed.
Issue Number: ISREST-1003
The loading spinner disappears after server communication has finished.
[] Yes  
[x] No
> fix: hide loading spinner after order creation failed

- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user edits an address on checkout address page the region is sometimes not or incorrectly displayed in the address form.
Issue Number: Closes #239
If the user edits an address on checkout address page the region is correctly displayed in the address form.
[ ] Yes
[x] No
> fix: display the region in the address form on the checkout address page

- src/app/core/models/product-variation/product-variation.helper.spec.ts
- src/app/core/models/product-variation/product-variation.helper.ts
- src/app/pages/product/product-detail/product-detail.component.ts
- src/app/pages/product/product-page.component.spec.ts
- src/app/pages/product/product-page.component.ts
- src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.ts
- src/app/shared/components/product/product-item/product-item.component.spec.ts
- src/app/shared/components/product/product-item/product-item.component.ts
- src/app/shared/components/product/product-row/product-row.component.ts
- src/app/shared/components/product/product-tile/product-tile.component.ts
- src/app/shared/components/product/product-variation-select/product-variation-select.component.html
- src/app/shared/components/product/product-variation-select/product-variation-select.component.spec.ts
- src/app/shared/components/product/product-variation-select/product-variation-select.component.ts
[x] Bugfix  
[x] Feature  
Bugfix in case of one variation attribute all options were "not available" any time. Additional new behaviour in case of one variation attribute is hiding "not available" options. (ISREST-756)  
"not available" selections should not be possible. (ISREST-725 & ISREST-1019)  
Now it is possible to find a possible variation based on the changed attribute.
In case of just one variation attribute and only one option now it reloads the component/page (second commit & cornercase)
[ ] Yes  
[x] No
> WIP: fix: variation select

- .github/workflows/test.yml
- angular.json
- e2e/test-schematics.sh
- package.json
- schematics/src/utils/lint-fix.ts
- src/app/core/services/api/api.service.spec.ts
- tslint-rules/.gitignore
- tslint-rules/jest.config.js
- tslint-rules/src/ngModuleSortedFieldsRule.spec.ts
- tslint-rules/src/ngModuleSortedFieldsRule.ts
- tslint-rules/src/testRuleExecutor.ts
- tslint-rules/tsconfig.json
[x] Feature
TSLint rule ng-module-sorted-fields does not respect `declaredComponents` arrays like in `ShellModule`.
- TSLint rule ng-module-sorted-fields sorts fields
- Unit Testing for tslint-rules
[ ] Yes
[x] No
> ng-module-sorted-fields improvements

- schematics/src/lazy-component/factory.ts
- schematics/src/lazy-component/factory_spec.ts
[x] Bugfix
[x] Feature
The lazy-component schematic does not correctly handle imports for complex typed inputs like:
```typescript
@Input() importComplexTyped: User[];
@Input() importGenericTyped: Observable<Customer[]>;
```
It does!
[ ] Yes
[x] No
> fix(schematics): handle imports of complex typings for input decorated fields in lazy-component schematic

- package-lock.json
- package.json
deps: update Bootstrap 4.4.1 to 4.5.0 (only the styling part of Bootstrap is used and affected)
> deps: update Bootstrap 4.4.1 to 4.5.0

- src/app/pages/account-profile/account-profile/account-profile.component.html
disabled display of users birthday in profile settings as long as the birthday input is not handled in the PWA, neither in the registration nor in the profile editting
> chore: disabled display of users birthday in profile settings

- src/app/shared/components/product/product-row/product-row.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user clicks on 'add to order template' icon button on a subcategory page (product row view) the order template will be created but the product won't be assigned to this order template.
Issue Number: Closes #271 
The product is added to order template.
[ ] Yes
[x] No
> fix: add to order template on product row

- .prettierignore
- .stylelintrc.json
[ ] Bugfix
[ ] Feature
[ ] Other: 
Generated compodoc output will be ignored by stylelint and prettier.
[ ] Yes
[x] No
> build: ignore generated compodoc output

- src/app/core/models/server-config/server-config.interface.ts
- src/app/core/models/server-config/server-config.mapper.spec.ts
- src/app/core/models/server-config/server-config.mapper.ts
- tslint.json
REST call response changed in 7.10.20 from array structure to pure object tree
BREAKING CHANGES: required ICM version 7.10.20+ GA
Closes #294
[x] Yes
[ ] No
> refactor: adapt parsing for changed configurations REST call

- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
[X] Bugfix
[ ] Feature
[ ] Other: 
The field type for account holder error message key was wrong.
The field type has been corrected for account holder message key.
[ ] Yes
[X] No
> fix: Correcting field type for error message key.

- schematics/src/extension/files/__name@dasherize__/exports/__name@dasherize__-exports.module.ts.template
extension schematic fix for feature switch naming from `dasherize` to the intended `camelize`
> refactor: use camelize for feature switch naming with the extension schematic

- src/app/core/store/shopping/categories/categories.effects.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
**Actual Behavior**
https://drive.google.com/file/d/1XuHs2z3H1G3dcldcUT-KoOFtTzJs0cMC/view
The second usage of a spezific page e.g. category "Notebooks" does not update the breadcrumb.  
Potentially affects all breadcrumbs.
**Expected Behavior**
Breadcrumb should work as expected
**Steps to Reproduce the Bug**
Steps to reproduce the behavior:
1. Go to category "Notebooks"
2. Click on first product
3. Click browser back or breadcrumb "Notebooks"
or
1. Go to first product of category "Notebooks" and refresh Page (F5)
2. Click on breadcrumb "Notebooks"
3. Click on first product or browser back 
closes: #316
> fix: inconsistent breadcrumb updates on category, search & product page

- docs/concepts/hybrid-approach.md
- docs/guides/migrations.md
- docs/guides/ssr-startup.md
- src/hybrid/default-url-mapping-table.ts
Hybrid Approach documentation adaptions for the PWA changes in regards to the new headless application type, plus some helpful other additions.
Note: Needs adaptions once the branch `feature/pwa_application_type` is merged to `develop`.
Wait for `feature/pwa_application_type` to be merged to `develop`.
Also includes upgrade informations for projects staying on RSS.
> docs: add headless app type migration information

- nginx/Dockerfile
The nginx modpagespeed local_storage_cache optimization is not actually doing anything for the PWA but writes an obsolete cookie, see https://www.modpagespeed.com/doc/filter-local-storage-cache. So we should remove it at all.
> chore: disable obsolete nginx modpagespeed local_storage_cache optimization

- schematics/src/store/files/__name@dasherize__/__name@dasherize__.reducer.ts.template
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.selectors.spec.ts.template
- src/app/core/store/customer/addresses/addresses.reducer.ts
- src/app/core/utils/ngrx-creators.spec.ts
- src/app/core/utils/ngrx-creators.ts
`loading` in reducers is boolean by default
`loading` can also be number for multiple parallel loading actions.
[ ] Yes
[x] No
> refactor: allow numbers as loading for ngrx reducer helpers

- e2e/test-schematics.sh
- schematics/src/helpers/customized-copy/factory.ts
- schematics/src/helpers/customized-copy/schema.json
[x] Bugfix
Schematic `customized-copy` does not work when executed from subfolder.
Fixed.
[ ] Yes
[x] No
Thank you for reporting @franciscomdrito :wink:
> fix(schematics): enable customized-copy schematic for subfolders

- schematics/src/lazy-component/factory_spec.ts
- schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
[x] Bugfix
[x] Application / infrastructure changes
Lazy components and extension stores are loaded without relation to their extension modules.
Fixed.
[x] Yes
[ ] No
> fix: repair loading of lazy extension components

- e2e/test-schematics.sh
- schematics/src/lazy-component/factory.ts
[x] Bugfix
All lazy components are generated with the customization prefix when starting a customization via script.
Original selectors of components are respected.
[ ] Yes
[x] No
Thanks again to @franciscomdrito for reporting 👍
> fix(schematics): respect original component selector when generating lazy components

- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.html
- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
[ ] Bugfix
[X] Feature
[ ] Other: 
Save for later checkbox was not available for Concardis direct debit.
Save for later checkbox is visible and working for Concardis direct debit.
[ ] Yes
[X] No
Requires Concardis Payment Connector 1.11.x - still unreleased
> feat: Implement save for later checkbox for Direct Debit

- e2e/cypress/integration/pages/account/registration.page.ts
- src/app/core/store/core/messages/messages.effects.spec.ts
- src/app/core/store/core/messages/messages.effects.ts
- src/app/shared/components/common/error-message/error-message.component.html
- src/app/shared/components/common/error-message/error-message.component.spec.ts
- src/app/shared/components/common/error-message/error-message.component.ts
- src/app/shared/components/login/login-form/login-form.component.html
- src/styles/global/toasts.scss
[x] Feature
- error messages are mostly displayed inline
- some success messages are displayed as toasts, but only in the top right corner
- toast messages used and styled more consistently
[ ] Yes
[x] No
To be discussed:
there is no simple solution, maybe postponed after header rework
Toasts are not used (yet):
- in the checkout because of the divergent header
- for information messages - consider to create a general info-message component in future for it
- success messages in modals are not replaced, e.g. add product to wish list/order template
VD Template:
> feat: styled toast messages for success and error messages

- src/app/core/models/basket/basket.model.ts
- src/app/core/models/line-item/line-item.mapper.ts
- src/app/core/models/line-item/line-item.model.ts
- src/app/core/models/order/order.model.ts
- src/app/core/store/customer/basket/basket-items.effects.spec.ts
- src/app/core/store/customer/customer-store.spec.ts
- src/app/core/utils/dev/basket-mock-data.ts
- src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.html
- src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.spec.ts
- src/app/shared/components/line-item/line-item-list/line-item-list.component.ts
- src/app/shell/header/mini-basket/mini-basket.component.html
- src/app/shell/header/mini-basket/mini-basket.component.spec.ts
[x] Bugfix
#373 introduced a bug, where line item names are no longer displayed for mini-basket and basket-item-summary components.
Product name is displayed for basket line items and supplied order line item names are used for order line items.
[ ] Yes
[x] No
> fix: use product name for basket line item name and order line item name for orders

- src/app/core/utils/theme/theme.service.ts
[x] Other: PageSpeed Insights Improvement
- PageSpeed Insights hint for preloading stylesheet: https://web.dev/uses-rel-preload/?utm_source=lighthouse&utm_medium=unknown
- stylesheet path is overwritten by browser application in production mode
Fixed.
[ ] Yes
[x] No
> perf: add preload link for stylesheet

- src/app/core/facades/account.facade.ts
- src/app/core/store/core/messages/messages.effects.ts
[x] Bugfix
Error Toasts stick to page until dismissed or hovered even when routing away.
Error Toasts are closed when routing is triggered.
Success Toast dissapear after usual time.
[ ] Yes
[x] No
> fix: close toast on routing

- e2e/cypress/integration/pages/account/order-templates-details.page.ts
- e2e/cypress/integration/pages/account/order-templates-overview.page.ts
- e2e/cypress/integration/pages/account/quote-detail.page.ts
- e2e/cypress/integration/pages/account/quote-list.page.ts
- e2e/cypress/integration/pages/account/wishlists-details.page.ts
- e2e/cypress/integration/pages/account/wishlists-overview.page.ts
- e2e/cypress/integration/specs/extras/order-templates-management.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/extras/wishlists-management.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
- src/app/core/store/core/viewconf/viewconf.effects.ts
- src/app/core/store/customer/orders/orders.effects.spec.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/extensions/order-templates/store/order-template/order-template.effects.spec.ts
- src/app/extensions/order-templates/store/order-template/order-template.effects.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.effects.ts
Closes  #399
[x] Bugfix
introduced by 3e55b635da47e1843f791b2e7574f95e8f15b4b4
Fixed.
[ ] Yes
[x] No
> fix: set breadcrumb from routing only if none was set previously

- projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
If a b2b administrator edits a b2b user profiles and an error occurs after submitting changes this error won't be displayed.
Errors are displayed on the b2b user edit profile page
[ ] Yes
[x] No
> fix: display error messages on the b2b user edit profile page

- nginx/channel.conf.tmpl
- src/app/app.server.module.ts
- src/app/core/configurations/configuration.meta.ts
- src/app/core/store/core/core-store.module.ts
[x] Bugfix
URL configuration parameters can be provided on storefront. -> security issue
The metaReducer for reading configuration parameters works only for the SSR container. The nginx running in front prevents setting of incoming configuration parameters.
[ ] Yes
[x] No
> fix: provide configuration meta reducer only on SSR side

- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ ] Bugfix
[ ] Feature
[ x] Other: Changes in the localization files
A table column has an incorrect naming, see ISREST-1111.
Issue Number: Closes #ISREST-1111
The table column has been renamed to "line items" and the German and French translations have been adapted.
[ ] Yes
[x ] No
> i18n: renamed line items table column (ISREST-1111)

- e2e/cypress/integration/pages/account/add-to-order-template.module.ts
- e2e/cypress/integration/pages/account/add-to-wishlist.module.ts
- src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.html
- src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.html
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
- src/app/extensions/quoting/shared/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
- src/app/extensions/wishlists/pages/account-wishlist/account-wishlist-list/account-wishlist-list.component.html
- src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
- src/app/extensions/wishlists/shared/wishlist-preferences-dialog/wishlist-preferences-dialog.component.html
- src/app/shared/components/common/modal-dialog/modal-dialog.component.html
- src/app/shared/components/login/login-modal/login-modal.component.html
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
- src/styles/global/modals.scss
- used the same 'modal-header' HTML in all places
- changed to cleaner modal-header / modal-body / modal-footer structure
- removed unneccessary 'modal-content' (duplicated in rendered HTML)
- removed unneccessary CSS classes (close-modal) and obsolete localization keys
[x] No
> refactor: Bootstrap Modal HTML unification and cleanup

- 3rd-party-licenses.txt
- package-lock.json
- package.json
- schematics/src/model/files/__name@dasherize__/__name@dasherize__.helper.spec.ts.template
- src/app/core/interceptors/mock.interceptor.spec.ts
- src/app/core/models/address/address.helper.spec.ts
- src/app/core/models/attribute/attribute.pipe.spec.ts
- src/app/core/models/category-tree/category-tree.helper.spec.ts
- src/app/core/models/category/category.helper.spec.ts
- src/app/core/models/category/category.mapper.spec.ts
- src/app/core/models/content-configuration-parameter/content-configuration-parameter.mapper.spec.ts
- src/app/core/models/content-view/content-view.helper.spec.ts
- src/app/core/models/price/price.helper.spec.ts
- src/app/core/models/product/product.helper.spec.ts
- src/app/core/models/product/product.mapper.spec.ts
- src/app/core/pipes/date.pipe.spec.ts
- src/app/core/pipes/highlight.pipe.spec.ts
- src/app/core/pipes/make-href.pipe.spec.ts
- src/app/core/pipes/sanitize.pipe.spec.ts
- src/app/core/services/api/api.service.errorhandler.spec.ts
- src/app/core/store/core/error/error.reducer.spec.ts
- src/app/core/utils/feature-toggle/feature-toggle.service.spec.ts
- src/app/core/utils/link-parser.spec.ts
- src/app/shared/address-forms/components/address-form/address-form.component.spec.ts
- src/app/shared/cms/sfe-adapter/dev/sfe.mapper.spec.dom-data.ts
- src/app/shared/cms/sfe-adapter/sfe.mapper.spec.ts
- src/app/shared/components/product/product-price/product-price.component.spec.ts
- src/app/shared/components/product/product-shipment/product-shipment.component.spec.ts
[ ] Bugfix
[ ] Feature
[x] Other: Library Replacement 
jasmine-data provider is used to provide multiple arguments to tests.
Issue Number: Closes #405
jest.each is natively available since jest version 23. Jasmine-data provider can be replaced.
[ ] Yes
[x] No
> chore: replace jasmine-data-provider with jest.each

- src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.html
- src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.html
- src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.html
- src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user presses enter in the promotion code input on the cart page the add-to-wishlist or add-to-order-template dialog opens up.
Issue Number: Closes #433 
If the user presses enter in the promotion code input on the cart page the promotion code is submitted.
[ ] Yes
[x] No
> fix: submit a promotion code by pressing enter

- src/app/pages/basket/shopping-basket-empty/shopping-basket-empty.component.html
- src/app/shared/components/basket/basket-validation-items/basket-validation-items.component.html
- src/app/shared/components/basket/basket-validation-products/basket-validation-products.component.html
- src/styles/pages/checkout/shopping-cart.scss
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user adds a product to cart and the product gets undeliverable, an error section is displayed.
The messages and the item description in the table are center-aligned.
The product name in the table is bold.
Issue Number: Closes #438
The messages and the item description in table are left-aligned.
The product name in the table is not bold.
[ ] Yes
[x] No
> fix: improve ui of out-of-stock products on the cart page 

- src/app/core/store/core/configuration/configuration.selectors.ts
- src/app/extensions/seo/store/seo/seo.effects.ts
[x] Bugfix
- meta tags `og:locale` and `og:locale:alternate` did not make it into the SSR response.
- selector `getCurrentLocale` returns falsy values when current locale (URL param `lang`) is set to invalid value.
- SSR crashes after delivering page when `og:locale:alternate` is attempted to be set, when `og:locale` isn't already set. 
Fixed.
[ ] Yes
[x] No
> fix: repair setting of locales meta tags

- docs/concepts/configuration.md
- src/app/core/directives/feature-toggle.directive.ts
- src/app/core/facades/app.facade.ts
- src/app/core/feature-toggle.module.ts
- src/app/core/pipes.module.ts
- src/app/core/pipes/feature-toggle.pipe.spec.ts
- src/app/core/pipes/feature-toggle.pipe.ts
- src/app/core/pipes/server-setting.pipe.spec.ts
- src/app/core/pipes/server-setting.pipe.ts
- src/app/pages/account/account-navigation/account-navigation.component.html
- src/app/pages/account/account-navigation/account-navigation.component.spec.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
-  Currently, there is no way to check server settings from a template.  This PR adds a ishServerSetting pipe that checks the store for relevant server settings.
- This PR adds an alternative to the feature toggle directive by introducing a feature toggle pipe. 
[ ] Yes
[x] No
> Add server configuration and feature toggle pipe

- src/app/core/store/customer/orders/orders.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
After the user changed the language on the order details page an error page is displayed. - This problem only occurs in case of server-side rendering with Angular Universal.
see also IS-IS-31347
The order detail page is displayed in the requested language.
[ ] Yes
[x] No
> fix: prevent an error if language switched on order details page 

- e2e/test-schematics.sh
- schematics/src/helpers/customized-copy/factory_spec.ts
- schematics/src/helpers/lazy-components/factory.ts
- schematics/src/helpers/move-component/factory_spec.ts
- schematics/src/lazy-component/factory.ts
- schematics/src/lazy-component/factory_spec.ts
- schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
- schematics/src/store/factory_spec.ts
- schematics/src/utils/registration.ts
- tslint.json
[x] Feature
lazy-component schematic works only for extensions.
lazy-component schematic also works for projects.
[ ] Yes
[x] No
> feat(schematics): lazy-components for projects

- schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
Simple fix to enable correct behaviour when running the simplified --ci option of the schematic:
FeatureToggleService is now imported only when needed. 
No breaking changes.
> chore: lazy-component fix for --ci option (#437)

- schematics/customization/add/index.js
[x] Bugfix
Script for adding customizations adds theme css to angular.json with inject = true, which causes faulty behavior.
This was a regression added with 3b8ea71cadafbe6b42093c8847f628cab8ab648b.
Fixed.
[ ] Yes
[x] No
> fix: customization start script should add themes with inject false

- server.ts
Requests for static resources, that don't exist, trigger an SSR rendering cycle which renders the error page.
The request accept headers are used to determine if the browser was expecting an html response. If the static resource was referenced in an img src, link or script tag, the browser doesn't explicitly request html content. This can be used to short-cut the 404 response and not trigger SSR.
[ ] Yes
[x] No
https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Accept
> perf: deny SSR rendering when accept headers do not match

- src/app/core/routing/category/category.route.spec.ts
- src/app/core/routing/category/category.route.ts
- src/app/core/routing/product/product.route.spec.ts
- src/app/core/routing/product/product.route.ts
- src/app/core/utils/routing.ts
[x] Bugfix
Under certain circumstances product slugs that are intended to make product routes more "speaking" and better suited for SEO can interfere with other PWA functionality (e.g the multi-site handling) if they contain some special characters in the route/URL. 
The current filtering of " ", "(" and ")" was extended with "&" and the whole configuration was centralized in one place and consistently used for product and category slugs.
If projects need further filtering, e.g. there have been issues with "/" for some projects, these additional characters can now be added at a single place.
[x] Yes - in regards to the current ICM-PWA site map implementation adaptions will be needed.
> fix: replace interfering special characters from product and categoy slugs

- src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.html
- src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.spec.ts
- src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Multiple validation error messages are shown for one form element, 
e.g. if an email address is required 2 errors are shown, if the field is empty
see ISREST-1088
If a form element has several validators, only the 1st validation message is shown
[ ] Yes
[x] No
> fix: display only one validation error for a form element at once

- .github/workflows/development.yml
- .github/workflows/integration.yml
- docs/README.md
- docs/concepts/sso.md
- docs/guides/nginx-startup.md
- docs/guides/sso-auth0.md
- docs/guides/ssr-startup.md
- nginx/channel.conf.tmpl
- package-lock.json
- package.json
- src/app/core/configurations/configuration.meta.ts
- src/app/core/identity-provider.module.ts
- src/app/core/identity-provider/auth0.identity-provider.ts
- src/app/core/identity-provider/icm.identity-provider.ts
- src/app/core/identity-provider/identity-provider.factory.ts
- src/app/core/identity-provider/identity-provider.interface.ts
- src/app/core/store/customer/addresses/addresses.effects.spec.ts
- src/app/core/store/customer/addresses/addresses.effects.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/pages/account-profile/account-profile/account-profile.component.html
- src/app/pages/account-profile/account-profile/account-profile.component.spec.ts
- src/app/shared/address-forms/components/address-form/address-form.factory.ts
- src/environments/environment.model.ts
[x] Feature
- SSO support via Auth0
[x] Yes
[ ] No
- support only B2C users
- No changes of email possible, email provided from IDP is used
- No customer approval supported
- Only one IDP supported
- Redirect to loading page to determine next page
- No creation of customers via Backoffice supported
- When using Auth0 username/password login, the name of the user must be changed from email to something useful, otherwise the user cannot set preferred payments or addresses.
- ICM Identity Provider
- Auth0 Identity Provider
> feat: SSO with Auth0 for B2C

- src/app/pages/account-overview/account-overview/account-overview.component.html
[x] Bugfix
Logging into B2C storefront displays an error on the my-account page
1. goto https://intershoppwa.azurewebsites.net/home
2. login
3. -> error toast caused by budget-widget
- widget display only active if approval is activated.
[ ] Yes
[x] No
caused by #326
> fix: wrap budget-widget to approval scope

- e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/checkout/basket-promotion-handling.b2c.e2e-spec.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/user/user.effects.spec.ts
- src/app/core/store/customer/user/user.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If an anonymous user enters a promotion code for the basket and registers the promotion code gets lost. 
The promotion is still applied to the basket after the user has registered.
[ ] Yes
[x] No
> fix: basket promotion code assignment gets lost after registration

- projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.spec.ts
- projects/organization-management/src/app/pages/user-create/user-create-page.component.spec.ts
- projects/organization-management/src/app/pages/user-create/user-create-page.component.ts
- projects/organization-management/src/app/services/users/users.service.spec.ts
- projects/organization-management/src/app/services/users/users.service.ts
- src/app/core/models/user/user.interface.ts
- src/app/core/models/user/user.mapper.ts
- src/app/core/models/user/user.model.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
- src/app/pages/registration/registration-form/registration-form.component.spec.ts
- src/app/pages/registration/registration-form/registration-form.component.ts
[x] Bugfix
User registration email is always sent in english (en_US) even if the user triggers the registration from a different storefront locale and with a this different locale in the REST call too.
This results from the hardcoded 'en_US' as preferredLanguage in the registration form.
The currently selected locale is used as 'preferredLanguage' when sending the registration form. With this change the registration email is send in the locale the user triggers the registration from.
[ ] Yes
[x] No
> fix: user registration mail always sent in english

- src/app/core/utils/dev/basket-mock-data.ts
- src/app/pages/checkout-payment/checkout-payment-page.component.spec.ts
- src/app/pages/checkout-payment/checkout-payment-page.component.ts
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ ] Bugfix
[x] Feature
[ ] Other: 
Although the basket total equals 0 the user has to select a payment method on checkout payment page.
Issue Number: see ISREST-1056
If the basket total equals 0 an info message is displayed on checkout payment page. The appropriate payment method is automatically assigned to the basket in the background.
[ ] Yes
[x] No
> feat: if the basket total equals 0 display only an info message on checkout payment page

- src/app/core/services/cms/cms.service.ts
- enables personalized content for view contexts
- prevents error "Bad Request (Matrix parameter "pgid" is required if auth token is present)"
addition to PR "feat: render view context content" #4
> fix: send PGID for CMS View Context calls

- e2e/cypress/integration/specs/checkout/checkout-payments.b2c.e2e-spec.ts
- projects/organization-management/src/app/store/users/users.effects.spec.ts
- projects/organization-management/src/app/store/users/users.effects.ts
- projects/requisition-management/src/app/store/requisitions/requisitions.effects.spec.ts
- projects/requisition-management/src/app/store/requisitions/requisitions.effects.ts
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.effects.ts.template
- src/app/core/models/basket-feedback/basket-feedback.model.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/error/error.effects.spec.ts
- src/app/core/store/core/error/error.effects.ts
- src/app/core/store/customer/basket/basket-items.effects.spec.ts
- src/app/core/store/customer/basket/basket-items.effects.ts
- src/app/core/store/customer/basket/basket-validation.effects.spec.ts
- src/app/core/store/customer/basket/basket-validation.effects.ts
- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/orders/orders.effects.spec.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/core/store/customer/user/user.effects.ts
- src/app/core/store/hybrid/hybrid.effects.ts
- src/app/core/store/shopping/categories/categories.effects.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/utils/http-status-code/http-status-code.service.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.ts
- src/app/extensions/tacton/store/product-configuration/product-configuration.effects.ts
- tslint.json
RxJS `tap` in effects usually points to improper usage.
[ ] Yes
[ ] No
> refactor: remove improper tap usage in effects

- src/app/core/identity-provider.module.ts
- src/app/core/identity-provider/auth0.identity-provider.ts
[x] Bugfix
Issue Number: Closes #512
`localStorage` is used for OAuth library to persist state across sessions.
[ ] Yes
[x] No
https://manfredsteyer.github.io/angular-oauth2-oidc/docs/additional-documentation/configure-custom-oauthstorage.html
fix deployed to #483 for testing: http://pwa-gh-review-483-universal-b2c.azurewebsites.net/
> fix: use localStorage as storage for oauth

- src/app/extensions/organization-hierarchies/shared/hierarchy-switch/hierarchy-switch.component.html
[ x] Bugfix
[ ] Feature
[ ] Other: 
In the group selectbox the selected group is not marked as selected in the list of this component. 
Issue Number: ISREST-1152
Selected group should not displayed in the list of the selectbox.
> fix: selected group should not displayed in list of group selectbox

- src/app/extensions/organization-hierarchies/models/organization-group/organization-group.mapper.spec.ts
- src/app/extensions/organization-hierarchies/models/organization-group/organization-group.mapper.ts
- src/app/extensions/organization-hierarchies/services/organization-hierarchies/organization-hierarchies.service.ts
[ x] Bugfix
[ ] Feature
[ ] Other: 
If a customer creates a root group in the PWA company structure page, then this group will not displayed with the correct group name in the group selectbox of the header component.
During the loading of the organization group into the PWA store, each root node name will mapped to the organization name. This solution works if only one root group exists. If more than one root group exist than several groups with the same name will displayed in the selectbox.
Issue Number: ISREST-1151
Remove mapping name to organization name.
[ …
> fix: remove specific mapper method for root nodes

- src/app/extensions/organization-hierarchies/facades/organization-hierarchies.facade.ts
[ ] Bugfix
[x ] Feature
[ ] Other: 
If the order history is opened and an new organization group is selected the order history page is not adapted regarding the new group.
Issue Number: ISREST-1131
If a new group is selected than the order history page should reload content.
[ ] Yes
[ x] No
> feat: reload orders after group selection

- src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
If a user has added products with reduced prices to his cart the crossed out prices are the same as the current product price on the checkout items widget.
Issue Number: Closes #ISREST-898
The correct crossed out prices are displayed on the checkout items widget.
[ ] Yes
[x] No
> fix: crossed prices in checkout items widget

- src/app/core/core.module.ts
- src/app/extensions/quickorder/pages/quickorder/quickorder-page.module.ts
- src/app/pages/checkout-shipping/checkout-shipping-page.module.ts
- src/app/pages/registration/registration-page.module.ts
- src/app/shared/formly/formly.module.ts
- src/app/shared/shared.module.ts
- formly is part of the vendor bundle
- formly is part of the common bundle
[ ] Yes
[x] No
> perf: move formly to lazy bundle

- src/app/extensions/order-templates/services/order-template/order-template.service.ts
- src/app/extensions/wishlists/services/wishlist/wishlist.service.ts
[x] Bugfix
If a user doesn't have order templates or wishlists and navigates to the corresponding my-account list view, the loading animation doesn't stop.
It works!
Calling `forkJoin` with an empty array will immediately complete, but somehow the `defaultIfEmpty` does not trigger anymore. I tried reproducing this behaviour on StackBlitz, but everything seems to work just fine (maybe a newer RxJS version? idk).
[ ] Yes
[x] No
> fix: prevent calling forkJoin with empty array for wishlists and order templates

- src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.html
- src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.spec.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
On the order template widget the names of the order templates are linked to the corresponding order template detail pages now.
[ ] Yes
[x] No
> feat: add order template detail links on order template widget

- schematics/src/extension/files/__name@dasherize__/exports/__name@dasherize__-exports.module.ts.template
- src/app/core/utils/module-loader/module-loader.service.ts
- src/app/extensions/order-templates/exports/order-templates-exports.module.ts
- src/app/extensions/punchout/exports/punchout-exports.module.ts
- src/app/extensions/quoting/exports/quoting-exports.module.ts
- src/app/extensions/sentry/exports/sentry-exports.module.ts
- src/app/extensions/tacton/exports/tacton-exports.module.ts
- src/app/extensions/tracking/exports/tracking-exports.module.ts
- src/app/extensions/wishlists/exports/wishlists-exports.module.ts
- templates/webpack/webpack.custom.ts
- one common bundle for all lazy loaded code
- if features are deactivated, the corresponding code will still be loaded
- previous bundling with many bundles had also issues, as it was closely associated with actual features
Current Bundles:
- features are split into bundles
- not every feature deserves a bundle (i.e. quickorder, tracking) - automatically managed by webpack
- feature specific libraries (like sentry) can be pushed into the chunk, that is lazy loaded when the feature is used
- one bundle for customer specific account functionality, that is not used while browsing
- common bundle for all remaining stuff
Proposed Bundles:
[ ] Yes
[x] No
> perf: restructure chunk splitting for features

- src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.html
- src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
After loading the checkout payment page there are console warnings concerning duplicate ids 'month' and 'year' if Cybersource and concardis creditcards are eligible as payment methods.
Unique ids are used, eg.e. concardis_creditcard_month, there are no console warnings
[ ] Yes
[x] No
see also tickets ISCS-67 and CONCARDIS-398.
> fix: set unique ids for form fields in payment components

- src/app/core/models/product/product.helper.spec.ts
- src/app/core/models/product/product.helper.ts
- src/app/pages/product/product-images/product-images.component.html
- src/app/pages/product/product-images/product-images.component.spec.ts
- src/app/pages/product/product-images/product-images.component.ts
`ish-product-images` uses NgbCarousel
`ish-product-images` uses Swiper
[ ] Yes
[x] No
> refactor: use swiper for product-images component

- .github/workflows/demo-server.yml
- .github/workflows/integration.yml
- Dockerfile
- Dockerfile_noSSR
- e2e/cypress/plugins/index.js
- e2e/package.json
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
- src/app/core/store/core/core-store.module.ts
- src/setupJest.ts
- src/typings.d.ts
- templates/webpack/webpack.custom.ts
With the webpack custom build we introduced a couple of minifications for production, but neither the cypress tests nor the demo servers are deployed with production settings to review and automatically test, if everything also works in production mode.
The GitHub review PWAs are deployed with production settings which also includes CSS minification for visual review.
See here for example:
- http://pwa-gh-review-572-universal-b2c.azurewebsites.net/page/page.helpdesk.pagelet2-Page
- https://intershoppwa.azurewebsites.net/page/page.helpdesk.pagelet2-Page
-> orange boxes are missing because this class is purged for production (thanks to @shauke for this example)
Now also cypress testing is run with production mode (and still ngrx runtime …
> build: make it possible to test and review in production mode

- .github/workflows/azure-devops.yml
- .github/workflows/reports.yml
[X] Bugfix
[ ] Feature
[ ] Other: 
Both github workflows `reports.yml` and `azure-devops.yml` are executed in all `intershop-pwa` related GitHub repos. They fail because the owning repo doesn't have the credentials necessary to log in into Azure.
If the owning repo is not `intershop`, skip the execution.
[ ] Yes
[X] No
> fix: run pipeline only on intershop account

- src/app/core/models/product-variation/product-variation.helper.ts
- src/app/core/models/server-config/server-config.mapper.ts
- src/app/core/services/filter/filter.service.ts
- src/app/core/utils/functions.spec.ts
- src/app/core/utils/functions.ts
- tslint.json
- `lodash-es/omit` in the codebase is not used to its full potential and it's a rather large helper (2 kB in the vendor bundle)
- replaced `omit` with simplified custom implementation
[ ] Yes
[x] No
needs fix in PR #594
> perf: forbid omit from lodash-es as it is not used to its full potential

- src/app/core/models/product-variation/product-variation.helper.ts
- src/app/core/models/server-config/server-config.mapper.spec.ts
- src/app/core/models/server-config/server-config.mapper.ts
- src/app/core/services/filter/filter.service.ts
- src/app/core/utils/functions.spec.ts
- src/app/core/utils/functions.ts
- tslint.json
[x] Bugfix
Server config settings with value `null` are mapped to an empty object `{ }`.
see:
`null` is correctly mapped.
[ ] Yes
[x] No
This happens because `typeof null === 'object'` and no special check was in place.
> fix: map server-config value for null correctly

- docs/guides/formly.md
- src/app/shared/formly/dev/testing/formly-testing.module.ts
[ ] Bugfix
[ ] Feature
[x] Other: Test-related changes
FormlyTestingModule exports only FieldTypes
FormlyTestingModule exports FieldTypes and FieldWrappers to be used throughout the PWA
[ ] Yes
[x] No
> test: add wrappers to formly-testing-module

- Dockerfile
- docs/concepts/cms-integration.md
- e2e/test-schematics.sh
- scripts/build-pwa.js
- templates/Dockerfile_dev
- deprecation warnings when using camel case parameters with ng commands
- removed unnecessary parameters
- transformed camel case parameters to kebab case
[ ] Yes
[x] No
https://blog.ninja-squad.com/2021/01/21/angular-cli-11.1/#camel-case-arguments-are-deprecated
> chore: remove deprecated camel case parameters from ng calls

- src/styles/global/global.scss
[x] Bugfix
[ ] Feature
[ ] Other: 
On the requisition page a scrollbar is shown next to the navigation bar.
There is no scrollbar any more.
[ ] Yes
[ x No
> fix: hide scrollbar from navigation tabs

- package-lock.json
- package.json
- src/app/app.server.module.ts
- src/app/core/core.module.ts
- src/app/core/utils/api-token/api-token.service.ts
- src/app/core/utils/cookies/cookies.service.spec.ts
- src/app/core/utils/cookies/cookies.service.ts
- src/app/extensions/punchout/pages/punchout/punchout-page.guard.ts
[x] Feature
- library ngx-utils-cookies-port (and also original library ngx-utils/cookies) are no longer maintained
- SameSite issue
- implementation integrated into PWA
- Closes #276
[ ] Yes
[x] No
> refactor: remove ngx utils cookies port

- projects/organization-management/src/app/store/users/users.reducer.ts
- src/app/core/store/content/includes/includes.reducer.ts
- src/app/core/store/content/pages/pages.reducer.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/core/store/customer/user/user.reducer.ts
- src/app/core/store/general/contact/contact.reducer.ts
- src/app/core/store/general/regions/regions.reducer.ts
- src/app/core/store/shopping/product-listing/product-listing.reducer.ts
- src/app/core/utils/ngrx-creators.ts
- src/app/extensions/order-templates/store/order-template/order-template.reducer.ts
- src/app/extensions/tacton/store/product-configuration/product-configuration.reducer.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.reducer.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Some reducers set their loading and error states manually when they don't have to.
Wherever possible and sensible, reducers now use setLoadingOn and unsetLoadingAndErrorOn for repetitive logic.
[ ] Yes
[x] No
> refactor: use setLoadingOn and unsetLoadingAndErrorOn where possible

- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/facades/shopping.facade.ts
- src/app/core/store/shopping/products/products.actions.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/products/products.reducer.ts
- src/app/core/store/shopping/products/products.selectors.spec.ts
- src/app/pages/product/product-links/product-links.component.ts
- src/app/shared/components/product/product-promotion/product-promotion.component.spec.ts
- src/app/shared/components/product/product-promotion/product-promotion.component.ts
- helper methods on product context for getting promotions and links lazy
- bundle and retail set parts are always fetched
- lazy Observable properties in the ProductContext type
[ ] Yes
[x] No
Not fetching bundle and retail set information for product tiles should decrease the home page rendering time.
> perf: use lazy properties on product context

- docs/guides/formly.md
- projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
- src/app/pages/registration/registration-page.component.spec.ts
- src/app/pages/registration/registration-page.component.ts
- src/app/shared/formly-address-forms/configurations/us/address-form-us.configuration.ts
- src/app/shared/formly/extensions/post-wrappers-extension.ts
- src/app/shared/formly/formly.module.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Currently you have to inject the FormlyConfig service to add wrappers to a FormlyFieldConfig.
Now you can append wrappers to a fields config via the postWrappers templateOptions attribute. 
[ ] Yes
[x] No
> refactor: use postWrappers extension instead of injecting config

- e2e/cypress/integration/specs/checkout/shopping-prices.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/extras/order-templates-shopping.b2b.e2e-spec.ts
- src/app/pages/account-profile-company/account-profile-company/account-profile-company.component.html
- src/app/pages/account-profile-company/account-profile-company/account-profile-company.component.spec.ts
- src/app/pages/account-profile-company/account-profile-company/account-profile-company.component.ts
- src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.html
- src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.spec.ts
- src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.ts
- src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.html
- src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.spec.ts
- src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.ts
- src/app/shared/formly/dev/testing/formly-testing.module.ts
- src/styles/global/forms/formly.scss
Some parts of profile settings in my account area uses the reactive form implementation.
All parts of profile settings in my account area uses formly for the forms.
[x] No
> refactor: use formly for my account profile forms

- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/utils/product-context-display-properties/product-context-display-properties.service.ts
it is hard to override default product context display property configuration without touching the `product-context.facade.ts` file
externalized calculation for easy overriding in projects.
see also #616 
[ ] Yes
[ ] No
> refactor: make display properties overridable

- src/styles/global/forms/forms.scss
- src/styles/global/global.scss
- src/styles/global/toasts.scss
- templates/webpack/webpack.custom.ts
[x] Bugfix
- toast styles are removed by PurgeCSS
Issue Number: Closes #600 
- toast styles are kept
[ ] Yes
[x] No
relates to #562
> fix: adapt purgecss configuration to prevent purging needed styles

- src/app/pages/forgot-password/update-password-form/update-password-form.component.html
- src/app/pages/forgot-password/update-password-form/update-password-form.component.spec.ts
- src/app/pages/forgot-password/update-password-form/update-password-form.component.ts
Update password form uses the reactive form implementation.
Update password form uses formly for the forms.
[x] No
> refactor: use formly for update password form

- nginx/Dockerfile
[x] Bugfix
Running `docker build -t nginx nginx` currently results in an error for the `nginx/nginx-prometheus-exporter` step.
Issue Number: Closes #632
`nginx` docker build is working again.
[x] No
> fix: adapt nginx Dockerfile to nginx-prometheus-exporter changes (#632)

- docs/guides/customizations.md
- e2e/test-schematics.sh
- package-lock.json
- package.json
- templates/webpack/webpack.custom.ts
[x] Feature
Environment specific overrides (#537) can only override HTML templates and component styles
Any typescript file can be overridden by having the extension "<key>.ts".
File overrides can be active for multiple configurations. For example `custom.service.brand1.brand2.ts` will activate for `ng build -c brand1` and also for `ng build -c brand2`.
[ ] Yes
[ ] No
This is useful for projects for overriding functionality without introducing changes in ISH sources.
> feat: replace any typescript file by configuration

- src/app/app.module.ts
- src/app/core/utils/custom-url-serializer.spec.ts
- src/app/core/utils/custom-url-serializer.ts
[x] Bugfix
Issue Number: Closes #610 
- custom URL serializer added, that encodes parentheses while processing URLs
[ ] Yes
[x] No
Sadly, the custom serializer has to be provided in `AppModule`. I did not get it working, when providing it in `CoreModule`, where such stuff usually belongs to...
> fix: allow parentheses in urls

- src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.html
- src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.spec.ts
- src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.ts
Forgot password form (request-reminder-form.component) uses the reactive form implementation.
Forgot password form uses formly for the form.
[x] No
> refactor: use formly for forgot password form (request reminder form)

- src/app/core/pipes/make-href.pipe.spec.ts
- src/app/core/pipes/make-href.pipe.ts
- src/app/shell/header/language-switch/language-switch.component.ts
[X] Bugfix
[ ] Feature
[ ] Other: 
Language switch component links to different URL and not multi site URL location that fits to the current page.
Language switch component links to same URL location that denotes the current page.
[ ] Yes
[ ] No
> fix: multi site not working language switch

- src/app/core/models/basket-validation/basket-validation.model.ts
- src/app/core/store/customer/basket/basket-validation.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If a cost center approval is required for a complete basket the basket acceleration doesn't work properly. The user cannot enter the checkout any more.
The user is routed to the checkout review page in this case.
[ ] Yes
[x] No
Steps to repeat:
- login as jlink@test.intershop.de
- add some products to basket, basket total has to be more than 500 USD
- click the 'checkout' button on cart page
- continue the checkout process until you reach the review page
- go back to cart page 
- click checkout
- => …
> fix: basket acceleration if cost center is required but missing

- src/app/pages/product/product-images/product-images.component.spec.ts
- src/app/pages/product/product-images/product-images.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the product has no product images of size 'L' there is no product image displayed on product detail page.
A fallback product image (not_available.png) is shown 
[ ] Yes
[x] No
see ISREST-1168
> fix: display a product unavailable image on product detail page

- src/app/core/utils/functions.spec.ts
- src/app/core/utils/functions.ts
[ x] Bugfix
[ ] Feature
[ ] Other: 
It is not possible to display not fully completed slides in cms-carousel-component.
Issue Number: Closes #450
Not fully completed slides are displayed in cms-carousel-component.
[ ] Yes
[ x] No
> fix: cms carousel component should handle not completely filled slides

- e2e/cypress/integration/pages/account/order-templates-overview.page.ts
- src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.html
- src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.spec.ts
- src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
Order template forms (order-template-preferences-dialog, select-order-template-modal) use the reactive form implementation.
Order template forms use formly for the form.
[x] No
> refactor: use formly for order template preferences form

- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Bugfix
Translations for common.button.navbarCollapsed.text is missing in PWA.
Issue Number: Closes #660
Translations for common.button.navbarCollapsed.text is added in PWA.
[ ] Yes
[x] No
> fix: add missing text for navigation toggle

- docs/guides/migrations.md
- e2e/cypress/integration/pages/checkout/checkout-addresses.page.ts
- e2e/cypress/integration/specs/checkout/register-before-checkout.b2c.e2e-spec.ts
- scripts/init-local-environment.js
- src/app/core/services/registration-form-configuration/registration-form-configuration.service.spec.ts
- src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.html
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.spec.ts
- src/environments/environment.model.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
Anonymous users are allowed to checkout and order items.
Issue Number: Closes #638
The guest checkout can be enabled/disabled with the help of the feature toggle 'guestCheckout' in the environment.ts.
It is possible to register after the user has started the checkout process. After registration he is automatically navigated back to the checkout.
[x] Yes, the guest checkout has to be enabled in the environment.ts, otherwise this feature is not available.
[ ] No
Limitations: In case of SSO the user is not automatically navigated …
> feat: add feature toggle for guest checkout

- src/app/core/identity-provider/auth0.identity-provider.ts
see: https://manfredsteyer.github.io/angular-oauth2-oidc/docs/additional-documentation/refreshing-a-token.html
<!--
[X] Bugfix
The authentication flow uses an automatic silent refresh, which is responsible to refresh the id and auth token before it expires. Currently this refresh token is failing: 
And according to the documentation, the offline_access scope is required to trigger the silent refresh.
Adding the offline_access scope will properly refresh the tokens before they expire.
[ ] Yes
[X] No
> fix: auth0 silentRefresh requires offline_access scope

- src/app/core/facades/product-context.facade.ts
[x] Bugfix
Data is not properly refreshed while switching between product detail pages once a product master or retail set is chosen.
Steps:
- open browser development tools, network tab, filter for `products/`
- go to master product: https://intershoppwa-b2b.azurewebsites.net/sku201807231
- switch to first variation (product call is being made)
- switch back to master via "Choose Another Variation"
-> no call is made to refresh the master product data
Level `true` (which means always refetch (set in `SelectedProductContextFacade`)) is not being overridden in `postProductFetch` of `ProductContextFacade`.
[ ] Yes
[x] No
> fix: repair data refresh on product pages

- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/orders/orders.actions.ts
- src/app/core/store/customer/orders/orders.reducer.ts
- src/app/core/store/customer/orders/orders.selectors.spec.ts
- src/app/pages/checkout-review/checkout-review/checkout-review.component.html
- src/app/pages/checkout-review/checkout-review/checkout-review.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
1. If the basket contains items that cannot be shipped together, but it is complete and validated successfully, the user is navigated from the cart page to the review page (in case of basket acceleration), but the review page is corrupt.
2. If the user submits a basket but the order could not be created (e.g. because a payment is not authorized), an error is displayed on checkout review page. If the user navigates to another page, e.g. the payment page and fixes the problem and he navigates to the review page again, the order …
> fix: in case of multiple buckets display message on checkout review page

- src/app/core/facades/checkout.facade.ts
[x] Bugfix
Issue Number: Closes #668
fixed 😁👍 
[ ] Yes
[x] No
> fix: track item changes as local state in checkout facade

- docker-compose.yml
- docs/guides/nginx-startup.md
- nginx/channel.conf.tmpl
…
[x] Feature
Multi Channel adds default root location redirecting to first baseHref in MultiChannel config
Check first if one multi channel config is also trying to map to root route.
[ ] Yes
[x] No
> feat: omit default redirect in multi channel when one base href is root route

- src/app/pages/product/product-links-carousel/product-links-carousel.component.html
- src/app/pages/product/product-links-carousel/product-links-carousel.component.spec.ts
- src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
- src/app/pages/product/product-links-list/product-links-list.component.html
- src/app/pages/product/product-links-list/product-links-list.component.spec.ts
- src/app/pages/product/product-links-list/product-links-list.component.ts
- src/app/pages/product/product-links/product-links.component.html
[x] Feature
The product links carousels/lists (cross-sellings, up-sellings. accessories, replacements, etc.) have no option to filter products out that are not available.
The product links carousel and product links list now have an input parameter `displayOnlyAvailableProducts` to configure if you want to display only available products. Via the parameter it can be controlled which lists should only present sell-able products (e.g. up-selling, cross-selling) and which lists should list products even if they are not available right now (e.g. spare parts).
[x] No
> feat: display only available products in product links carousels and lists

- e2e/cypress/integration/specs/checkout/checkout-validation.b2c.e2e-spec.ts
- src/app/shared/formly-address-forms/configurations/us/address-form-us.configuration.ts
[X] Bugfix
[ ] Feature
[ ] Other: 
The US new address form uses the id (e.g. "US_CA") for the region select dropdown as value. So that Value is sent to the new address API endpoint.
The default address form uses the regionCode (e.g. "CA").
Which makes perfectly sense as even the Store distinguishes between id (US_CA), regionCode (CA) and regionName (California) in that way.
Another visual problem can be seen after saving that address. In the address field it says for example "San Jose, US_CA" where it should be "San Jose, CA".
Issue Number: no known issue …
> fix: using regionCode instead of id for US new-address-form

- src/app/pages/content/content-page.component.html
- src/app/pages/content/content-page.component.spec.ts
- src/app/shared/cms/components/cms-static-page/cms-static-page.component.html
- src/app/shared/cms/components/cms-static-page/cms-static-page.component.spec.ts
- src/app/shared/cms/components/content-navigation/content-navigation.component.html
- src/app/shared/cms/components/content-navigation/content-navigation.component.spec.ts
- src/styles/pages/content-pages/page-content.scss
- src/styles/pages/content-pages/page-navigation.scss
Adapting the static content navigation styling to the required IAD/VD changes.
**Changes**
> fix: adapt static content navigation styling to meet new IAD/VD requirements

- server.ts
- tslint-rules/src/banSpecificImportsRule.ts
- tslint.json
[ ] Bugfix
[ ] Feature
[x] Other: tslint rule change
I often import the express router instead of @angular/router on accident.
You now get a tslint rule warning when importing the wrong router.
[ ] Yes
[x] No
> chore: adjust tslint rule for express/router

- src/app/core/facades/cms.facade.ts
[x] Bugfix
When re-fetching content for (several) content includes after the user logs out the `/cms/includes` REST calls might result in an error stating `Bad Request (Matrix parameter "pgid" is required if auth token is present)`.
This happens since the CMS content include REST calls are re-triggered if the `PGID` changes (that is the case when a user logs in or logs out). If at this point in time the `apiToken` cookie is not yet removed (something that is done when logging out) the re-triggered REST call is done without a `pgid` but still with the auth token information of the `apiToken` cookie. This results in the mentioned REST error. In general this seems to be a timing issue since the `apiToken` cookie will be deleted after a user logs out.
The timing issue is fixed so that the …
> fix: timing issue when fetching CMS content include data after logout

- src/app/core/utils/api-token/api-token.service.ts
- src/app/core/utils/cookies/cookies.service.ts
- src/app/extensions/punchout/pages/punchout/punchout-page.guard.ts
[x] Bugfix
A PWA punchout session does not work within an iframe that is often used by punchout systems, e.g. https://punchoutcommerce.com/tools/cxml-punchout-tester. This is due to necessary cookies (e.g. for the return url) not being set properly in such combinations.
The punchout cookies are set with "SameSite=None; Secure" that allows for the required cookies being set in iframe environments too.
[x] No
> fix: set punchout cookies with "SameSite=None; Secure" to work in iframes

- src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
- src/app/pages/contact/contact-page.component.html
- src/app/pages/product/product-page.component.html
- src/app/pages/recently/recently-page.component.html
- src/app/pages/recently/recently-page.component.spec.ts
- src/app/pages/recently/recently-viewed-all/recently-viewed-all.component.html
- src/app/pages/recently/recently-viewed-all/recently-viewed-all.component.spec.ts
- src/app/pages/search/search-no-result/search-no-result.component.html
- src/app/pages/search/search-no-result/search-no-result.component.spec.ts
- src/app/pages/search/search-page.component.html
- src/app/pages/search/search-page.component.spec.ts
- src/styles/global/breadcrumbs.scss
- src/styles/pages/account/account.scss
- src/styles/pages/category/search-result.scss
- src/styles/pages/productdetail/productdetail.scss
[x] Bugfix
The Breadcrumb styling (mainly the padding on top and bottom) is different for pages with side panel (category, my account, static content) or without (product detail, quick order, etc.).
Harmonized Breadcrumb styling with consistent padding on top and bottom.
[x] No
> fix: breadcrumb styling harmonization

- docs/concepts/configuration.md
- src/app/app.server.module.ts
- src/app/core/internationalization.module.ts
- templates/webpack/webpack.custom.ts
[x] Feature
`ngx-translate` translation files are loaded with [TranslateHttpLoader](https://github.com/ngx-translate/http-loader#1-setup-the-translatemodule-to-use-the-translatehttploader) on the browser side and a special translate loader on the server side. Due to this handling, the translation files are not automatically output-hashed via Angular CLI. This can lead to misbehavior, when new keys are added but the browser still holds the old translation file in the browser cache.
- Translation files are consistently loaded via webpack and automatically output-hashed
- ~~The old mechanism of `registerLocaleData` is exchanged with the [new one](https://angular.io/guide/i18n#import-global-variants-of-the-locale-data)~~ Doesn't work with FF
- Translation file ~~and Angular locale data~~ is …
> feat: load translations with webpack

- src/app/app.server.module.ts
- src/app/core/configurations/ngrx-state-transfer.ts
- src/app/core/configurations/state-keys.ts
- src/app/core/internationalization.module.ts
- src/app/core/services/localizations/localizations.service.spec.ts
- src/app/core/services/localizations/localizations.service.ts
- src/app/core/store/core/configuration/configuration.actions.ts
- src/app/core/store/core/configuration/configuration.effects.spec.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/configuration/configuration.integration.spec.ts
- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/store/core/configuration/configuration.selectors.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/app/core/utils/translate/fallback-missing-translation-handler.ts
- src/app/core/utils/translate/icm-translate-loader.ts
- src/app/core/utils/translate/translations.type.ts
[x] Feature
- Missing translations are silently replaced with the ones from the ngx-translate default lang or just the translation key is inserted
- The default lang is always pulled for client applications
- Missing translations trigger an error in the console, so that they can be detected (SSR logs, Sentry, Browser console)
- Pulling default fallbacks can be customized
- final SSR locale is transferred to the client to be used for initialization
[ ] Yes
[x] No
> feat: improve detecting missing translations

- src/app/core/configurations/injection-keys.ts
- src/app/core/models/product-listing/product-listing.mapper.spec.ts
- src/app/core/models/product-listing/product-listing.mapper.ts
- src/app/core/services/filter/filter.service.spec.ts
- src/app/core/services/filter/filter.service.ts
- src/app/core/services/products/products.service.ts
- src/app/core/store/content/parameters/parameters.effects.spec.ts
- src/app/core/store/content/parameters/parameters.effects.ts
- src/app/core/store/shopping/filter/filter.effects.spec.ts
- src/app/core/store/shopping/filter/filter.effects.ts
- src/app/core/store/shopping/product-listing/product-listing.actions.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
- src/app/core/store/shopping/product-listing/product-listing.reducer.ts
- src/app/core/store/shopping/product-listing/product-listing.selectors.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/search/search.effects.spec.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/environments/environment.model.ts
[x] Feature
Only one page size can be set for all master-page, category-page and search-page listings.
Page sizes for listings of master-page, category-page and search-page can also be set individually.
[ ] Yes
[x] No
> feat: individual page sizes for listings

- docs/concepts/localization.md
- projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.html
- projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.spec.ts
- src/app/core/internationalization.module.ts
- src/app/core/utils/translate/pwa-translate-compiler.spec.ts
- src/app/core/utils/translate/pwa-translate-compiler.ts
- src/app/core/utils/translate/translations.type.ts
- src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.html
- src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.spec.ts
- src/app/extensions/wishlists/pages/account-wishlist/account-wishlist-list/account-wishlist-list.component.html
- src/app/pages/search/search-result/search-result.component.html
- src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.html
- src/app/shell/header/mini-basket/mini-basket.component.html
- src/app/shell/header/mini-basket/mini-basket.component.spec.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Feature
ngx-translate does not support pluralization out of the box and a serious hack using i18nPlural pipe from Angular has to be used.
Added a custom translate compiler, that handles pluralization.
[ ] Yes
[x] No
Using the [ngx-translate-messageformat-compiler](https://www.npmjs.com/package/ngx-translate-messageformat-compiler) did not work and would also pull additional dependencies.
> feat: replace i18nPlural pipe usage with translate compiler

- src/app/core/directives/authorization-toggle.directive.ts
- src/app/pages/account-profile/account-profile-page.module.ts
- src/app/pages/account-profile/account-profile/account-profile.component.html
- src/app/pages/account-profile/account-profile/account-profile.component.spec.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
All b2b users can edit the company profile data no matter which permissions they have.
Issue Number: Closes #724
Only b2b users with permission B2B_MANAGE_USERS (admin) can edit the company profile data.
[ ] Yes
[x] No
> fix: add permission check to edit the company profile

- docker-compose.yml
- docs/guides/multi-site-configurations.md
- docs/guides/nginx-startup.md
- nginx/Dockerfile
- nginx/channel.conf.tmpl
- nginx/entrypoint.sh
[x] Feature
For Intershop CaaS environments, UAT and INT deployments are configured to use basic auth, so that the shop is not publicly visible or indexed by search engines.
This setup however is performed on the Kubernetes nginx ingress, where it doesn't differentiate between page responses and retrieval of static assets. Some of the assets can not be retrieved by the PWA without setting up cross-origin use-credentials, and even then (with multiple basic auth dialogs popping up), fonts are not properly retrieved.
The PWA nginx container can be set up using basic auth: https://github.com/intershop/intershop-pwa/blob/feat/nginx-basic-auth/docs/guides/nginx-startup.md#basic-auth
Whitelisting IPs is also supported.
The nginx only guards page responses and makes static assets freely …
> feat: basic auth support for nginx

- src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
- src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user selects a valid csv file on quick order page the add to cart button remains disabled.
Issue Number: Closes #734
The add-to-cart button will be enabled after the user has selected a valid csv file.
[ ] Yes
[x] No
> fix: quick order - enable the add-to-cart button after a valid csv file has been selected

- src/app/shared/components/line-item/line-item-edit/line-item-edit.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
If the feature toggle 'advancedVariationhandling' is turned off the edit link is shown for all products in the cart.
If the feature toggle 'advancedVariationhandling' is turned off the edit link is shown only for variation products in the cart.
[ ] Yes
[x] No
> fix: display edit line item link only for variation products

- src/app/pages/checkout-review/checkout-review/checkout-review.component.ts
- src/app/shared/components/basket/basket-address-summary/basket-address-summary.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user selects a payment method on checkout payment page that requires a redirect before checkout on the checkout review page an error message is wrongly shown: There is no shipping method available that allows these products to be shipped together.
After redirect before checkout the error message is only shown if an error occured.
[ ] Yes
[x] No
> fix: don't display multiple bucket message after redirect before checkout

- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
Payment costs can be configured in the ICM backoffice.
If a payment method has costs with value '0' they will be displayed on checkout payment page.
If a payment method has costs with value '0' they won't be displayed on checkout payment page.
[ ] Yes
[x] No
> fix: don`t display payment costs on checkout payment page if the value is zero

- src/app/core/directives/server-html.directive.ts
[x] Feature
Callback handlers in `ServerHtmlDirective` don't see the `MouseEvent` and can not do something like `event.preventDefault()`.
The `MouseEvent` is forwarded to the callback handler as an optional argument.
[ ] Yes
[x] No
> feat: forward mouse event to callback handler in server-html directive

- src/app/core/store/core/router/router.integration.spec.ts
- src/app/core/store/core/server-config/server-config.effects.spec.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/jest-serializer/NgrxActionSerializer.js
Router actions when serialized in jest snapshots contain unnecessary properties. The cancel action even prints out (for whatever reason) a slice of the current NgRx state, that always has to be updated when something changes:
https://github.com/intershop/intershop-pwa/blob/c08eebee46ddbcfcd16477781c1b4dbb5ab982f0/src/app/core/store/shopping/shopping-store.spec.ts#L979-L982
Router actions are only printing the navigation URLs associated with then.
[ ] Yes
[x] No
> test: simplify router action serialize

- src/app/core/facades/cms.facade.ts
[x] Bugfix
The "Global" Scope configuration of the "Product List (Filter)" component is not evaluated right in the PWA rendering logic.
The "Global" Scope configuration of the "Product List (Filter)" component with the value "GlobalScope" instead of "Global" is evaluated right in the PWA rendering logic.
[x] No
> fix: add support for CMS component "Product List (Filter)" - use correct scope configuration

- docs/guides/formly.md
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.html
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.spec.ts
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.ts
- src/app/pages/checkout-address/checkout-address-page.module.ts
- src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.html
- src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.spec.ts
- src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.ts
- src/app/shared/formly/formly.module.ts
- src/app/shared/formly/types/radio-field/radio-field.component.html
- src/app/shared/formly/types/radio-field/radio-field.component.spec.ts
- src/app/shared/formly/types/radio-field/radio-field.component.ts
- src/app/shared/formly/wrappers/radio-horizontal-wrapper/radio-horizontal-wrapper.component.html
- src/app/shared/formly/wrappers/radio-horizontal-wrapper/radio-horizontal-wrapper.component.spec.ts
- src/app/shared/formly/wrappers/radio-horizontal-wrapper/radio-horizontal-wrapper.component.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Checkout Address Anonymous component contains formly and reactive form components.
Checkout Address Anonymous component should only contain formly components.
[ ] Yes
[x] No
> refactor: add formly components to checkout address anonymous component

- e2e/test-universal.sh
- src/app/extensions/seo/store/seo/seo.effects.ts
Production PWAs should always be run in a secure context but the PWA SSR container itself is usually not run in a secure context in production. The SSL certification is handled outside the PWAs context. This makes it hard to get the correct protocol from the PWA SSR context even though it is a secure context to the user. For this reason we always set the canonical link URLs and the 'og:url' to 'https:' to prevent false non indexable canonical links.
[x] Bugfix
[x] No
Issue number: #749 
[AB#64674](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64674)
> fix: set canonical link and 'og:url' info independent from SSR container context to 'https'

- server.ts
[x] Bugfix
When ICM backend is not protected with a valid SSL certificate the SSR rendering process logs a not very helpful message into std-out.
Issue Number: Closes #756
Log some information into SSR std-out that SSL trust cannot be established.
[x] No
[AB#64704](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64704)
> SSL certificate error message

- angular.json
- scripts/find-dead-code.ts
- src/app/core/state-management.module.ts
- src/app/core/store/store-devtools.module.prod.ts
- src/app/core/store/store-devtools.module.production.ts
- src/app/core/store/store-devtools.module.ts
- tslint.json
[x] Feature
The current PWA configuration exposes the ngrx store debugging information in production deployments too.
Since this is seldomly wanted in production environments the new configuration disables this information completely for such deployments.
[x] No
https://ngrx.io/guide/store-devtools/recipes/exclude
[AB#64608](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64608)
> feat: disable ngrx Store Devtools in production environments

- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Bugfix
If the registration failed because the customer could not be created only an error key customer.creation_failed.error is displayed.
Issue Number: Closes #786
An error message is shown.
[x] No
see the issue #786 for steps to repeat
[AB#65466](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65466)
> fix: display an error message in case the customer creation failed

- .github/workflows/dead-code.yml
- .github/workflows/development.yml
- .github/workflows/docs.yml
- .github/workflows/integration.yml
- .github/workflows/updates.yml
- .github/workflows/windows.yml
The setup-node action v2 now supports dependency caching. Maybe this can help us make our ci pipeline faster.
https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
[x] No
[AB#64630](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64630)
> ci: enable setup-node caching

- e2e/cypress/integration/pages/account/add-to-order-template.module.ts
- e2e/cypress/integration/pages/account/order-templates-details.page.ts
- src/app/extensions/order-templates/facades/order-templates.facade.ts
- src/app/extensions/order-templates/order-templates.module.ts
- src/app/extensions/order-templates/shared/select-order-template-form/select-order-template-form.component.html
- src/app/extensions/order-templates/shared/select-order-template-form/select-order-template-form.component.spec.ts
- src/app/extensions/order-templates/shared/select-order-template-form/select-order-template-form.component.ts
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.spec.ts
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.ts
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[x] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Currently, the order template modal still uses the old way of defining forms. We want to change this to formly as part of the rework.<br /><br />## What Is the New Behavior?<br /><br />Now, the order template modal uses formly to construct the form. Additionally, the component has been refactored to be more functional.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br …
> refactor: adapt order template modal with formly

- src/app/pages/checkout-shipping/checkout-shipping-page.component.html
- src/app/pages/checkout-shipping/checkout-shipping-page.component.spec.ts
- src/app/pages/checkout-shipping/checkout-shipping-page.component.ts
<br /><br />## PR Type<br /><br /><br /><br />[x] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Currently, the checkout shipping page has a skipped test and an error message is not shown. This is because the nextDisabled variable is changed inside a subscribe block and not automatically updated in the template. <br /><br />## What Is the New Behavior?<br /><br />Now, the subscription updates the component to be checked in the next change detection cycle. This fixes the issue and …
> fix: checkout shipping selection error and test

- src/app/core/models/customer/customer.interface.ts
- src/app/core/models/customer/customer.mapper.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
After login the companyName attribute of the response has been taken to decide if a get request for the privateCustomers REST resource is necessary
Now the customerType attribute of the response is taken as criterion for this decision.
[x] No
[AB#65496](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65496)
> refactor: use customerType to differentiate between private and business customers

- src/app/pages/account-addresses/account-addresses-page.component.html
- src/app/pages/account-addresses/account-addresses-page.component.ts
- src/app/pages/account-addresses/account-addresses/account-addresses.component.html
- src/app/pages/account-addresses/account-addresses/account-addresses.component.spec.ts
- src/app/pages/account-addresses/account-addresses/account-addresses.component.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
- src/app/shared/forms/utils/forms.service.spec.ts
- src/app/shared/forms/utils/forms.service.ts
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[x] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Currently, the account-address component uses the old select-address component, which is a specification of ish-select.<br /><br /><br />## What Is the New Behavior?<br /><br />Now, the page uses formly and is refactored to be more functional.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br /> …
> refactor: adapt account-address component with formly

- src/app/pages/contact/contact-form/contact-form.component.ts
- src/app/shared/formly/extensions/translate-select-options.extension.ts
<br /><br />## PR Type<br /><br /><br /><br />[x] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Selectboxes don't work anymore. You can't select values even though the selection is updated in the model (which is the reason no tests failed).<br /><br />## What Is the New Behavior?<br /><br />Formly 5.10.22 introduced a bugfix that causes expressionProperties that return observables to always be reevaluated. This exposed a flaw in the translate-select-options extension. I have now …
> fix: translate-select-options without expressionProperty

- src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
- src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.ts
[x] Bugfix
Registration password fields were of the wrong type
Registration password fields are now correctly hidden.
[x] No
[AB#65840](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65840)
> fix: remove type: text from registration password fields

- .dockerignore
- .gitignore
- dist/healthcheck.js
- dist/livenessprobe.js
- dist/readinessprobe.js
[x] Feature
K8s uses a liveness and readiness probes to check if a pod is available and ready to accept requests. Due to the implemented pm2 process manager a new liveness and readiness probe is needed.
New scripts for liveness and readiness probes are added to project, which can be used in k8s deployments.
The readiness probe checks if at least one process is available for each theme.
The liveness probe checks for each theme, that at least one process with status 'online' or 'launching' exists. 
The healthcheck should not be used for liveness and readiness probes and should not check, if the ICM is available.
[ x ] No
[AB#65808](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65808)
> feat: readiness and liveness probe for pm2

- src/app/core/facades/product-context.facade.ts
- src/app/core/models/product/product.helper.ts
- src/app/core/store/customer/basket/basket-items.effects.spec.ts
- src/app/core/store/customer/basket/basket-items.effects.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.selectors.spec.ts
- src/app/core/store/customer/customer-store.spec.ts
If projects don't want to use the mini-cart but instead use toasts for displaying add-to-cart success feedback, they can't use the `addItemsToBasketSuccess` out of the box because it does not include the added items.
`items` are also included in `addItemsToBasketSuccess`
[ ] Yes
[x] No
[AB#65942](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65942)
> refactor: add items to addItemsToBasketSuccess action

- schematics/customization/add/index.js
[x] Bugfix
[ ] Feature
[ ] Other: 
**Intro**
When executing customization schematic to add a new customization theme like so:
```zsh
node schematics/customization/add customer
```
The resulting process changes a bunch of files. One of which is the list of active-themes in `package.json` file. That list is also used for generating `dist/ecosystem.yml` and `dist/ecosystem-ports.js` files which are important for operating multiple themed PWAs in one container.
**Problem**
SSR requests without a theme parameter end up at the process behind port 4200. This is the …
> fix: insert none default theme at the end of active themes

- src/app/extensions/quickorder/shared/quickorder-repeat-form/quickorder-repeat-form.component.html
- src/styles/global/line-item.scss
<br /><br />## PR Type<br /><br /><br /><br />[x] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br />Heading of quickorder form table isn't in line to the quantity fields. Between form elements is to much space.<br /><br />## What Is the New Behavior?<br />The form elements stand closer together, so the quantity field is in line with its heading.<br /><br />## Does this PR Introduce a Breaking Change?<br />[ ] Yes<br />[x] No<br /><br />## Other Information<br /> …
> fix spaces in quickorder form

- src/typings.d.ts
[x] Bugfix
`THEME` variable is typed as `boolean`.
`THEME` variable is typed as `string`.
[ ] Yes
[x] No
[AB#66169](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66169)
> fix: THEME variable should be string

- .github/workflows/demo-server-down.yml
- .github/workflows/demo-server.yml
[ ] Bugfix
[ ] Feature
[ ] Other: 
Every synchronized (means no git conflicts exist) GitHub pull request creates demo server installations in Azure to showcase whatever changes. Two installations per PR. One for B2B and one for B2C.
Since PWA 1.0 we can host multiple themes in one installation. Leaving the necessity to deploy two containers. We just need to adjust the link to both.
[AB#69177](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69177)
> Work on PR demo server deployment

- jest.config.js
- package.json
Whenever `jest` can occupy all CPUs of the developer's machine, it will! 
No more computer freezes.
[ ] Yes
[x] No
[AB#66030](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66030)
> chore: limit jest load globally to 75%

- src/app/core/models/attachment/attachment.interface.ts
- src/app/core/models/attachment/attachment.mapper.spec.ts
- src/app/core/models/attachment/attachment.mapper.ts
- src/app/core/models/attachment/attachment.model.ts
- src/app/core/models/product/product.interface.ts
- src/app/core/models/product/product.mapper.spec.ts
- src/app/core/models/product/product.mapper.ts
- src/app/core/models/product/product.model.ts
- src/app/pages/product/product-detail-info-accordion/product-detail-info-accordion.component.html
- src/app/pages/product/product-detail-info-accordion/product-detail-info-accordion.component.spec.ts
- src/app/shared/components/product/product-attachments/product-attachments.component.html
- src/app/shared/components/product/product-attachments/product-attachments.component.spec.ts
- src/app/shared/components/product/product-attachments/product-attachments.component.ts
- src/app/shared/shared.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
- src/styles/global/global.scss
- src/styles/pages/productdetail/productdetail.scss
[x] Feature
The PWA does currently not support the display of product attachments.
Issue Number: Closes #767
Product attachment information are displayed on product detail page similar to the Responsive Starter Store regarding the IAD changes mentioned in issue #767.
[ ] Yes
[x] No
[AB#66193](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66193)
> feature: product attachments

- src/app/shell/header/header-navigation/header-navigation.component.html
- src/app/shell/header/header-navigation/header-navigation.component.spec.ts
- src/app/shell/header/header-navigation/header-navigation.component.ts
- src/app/shell/header/sub-category-navigation/sub-category-navigation.component.html
- src/app/shell/header/sub-category-navigation/sub-category-navigation.component.spec.ts
[x] Bugfix
Currently the environment configuration provides a parameter `mainNavigationMaxSubCategoriesDepth` that can be used to configure the main navigation hover depth. Unfortunately it does not work with `0` as a value to completely disable the main navigation hover menu.
The environment configuration parameter `mainNavigationMaxSubCategoriesDepth` can be used to configure the main navigation hover depth with `0` as a value to completely disable the main navigation hover menu.
[ ] Yes
[x] No
[AB#69233](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69233)
> fix: mainNavigationMaxSubCategoriesDepth configuration with '0' fails to disable main navigation hover menu

- scripts/build-multi-pwa.js
- scripts/build-pwa.js
[x] Bugfix
The `DEPLOY_URL` functionality (#630) is broken with the multi-config build (#775) because extra arguments are not properly propagated.
Fixed
[ ] Yes
[x] No
[AB#66096](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66096)
> fix: propagate extra arguments in build:multi script

- angular.json
- e2e/cypress/integration/specs/system/cookie-consent.b2c.e2e-spec.ts
- e2e/cypress/support/commands.js
- src/styles/components/footer/footer.scss
- templates/webpack/webpack.custom.ts
[x] Bugfix
When using component styles with imports in them, the build breaks using the new approach.
- purgeCSS tries to minify unrelevant themes
- the server build fails because the style import root is not set correctly
Fixed
[ ] Yes
[x] No
[AB#66091](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66091)
> fix: server build with component styles

- scripts/clean-up-localizations.js
Customizing the `clean-up-localizations` script with new keys, that should be kept, means modifying a one-line regular expression, that is always hard to read whenever conflicts arise when upgrading to the newest PWA version.
The regular expression is split into an array of regular expressions like the one for PurgeCSS whitelist.
[ ] Yes
[x] No
[AB#66031](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66031)
> refactor: optimize clean-up-localizations script for projects

- src/polyfills.ts
[x] Feature
Convenience method `version()` as a global polyfill, that can be used to inspect the versions of a deployed PWA.
[ ] Yes
[x] No
From the demo server:
It looks like the GitHub CI pipeline does not set a displayVersion 🤔 
[AB#69394](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69394)
> feat: add version method for inspecting version information

- src/setupJest.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Currently, when you add a unit test that uses toMatchInlineSnapshot and one of the 3 simple variables is being tested (PRODUCTION_MODE, NGRX_RUNTIME_CHECKS and THEME), the result for these variables will be the whole function (eg: for THEME, function () { return 'default'; }).
The snapshot will have only the intended value (eg: default for THEME).
[ ] Yes
[x] No
> fix: use get instead of value in global variables

- templates/nginx.conf
[x] Bugfix
After the latest changes to the noSSR PWA Docker container the container only worked for the '/' route but not for any other route anymore, e.g. '/home'. Such routes return a 404 error from nginx.
Reverted to the former location matching in nginx to restore previously working noSSR container routing.
[x] No
[AB#69756](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69756)
> fix: noSSR PWA Docker container does not support deep links

- docs/guides/nginx-startup.md
- nginx/Dockerfile
- nginx/channel.conf.tmpl
[x] Feature
Cache duration of pre-rendered pages in nginx is hard-coded to 10 minutes for successful pages and 60 minutes for 404 pages and cannot be configured individually for different environments.
Introduced two new environment variables for nginx container for customization.
[ ] Yes
[x] No
[AB#69867](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69867)
> feat: customizable nginx cache duration

- src/app/shared/components/product/product-image/product-image.component.spec.ts
- src/app/shared/components/product/product-image/product-image.component.ts
[x] Bugfix
Occasionally the console output contains the error `missing translation in en_US: product.image.text.alttext`. This happens because the `product-image` component accesses this translation with `TranslateService.instant` when translations are not yet loaded correctly.
Refactored to use `TranslateService.get`
[ ] Yes
[x] No
[AB#69899](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69899)
> fix: use translate get instead of instant for product-image component

- src/app/core/utils/translate/pwa-translate-compiler.ts
Translate Compiles are re-done for every value when the translations are initialized. Especially in the SSR process caching can improve performance.
Once compiled, translation templates are cached and reused.
[ ] Yes
[x] No
[AB#69905](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69905)
> perf: cache compiled translations in PWA process

- docs/concepts/localization.md
- src/app/core/utils/translate/pwa-translate-compiler.ts
The PWA Translate Compiler compiles translation keys regardless of length, but if huge values are used (i.e. for injecting large quantities of HTML), the regular expressions evaluation becomes costly and blocks rendering.
- Large translation values (>1000 characters) are not compiled.
- A development warning is printed in the console.
[ ] Yes
[x] No
[AB#69904](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69904)
> perf: prevent compiling translations with very large values

- src/app/core/utils/url-form-params.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
When applying search filter with characters like "&" or "/" leads to false encodet parameters in the rest request.
When applying search filter with special characters, parameters are encodet properly.
[ ] Yes
[x] No
The change from decodeURI to decodeURIComponent works for the filters, but wasn't tested enough and might lead to unexpected behavior elsewhere.
> fix: filter with special characters

- src/app/shared/components/product/product-quantity/product-quantity.component.html
- src/app/shared/components/product/product-quantity/product-quantity.component.spec.ts
- src/app/shared/components/product/product-quantity/product-quantity.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
When you enter negative numbers as product quantity, the form will display a warning and not set the value.
~~When you enter negative numbers as product quantity, they get inverted to their positive counterparts and the value can be set. This prevents negative numbers from being used in the first place as this doesn't make sense for quantity values.~~
Depending on the browser (Chromium based works, others not) the added input pattern `[0-9]*` prevents the adding of invalid characters (letters etc.) but not '-'. But this is …
> fix: restrict product-quantity input to numbers (browser dependend)

- .vscode/extensions.json
- .vscode/settings.json
[x] Other: IDE setting
Plugin used for bracket pair colorization: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer
VSCode setting: https://www.youtube.com/watch?v=elNuPq3GFXg
[ ] Yes
[x] No
[AB#69907](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69907)
> chore: switch from extension to vscode setting for bracket pair colorization

- src/app/core/store/shopping/categories/categories.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
When visiting a category or product page, an effect loads details for all categories in the category path with additional REST API calls. Yet, all of the data that is needed to render the breadcrumb is already properly extracted from the visited categories `categoryPath` attribute.
- Only the selected category is loaded at detail level
- adapted `shopping-store.spec` mocks to represent the proper data
- less calls being made to the ICM
[ ] Yes
[x] No
[AB#69900](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69900)
> perf: remove individual loading of path categories

- docs/guides/customizations.md
- docs/guides/multiple-themes.md
- schematics/src/helpers/override/schema.json
- templates/webpack/webpack.custom.ts
- tslint.json
[x] Feature
Currently it's not possible to _always_ override a file for every theme. All themes have to be added to the filename.
By using the virtual theme "all", a file is always switched in if no theme-specific override is defined.
[ ] Yes
[x] No
[AB#66222](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66222)
> feat: add virtual theme "all" for always overriding files

- src/app/core/guards/identity-provider-logout.guard.ts
- src/app/core/identity-provider/auth0.identity-provider.ts
- src/app/core/identity-provider/identity-provider.interface.ts
- src/app/extensions/punchout/pages/punchout/punchout-page.guard.ts
[x] Bugfix
If you are logged into the PWA, there will some kind of persistent user state saved to your browser, depending on the identity provider. Especially with SSO this can lead to all kinds of problems if you are logged into the PWA and then try to do cxml punchout in the same browser.
This PR will attempt to fix this behaviour so that cxml punchout works even if the user forgot to log out of the regular PWA or has some other uncleaned state in their browser.
Punchout will work regardless of persistent user state.
[x] No
[AB#69525](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69525)
> fix: enable cxml punchout with unclean user state

- Dockerfile
- docker-compose.yml
[x] Feature
Docker build performs multi-theme build for all active themes in `package.json`.
Docker build also takes active themes as an argument for overriding active themes in `package.json`.
Useful for locally speeding up builds in `docker-compose.yml`.
[ ] Yes
[x] No
[AB#69390](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69390)
> feat: add option for only building specific themes in docker build

- .husky/post-checkout
[x] Other: Convenience
Sometimes you forget to `npm install` when changing branches
A `post-checkout` hook detects `package.json` changes and performs the `npm install` automagically 🧙 
[ ] Yes
[x] No
[AB#69936](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69936)
> feat: helper for never forgetting npm install on branch change

- docs/concepts/state-management.md
- src/app/core/configurations/ngrx-state-transfer.spec.ts
- src/app/core/configurations/ngrx-state-transfer.ts
The state transfer is filtering out slices of the state starting with underscore before passing the NgRx state to the client. When there are a lot of entries in the store (i.e. when using server translations like https://pwa-ish-demo.test.intershop.com/INTERSHOP/rest/WFS/inSPIRED-inTRONICS-Site/rest;loc=en_US/localizations?searchKeys=pwa-) this process takes some time on every SSR render.
- Filtering is restricted to two levels
- Documentation for excluding properties with underscore
[ ] Yes
[x] No
[AB#70157](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/70157)
> perf: restrict NgRx state transfer filtering to two levels

- .vscode/extensions.json
- .vscode/launch.json
[x] Other: VS Code extension cleanup
[x] No
[AB#70179](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/70179)
> chore: remove deprecated "Debugger for Chrome" as recommended extension and clean up launch configurations

- src/app/extensions/quickorder/shared/quickorder-csv-form/quickorder-csv-form.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
Quickorder file message overlaps button due to it being wrapped inside a div with absolute position.
Issue Number: Closes #827
Message doesn't overlap button anymore
[ ] Yes
[x] No
Absolute positioning in parent div caused the overlaping. Since there is no use in having absolute positioning here it was simply removed from the div.
> fix: file error message doesnt overlap button

- templates/webpack/webpack.custom.ts
[x] Bugfix
Files for differential loading are not correct: 
- add `> 0.5%` as an only rule to `.browserslistrc`
- `npm run build client`
- observe overlapping filenames for lazy differential loading chunks:
```
Initial Chunk Files                             | Names                   |      Size
vendor-es5.6bfd51788ebdd6c8e837.js              | vendor                  | 844.88 kB
vendor-es2015.6bfd51788ebdd6c8e837.js           | vendor                  | 720.08 kB
...
| Initial ES5 Total       |   1.58 MB
| Initial ES2015 Total    |   1.32 MB
Lazy Chunk Files                                | Names                   |      Size
common.5d231b554730def6758e.js                  | common                  | 648.54 kB
common.5d231b554730def6758e.js                  | common                  | …
```
> fix: repair chunk output file names for differential loading

- package-lock.json
- package.json
- src/styles/components/header/language-switch.scss
- src/styles/components/header/search-container.scss
- src/styles/components/header/user-information-mobile.scss
- src/styles/global/buttons.scss
- src/styles/global/forms/forms.scss
- src/styles/global/global.scss
- src/styles/global/icons.scss
- src/styles/global/panel.scss
- src/styles/global/share-tools.scss
- src/styles/global/tables.scss
- src/styles/pages/account/account-navigation.scss
- src/styles/pages/category/filter-panel.scss
- src/styles/pages/category/filter-row.scss
- src/styles/pages/category/product-list.scss
- src/styles/pages/checkout/shopping-cart.scss
- src/styles/pages/content-pages/page-content.scss
- src/styles/pages/homepage/homepage.scss
- src/styles/pages/productdetail/product-images.scss
- src/styles/pages/productdetail/product-info.scss
- src/styles/pages/productdetail/productdetail.scss
* remove `@use 'sass:math';` and replace `math.div();`
* cleanup after temporary changes from #751
closes: #759
BREAKING CHANGE: We no longer use `@use 'sass:math';` and `math.div();` in our `.scss` files but instead switched to the new Bootstrap default way using `divide()`. This is more a note to check your styling customizations for possible adaptions. Both ways should still work together and adaptions are not required.
[x] Bugfix
[AB#70931](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/70931)
> fix: use newest Bootstrap release 4.6.1 with own divide() function

- src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.html
- src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.spec.ts
- src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.ts
[ ] Bugfix
[X] Feature
[ ] Other: 
Save for later feature is not available for CyberSource credit card.
Issue Number: Closes #60557
Checkbox is visible when Save for later option is enabled for CyberSource credit card.
[ ] Yes
[X] No
> feat: cybersource creditcard save for later checkbox

- docs/concepts/configuration.md
- docs/guides/nginx-startup.md
- nginx/entrypoint.sh
- nginx/templates/multi-channel.conf.tmpl
- src/app/core/guards/identity-provider-logout.guard.ts
- src/app/core/identity-provider.module.ts
- src/app/core/identity-provider/identity-provider.factory.ts
- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.module.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.spec.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
- src/app/extensions/punchout/pages/punchout/punchout-page.guard.ts
- src/app/extensions/punchout/store/punchout-functions/punchout-functions.effects.ts
- tslint.json
[x] Feature
OCI Punchout Sessions gets lost after Reload.
OCI Punchout Sessions is available after Reload. Therefore is the punchout guard refactored to a new identity provider, which saves the actual basketId to the session storage. Furthermore it is possible to override the actual identity provider on specific routes. 
[ ] Yes
[ ] No
[AB#70891](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/70891)
> feat: punchout identity provider

- src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.html
- src/app/shared/components/basket/basket-promotion/basket-promotion.component.html
- src/app/shared/components/basket/basket-promotion/basket-promotion.component.spec.ts
[x] Bugfix
In the order/basket cost summary there is no default text, if a promotion discount has been applied and promotion messages are disabled. A user only sees that the price was reduced but might be confused why. 
Now, a localizable default value is displayed.
[x] No
[AB#71599](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/71599)
> fix: display a default promotionname if promotionmessaging disabled

- docs/guides/ssr-startup.md
- src/app/app.server.module.ts
- src/app/core/interceptors/universal-cache.interceptor.ts
- src/app/core/utils/functions.spec.ts
- src/app/core/utils/functions.ts
[x] Feature
Repeated calls to the same endpoints on every SSR render:
```
/INTERSHOP/rest/WFS/inSPIRED-inTRONICS-Site/rest;loc=en_US/configurations
/INTERSHOP/rest/WFS/inSPIRED-inTRONICS-Site/rest;loc=en_US/localizations?searchKeys=pwa-
```
Introduced `CACHE_ICM_CALLS` environment property to activate SSR-only short-time caching.
[ ] Yes
[x] No
Alternative solution (less intrusive) to #867 
[AB#70117](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/70117)
> feat: SSR-only ICM call cache interceptor

- src/app/shared/cms/components/cms-image-enhanced/cms-image-enhanced.component.html
[x] Bugfix
`CMSImageEnhancedComponent` applies the pagelet configuration paramter `CSS Class` to the component `div` and the `img` tag. This duplication is not intended and can lead to unexpected styling effects.
The `CSS Class` configuration parameter is only applied to the component `div`.
[x] No
[AB#71848](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/71848)
> fix: remove wrongly used component CSS class from 'img' tag

- nginx/templates/multi-channel.conf.tmpl
[x] Bugfix
Query parameters are duplicated at rewrite.
Issue Number: Closes #929
Query parameters are not duplicated at rewrite.
[ ] Yes
[ x ] No
solution: http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite
[AB#71880](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/71880)
> fix: Query parameters are duplicated during multi-site nginx rewrite

- src/app/extensions/quoting/services/quoting/quoting.service.spec.ts
- src/app/extensions/quoting/services/quoting/quoting.service.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user has no cart and he tries to add a quote to cart he gets only a cart-not-found-error message.
Issue Number: Closes #947 
If the user has no cart a new cart will be automatically created before the quote is added to cart.
[ ] Yes
[x] No
> fix: add quote to cart in case no cart exists

- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.html
- src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.html
- src/app/extensions/order-templates/shared/basket-create-order-template/basket-create-order-template.component.html
- src/app/extensions/order-templates/shared/basket-create-order-template/basket-create-order-template.component.ts
- src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.html
- src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.html
- src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.ts
- src/app/extensions/quoting/shared/product-add-to-quote/product-add-to-quote.component.html
- src/app/extensions/quoting/shared/product-add-to-quote/product-add-to-quote.component.ts
- src/app/extensions/quoting/shared/quote-line-item-list-element/quote-line-item-list-element.component.html
- src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.html
- src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.ts
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/pages/product/product-detail/product-detail.component.html
- src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.html
- src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.html
- src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
- src/app/shared/components/product/product-add-to-compare/product-add-to-compare.component.html
- src/app/shared/components/product/product-add-to-compare/product-add-to-compare.component.ts
- src/app/shared/components/product/product-row/product-row.component.html
- src/app/shared/components/product/product-tile/product-tile.component.html
[x] Bugfix
There are components with an input named class which can lead to different and not desired behavior (see #970).
Issue Number: Closes #970
No component should use an Input named 'class'.
[x] Yes
BREAKING CHANGE: The input parameter `class` was changed to `cssClass` for the following components `ish-basket-create-order-template`,`ish-lazy-basket-create-order-template`, `ish-lazy-product-add-to-order-template`,`ish-lazy-product-add-to-quote`, `ish-lazy-product-add-to-wishlist`, `ish-product-add-to-basket`, `ish-product-add-to-compare`, `ish-product-add-to-order-template`, `ish-product-add-to-quote`, `ish-product-add-to-wishlist`. All uses of these components need to be adapted in custom code.
[AB#72542](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_worki …
> fix: rename component inputs named 'class' to 'cssClass'

- package-lock.json
- package.json
- src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.ts
- src/app/pages/product/product-images/product-images.component.html
- src/app/pages/product/product-images/product-images.component.spec.ts
- src/app/pages/product/product-images/product-images.component.ts
- src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
- src/app/shared/components/product/products-list/products-list.component.ts
- src/styles/global/swiper.scss
- src/styles/main.scss
[ ] Bugfix
[ ] Feature
[ ] Other: 
Currently Swiper 6 (old) is used
Now Swiper 7 (latest) is used
[ ] Yes
[ ] No
- With the new version 7, Swiper is now a pure ESM package and some APIs were deprectated.
- Updating to version 7 breaks some tests which needs to be fixed (this might be due to the new ESM structure)
> chore: update swiper 6 to 7

- e2e/cypress/integration/pages/meta-data.module.ts
- e2e/open-cypress.js
- e2e/package.json
[x] Other: Cypress update
Cypress 7.x is used to execute e2e tests.
Cypress is updated to the latest version 9.x.
[x] No
[AB#72819](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/72819)
> deps: update cypress from 7.x to 9.x

- schematics/src/eslint-rule/factory.ts
Remove a leftover console.log statement from eslint rule schematic.
[AB#73586](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/73586)
> fix: remove console.log from schematic

- src/app/app.server.module.ts
[x] Bugfix
- start SSR with wrong configuration and logging enabled: (linux) `LOGGING=true ICM_CHANNEL=blubb npm run start`
- trigger render for any SSR page
-> observe log output:
```
ERROR [object Object]
ERROR [object Object]
...
```
Output is stringified using JSON.stringify if possible.
[ ] Yes
[x] No
[AB#72609](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/72609)
> fix: stringify SSR error if possible

- src/app/core/utils/translate/pwa-translate-compiler.ts
[x] Bugfix
`translate` functionality of [`PWATranslateCompiler`](https://github.com/intershop/intershop-pwa/blob/892a1ef31a4442a0bda2a17ac889eaca8ed5e5c4/src/app/core/utils/translate/pwa-translate-compiler.spec.ts#L167) breaks on SSR after the first SSR prerender.
- add a translation key using the `translate` functionality:
```
"test.translate.key": "Welcome to {{ translate, seo.defaults.description }}",
```
- use this key on some page:
```html
{{ 'test.translate.key' | translate }}
```
- start SSR: `npm run start`
- trigger an SSR render for that page multiple times
-> it will work properly the first time, but for every subsequent prerender the following errors are displayed in the console:
```
ERROR Error Injector has already been destroyed. at …
```
> fix: lazily resolve translate service in translate compiler

- docs/guides/migrations.md
- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/facades/selected-product-context.facade.ts
- src/app/core/models/product/__snapshots__/product.mapper.spec.ts.snap
- src/app/core/models/product/product.mapper.ts
[x] Bugfix
product maxOrderQuantity defaults to 100 and does not consider ICM server setting for basket.maxItemQuantity
ICM server setting for basket.maxItemQuantity is used as validator for product quantity if no specific settings are defined on the product.
[ ] Yes
[x] No
[AB#73724](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/73724)
It looks like the ICM API _still_ does not support getting maxOrderQuantity and stepOrderQuantity attributes in the list call... 😢
> fix: respect ICM setting basket.maxItemQuantity

- src/app/core/directives.module.ts
- src/app/core/directives/scroll.directive.ts
- src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.html
- src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.spec.ts
- src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.ts
[x] Feature
On checkout error message doesn't get scrolled to
Issue Number: Closes #848 
When the checkout has some errors, the browser will scroll to it
[x] No
Uses Scrolling Directive developed for #911 
[AB#71917](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/71917)
> Scrolling to error message

- src/app/pages/basket/basket-page.component.html
- src/app/pages/basket/basket-page.component.spec.ts
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/pages/category/category-categories/category-categories.component.html
- src/app/pages/category/category-categories/category-categories.component.spec.ts
- src/app/pages/category/category-products/category-products.component.html
- src/app/pages/category/category-products/category-products.component.spec.ts
- src/app/pages/product/product-detail/product-detail.component.html
- src/app/pages/product/product-detail/product-detail.component.spec.ts
- src/app/pages/product/product-detail/product-detail.component.ts
- src/app/pages/product/product-page.component.html
- src/app/pages/product/product-page.component.spec.ts
- src/app/pages/product/product-page.component.ts
- src/app/pages/search/search-no-result/search-no-result.component.html
- src/app/pages/search/search-no-result/search-no-result.component.spec.ts
- src/app/pages/search/search-result/search-result.component.html
- src/app/pages/search/search-result/search-result.component.spec.ts
[x] Feature
With ICM 7.10.38-LTS demo content artifacts are provided to manage CMS content at different places within category, family, product, search, and basket pages. The PWA does not use these demo content artifacts.
The PWA uses demo content artifacts and can present demo content provided in ICM.
[ ] Yes
[x ] No
ICM release 7.10.38-LTS is necessary.
[AB#72311](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/72311)
> feat: use demo content artifacts

- src/app/extensions/punchout/services/punchout/punchout.service.ts
If a new punchout type want to be added all request of this new type will call the "cxml" rest url. 
New punchout types will use its name for the rest call. You can add new types, when the rest url is the same.
[x] No - only the fallback to `cxml1.2` no longer works
[AB#73848](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/73848)
> refactor: add dynamic punchout type to punchout service

- nginx/entrypoint.sh
[x] Bugfix[ ] Feature
[ ] Other: 
When starting nginx container with `CACHING_IGNORE_PARAMS_SOURCE` environment variable set. You get to see this.
```
entrypoint.sh: 39: [: missing ]
```
No error is printed
[ ] Yes
[x] No
[AB#73908](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/73908)
> fix: fix missing space on caching ignore (entrypoint.sh)

- server.ts
- src/ssr/server-scripts/build-ecosystem.js
[x] Other: Logging optimization
- Log output is prepended with timestamps for stdout but not stderr by pm2. If run in an Intershop CaaS environment, datadog will also provide timestamps
- Multiple PWA instances running in parallel inside the container are not easily distinguishable 
- timestamps removed
- pm2 process ids prepended
[ ] Yes
[x] No
[AB#72619](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/72619)
> chore: pm2 logging adaptions for Intershop CaaS

- .eslintrc.json
[x] Other: ESLint configuration
Many eslint rules are configured to cause an error, which is sometimes disruptive.
The eslint rules have been checked to cause only an error if it is necessary. All other rules only cause a warning.
[x] No
[AB#73844](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/73844)
> chore: configure eslint rules to show warnings instead of errors

- scripts/icm-cache.js
[x] Feature
local ICM cache for (performance) testing purposes.
[x] No
[AB#69659](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69659)
> feat: local ICM cache for (performance) testing purposes

- e2e/cypress/integration/specs/checkout/checkout-cost-center-multiple.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/shopping/search-products.b2b.e2e-spec.ts
- e2e/package.json
- package-lock.json
- package.json
[x] Other: e2e test fix
The search products b2b e2e test fails after solr has been updated to a new version.
The search term in the test has been adapted and it returns the right search result now.
[x] No
[AB#73925](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/73925)
> test: adapt search e2e test to the slightly changed solr search behavior

- src/app/core/services/order/order.service.spec.ts
- src/app/core/services/order/order.service.ts
- src/app/core/services/payment/payment.service.spec.ts
- src/app/core/services/payment/payment.service.ts
<br /><br />## PR Type<br /><br /><br /><br />[x] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Currently, when using a multisite configuration, the payment redirect link will not contain the baseHref and often return to a wrongly configured PWA.<br /><br />Issue Number: Closes #912<br /><br />## What Is the New Behavior?<br />Now, the baseHref is respected and the payments will redirect to a correct PWA.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br …
> fix: payment redirect respects baseHref

- .eslintrc.json
[x] Bugfix
A change from 9b595d1812690ef0d00e96ec3022c6301f58533a was lost in the tslint to eslint migration
Included again
[ ] Yes
[x] No
[AB#74359](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74359)
> fix: include all theme in allowed overrides

- .eslintrc.json
- eslint-rules/src/index.ts
- eslint-rules/src/rules/require-formly-code-documentation.ts
- eslint-rules/tests/require-formly-code-documentation.spec.ts
- src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.ts
- src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.ts
- src/app/pages/registration/formly/disable-prefilled.extension.ts
- src/app/pages/registration/formly/registration-address-field/registration-address-field.component.ts
- src/app/pages/registration/formly/registration-heading-field/registration-heading-field.component.ts
- src/app/pages/registration/formly/registration-tac-field/registration-tac-field.component.ts
- src/app/shared/formly/dev/testing/formly-testing-example/formly-testing-example.component.ts
- src/app/shared/formly/dev/testing/formly-testing-fieldgroup-example/formly-testing-fieldgroup-example.component.ts
- src/app/shared/formly/dev/testing/formly-testing.module.ts
- src/app/shared/formly/types/plain-text-field/plain-text-field.component.ts
- src/app/shared/formly/types/text-input-field/text-input-field.component.ts
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[x] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Currently, no one is checking whether your formly artifacts are documented.<br /><br />Issue Number: Closes #<br /><br />## What Is the New Behavior?<br /><br />Now, an eslint rule enforces (hopefully explanatory) comments before formly artifacts.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br /> …
> ci: add require formly documentation rule

- .dockerignore
- .github/workflows/development.yml
- .gitignore
- package.json
- scripts/eslint-hard.js
- scripts/update-dockerignore.js
`scripts/lint-hard` only modifies the root ESLint config and linting has to be performed afterwards. The script is not runnable for single files.
- Script modifies all eslint configs
- Automatic restore after run or interrupt
- Script can run on single files
[ ] Yes
[x] No
[AB#74496](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74496)
> chore: lint-hard with auto restore of configs

- src/app/core/store/shopping/product-listing/product-listing.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
… state is stored
[ x ] Bugfix
[ ] Feature
[ ] Other: 
Once a product search is successfully done the result is added to the State Management. In a later search for the same search term the result is taken from the State Management (this is okay for fast result rendering) but no REST request is triggered to update this result information. This should be done for search results.
Issue Number: Closes #983 
Every product search triggers a REST call that fetches and updates any search result information the State Management might already have.
[ ] Yes
[ x ] No …
> Product Search is cached in PWA and does not trigger a new REST call

- src/app/core/directives/product-context.directive.ts
[x] Bugfix
If a child product context is created in the template, and afterwards removed, the parent context does not get the removal update.
Removals are propagated on destroy.
[ ] Yes
[x] No
[AB#74466](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74466)
> fix: update propagation of parent context if child context is removed

- .github/workflows/dead-code.yml
- .github/workflows/development.yml
- .github/workflows/docs.yml
- .github/workflows/windows.yml
- docs/concepts/localization.md
- docs/guides/migrations.md
- package.json
- projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
- projects/organization-management/src/app/pages/cost-center-buyers/cost-center-buyers-page.component.html
- projects/requisition-management/src/app/store/requisitions/requisitions.effects.ts
- scripts/clean-up-localizations.js
- src/app/pages/registration/registration-page.component.ts
- src/app/shared/components/login/login-modal/login-modal.component.html
- src/app/shared/forms/utils/forms.service.ts
- src/app/shell/header/language-switch/language-switch.component.html
Localization keep patterns are managed in the cleanup script.
Localization keep patterns are managed where they are defined. (with an annotation)
[ ] Yes
[x] No
Hi @SGrueber @suschneider @MaxKless 😃 
I think the `.error.` keep pattern in the `scripts/clean-up-localizations.js` is outdated. I see that all of the error feedback regarding payments comes from the API, there should be no need to keep those translation keys in the PWA (also because we now fetch specific keys directly from the ICM). Regarding anything not payment related? I'm not sure...
Please check if my assumption is correct.
In projects every uselessly translated localization is money 🤑 
[AB#72086](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/ …
> refactor: move localization keep patterns where they are needed

- src/app/pages/product/product-detail-info/product-detail-info.component.html
[ x ] Bugfix  
HTML content for long description on product detail page is not rendered.
Long description is displayed correctly.
[ ] Yes  
[ X ] No
[AB#74768](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74768)
> fix: render content of product detail description tab as html

- src/app/shell/header/header-navigation/header-navigation.component.html
- src/app/shell/header/header-navigation/header-navigation.component.spec.ts
[x] Feature
With ICM 7.10.38-LTS demo content artifact for header navigation is provided to manage CMS content but this is not used in the PWA.
The PWA uses this artifact and can present demo content for header navigation provided in ICM.
[ ] Yes
[x ] No
ICM release 7.10.38-LTS is necessary.
[AB#74771](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74771)
> feat: use demo content artifact in header navigation

- src/app/core/models/line-item/line-item.interface.ts
- src/app/core/models/line-item/line-item.mapper.ts
- src/app/core/models/line-item/line-item.model.ts
- src/app/extensions/quoting/exports/quoting-exports.module.ts
- src/app/extensions/quoting/facades/quoting.facade.ts
- src/app/extensions/quoting/quoting.module.ts
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.html
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.spec.ts
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.ts
- src/app/extensions/quoting/store/quoting/quoting.actions.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.ts
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/pages/basket/shopping-basket/shopping-basket.component.ts
- src/assets/i18n/en_US.json
[ ] Bugfix
[ x] Feature
[ ] Other: 
Closes #948 
Quote products cannot be removed from the cart once they have been added to it.
Quote products can now be removed from the cart.
[ ] Yes
[ x] No
[ ] Unit tests
[ ] Add localization key 'quote.basket_items.label' for all languages (now is only for US)
> feat: Remove quote requests from cart

- src/app/core/facades/checkout.facade.ts
- src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.ts
- src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.html
- src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.spec.ts
- src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.ts
- src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.html
- src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user enters the checkout shipping page errors are thrown in the browser console.
There are no errors in the browser console any more.
[ ] Yes
[x] No
[AB#74842](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74842)
> fix: prevent console error messages on checkout shipping page

- src/app/pages/basket/shopping-basket/shopping-basket.component.spec.ts
- src/setupJest.ts
It looks like template errors are no longer reported as `Error`s since the last upgrade and so they don't fail the test anymore.
Fail on every test error message.
[ ] Yes
[x] No
[AB#74936](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74936)
> test: fail on console error

- .eslintignore
- .github/workflows/development.yml
- e2e/test-schematics-customization.sh
- e2e/test-schematics-normal.sh
- package.json
- schematics/src/helpers/add-destroy/factory.ts
- schematics/src/lazy-component/factory.ts
- schematics/src/utils/filesystem.ts
- schematics/src/utils/lint-fix.ts
- Since tslint->eslint migration, all lazy components are excempt from linting. (Also the not generated ones)
- Linting after schematics is not fast
- Exit hook for schematics that applies linting only once using command line.
- Activate linting for all files again.
- Cleanup and optimize schematics test scripts for git bash (no `wget`, verbose output from `stat`)
- Removed one test for `customized-copy` on lazy component, because it wasn't working and `customized-copy` is deprecated.
[ ] Yes
[x] No
[AB#74941](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74941)
> perf(schematics): better linter performance

- docs/guides/migrations.md
- src/app/core/facades/shopping.facade.ts
- src/app/core/identity-provider/icm.identity-provider.ts
- src/app/core/services/categories/categories.service.spec.ts
- src/app/core/services/categories/categories.service.ts
- src/app/core/services/filter/filter.service.spec.ts
- src/app/core/services/filter/filter.service.ts
- src/app/core/services/products/products.service.spec.ts
- src/app/core/services/products/products.service.ts
- src/app/core/store/customer/customer-store.spec.ts
- src/app/core/store/customer/user/user.actions.ts
- src/app/core/store/customer/user/user.effects.spec.ts
- src/app/core/store/customer/user/user.effects.ts
- src/app/core/store/customer/user/user.reducer.ts
- src/app/core/store/shopping/categories/categories.effects.spec.ts
- src/app/core/store/shopping/categories/categories.effects.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/promotions/promotions.effects.spec.ts
- src/app/core/store/shopping/promotions/promotions.effects.ts
- src/app/core/store/shopping/search/search.effects.spec.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/store/shopping/shopping-store.module.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/app/core/utils/api-token/api-token.service.ts
- src/app/core/utils/meta-reducers.spec.ts
- src/app/core/utils/meta-reducers.ts
- src/app/core/utils/operators.ts
[x] Feature
Category and product REST calls are sent without pgid (unpersonalized). Category views, personalized product prices or promotions defined in the ICM back office are not respected in the storefront.
Issue Number: Closes #315
Category and product data are personalized.
[x] Yes
[AB#74465](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74465)
> feat: fetch and display personalized category and product data

- Dockerfile
- nginx/templates/multi-channel.conf.tmpl
- scripts/build-pwa.js
- server.ts
- src/ssr/server-scripts/server.js
[x] Bugfix
Service Worker functionality is broken since v1.0.
1. Modify `docker-compose.yml` (SW need a full deploy as part is handled in nginx and PWA SSR)
- enable SW by setting `serviceWorker: 'true'` on the SSR image
- comment out `MULTI_CHANNEL` of the nginx (SW never worked with multi-site using context paths)
2. Start up with `docker compose up --build`
3. Go to `http://localhost:4200/home` and give the SW time to boot up (check dev tools)
4. Go to `http://localhost:4200/ngsw/state`
- Expected: everything should be fine: `Driver state: NORMAL`
- Actual: SW is `Degraded due to: Failed to retrieve hashed resource from the server.`
5. stop the `docker compose` and refresh page in browser
- Expected: Page should still work because SW has installed correctly
- …
> fix: repair service worker

- e2e/cypress-ci-e2e.js
- e2e/cypress/integration/framework/index.ts
- e2e/cypress/integration/pages/checkout/cart.page.ts
- e2e/cypress/integration/pages/meta-data.module.ts
- e2e/cypress/integration/specs/quoting/quote-handling-anonymous-basket-to-quote-request.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/system/seo-home-page.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/system/seo-product-detail-page.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/system/seo-search-page.b2c.e2e-spec.ts
- src/app/core/services/filter/filter.service.spec.ts
- src/app/core/services/products/products.service.ts
Some e2e tests unstable.
[ ] Yes
[x] No
[AB#75134](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75134)
> chore: cypress test stabilization

- src/app/core/utils/dev/operators.spec.ts
- src/app/core/utils/dev/operators.ts
[x] Feature
Dynamic values cannot be printed as a message in the `log` operator, when they change during the stream lifetime.
The `log` operator supports a function argument for message.
[ ] Yes
[x] No
[AB#75187](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75187)
> chore: enable function argument to log operator

- templates/webpack/webpack.custom.ts
[x] Bugfix
When using theme specific component overrides, the angular cache gets confused.
- `ng g override src/app/pages/home/home-page.component.ts --ts --html --theme b2b --defaults`
- add `test$ = of('test');` to `src/app/pages/home/home-page.component.b2b.ts`
- add `<pre>{{ test$ | async | json }}</pre>` to `src/app/pages/home/home-page.component.b2b.html`
- Do `ng serve` and once up stop it
- Do `ng serve --configuration="b2c,development"`
Expected: no error
Actual:
```
Error: src/app/pages/home/home-page.component.html:1:9 - error TS2339: Property 'test$' does not exist on type 'HomePageComponent'.
1 <pre>{{ test$ | async | json }}</pre>
~~~~~
src/app/pages/home/home-page.component.ts:5:16
5   templateUrl: './home-page.component.html', …
```
> build: dedicated directory for angular cache per theme

- .dockerignore
- .eslintignore
- .eslintrc.json
- angular.json
- docs/check-dead-links.js
- docs/check-sentence-newline.js
- e2e/.gitignore
- e2e/cypress/tsconfig.json
- intershop-changelog.js
- package.json
- schematics/customization/service-worker/index.js
- schematics/scripts/generate-schema-defs.js
- scripts/check-file-synchronization.js
- scripts/clean-up-localizations.js
- scripts/convert-to-xliff.js
- scripts/update-dockerignore.js
- scripts/upgrade-pwa.js
- src/jest-serializer/AngularHTMLSerializer.js
- src/jest-serializer/CategoryTreeSerializer.js
- templates/review-server/review-proxy.js
- templates/webpack/data-testing-id-loader.js
ESLint not running on JS files.
ESLint running on JS files.
[ ] Yes
[x] No
[AB#74955](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74955)
> chore: activate eslint for js files

- .github/workflows/windows.yml
Windows job runs `npm run check` which takes a lot of time on the GitHub shared runners.
- Run a simplified version with Local task and run Check only on develop builds.
- Run the simplified workflow for `cmd`, `powershell` and Git Bash
[ ] Yes
[x] No
[AB#75150](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75150)
> build: simplify win check for PR build

- .eslintrc.json
- eslint-rules/src/index.ts
- eslint-rules/src/rules/do-not-use-theme-identifier.ts
- eslint-rules/src/rules/use-correct-component-overrides.ts
- eslint-rules/tests/do-not-use-theme-identifier.spec.ts
- eslint-rules/tests/use-correct-component-overrides.spec.ts
[x] Feature
[x] Other: Best Practice
When using the Intershop PWA with multiple themes, some best practices should be honored:
- the `THEME` variable should not be used in components, instead component file overrides should be used
- properties `templateUrl` and `styleUrls` should always point to the base file, so the override mechanism can step in at build time.
Lint rules added.
[ ] Yes
[x] No
[AB#75105](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75105)
> feat(eslint): rules for customization

- .eslintrc.json
- eslint-rules/src/rules/sort-testbed-metadata-arrays.ts
- intershop-changelog.js
- scripts/eslint-hard.js
- src/app/core/interceptors/payment-payone.interceptor.ts
- src/app/core/services/products/products.service.spec.ts
- src/app/core/store/shopping/product-prices/product-prices.reducer.ts
- src/jest-serializer/NgrxActionArraySerializer.js
- src/jest-serializer/NgrxActionSerializer.js
- templates/review-server/review-proxy.js
ESLint rules [arrow-body-style](https://eslint.org/docs/rules/arrow-body-style) and [prefer-arrow-callback](https://eslint.org/docs/rules/prefer-arrow-callback) are activated again like they were for TSLint with similar rules: https://github.com/intershop/intershop-pwa/blob/892a1ef31a4442a0bda2a17ac889eaca8ed5e5c4/tslint.json#L26-L27
[ ] Yes
[x] No
[AB#75394](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75394)
> chore: activate eslint rules arrow-body-style and prefer-arrow-callback

- .eslintrc.json
- eslint-rules/src/index.ts
- eslint-rules/src/rules/meaningful-describe-in-tests.ts
- eslint-rules/tests/meaningful-describe-in-tests.spec.ts
- src/app/core/store/shopping/product-prices/product-prices.effects.spec.ts
- src/app/core/store/shopping/product-prices/product-prices.selectors.spec.ts
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.spec.ts
- src/app/extensions/recently/store/recently/recently.integration.spec.ts
- src/app/extensions/store-locator/store/store-locator-config/store-locator-config.selectors.spec.ts
[x] Feature
Top-level describes in tests are no longer corrected after the TSLint-> ESLint migration. This can lead to confusing test outputs if a new test has an wrong name due to refactoring or copy&paste.
New rule to assert the old behavior.
[ ] Yes
[x] No
[AB#75398](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75398)
> chore: add rule for meaningful top-level describes in tests

- .eslintrc.json
- package.json
- scripts/cleanup-testbed.mjs
[x] Bugfix
When `cleanup-testbed` is run in CI, it will try to execute against eslint rules specs, but ignores the file in the individual run:
```
> node scripts/cleanup-testbed.mjs "origin/develop"
found 6 test files
did not find any test files <-- that one is a eslint test
at src/app/core/store/shopping/product-prices/product-prices.effects.spec.ts 3 tests
...
```
Execution for folders and multiple files on powershell does not work
- Minimatch is used to filter out potential files from git diff checks.
- ordered-imports check and pre-commit check for `.mjs` files.
- normalizing paths to work with windows cmd and powershell
[ ] Yes
[x] No
[AB#75414](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75414)
> chore: minor cleanup testbed improvements

- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/facades/shopping.facade.ts
- src/app/core/models/price-item/price-item.helper.ts
- src/app/core/models/price/price.model.ts
- src/app/core/models/product-view/product-view.model.spec.ts
- src/app/core/models/product-view/product-view.model.ts
- src/app/core/routing/product/product.route.spec.ts
- src/app/core/store/shopping/products/products.selectors.spec.ts
- src/app/core/store/shopping/products/products.selectors.ts
- src/app/pages/compare/product-compare-list/product-compare-list.component.spec.ts
- src/app/pages/product/product-detail-actions/product-detail-actions.component.spec.ts
- src/app/pages/product/product-page.component.spec.ts
- src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.html
- src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.spec.ts
- src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.ts
- src/app/shared/components/product/product-price/product-price.component.spec.ts
- src/app/shared/components/product/product-price/product-price.component.ts
With #1018, the `ProductView` model was extended with pricing information even though it is only really used on the `product-price.component`.
Keeping additional properties in the `ProductView` means it is firing (at least) once more for every property.
In the past, more properties were disconnected from the model, like `links` in 5e0e4c8559b98c1d277170b0e8fabb6b2e58dc9f or `parts` in f5b49e0763cf5625d7f1f6027b3865c5e896e57a, finished by a memoization overhaul in #528.
- disconnected pricing from product views
- added pricing to product context
[ ] Yes
[x] No
[AB#75549](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75549)
> refactor: disconnect pricing from product view model

- src/app/extensions/order-templates/facades/order-templates.facade.ts
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-line-item/account-order-template-detail-line-item.component.html
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-line-item/account-order-template-detail-line-item.component.spec.ts
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-line-item/account-order-template-detail-line-item.component.ts
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.html
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.spec.ts
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.ts
- src/app/extensions/order-templates/store/order-template/order-template.selectors.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Feature
Issue Number: Closes #1052
Display warning and disable checkbox when product is out of stock on an order template.
[ ] Yes
[x] No
**1 item** in your order template **is** out of stock. **This item** cannot be added to the shopping cart.
**2 items** in your order template **are** out of stock. **These items** cannot be added to the shopping cart.
[AB#75189](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75189)
> feat: display feedback when product is out of stock on order templates

- src/app/core/identity-provider.module.ts
Production code uses import from `ng-mocks`
Use correct import
[ ] Yes
[x] No
[AB#75596](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75596)
> chore: fix import in identity-provider module

- src/app/core/utils/routing.ts
[x] Bugfix
`=` char in URL (even though it is escaped) causes problems in deployment.
1. put `=` into product name in ICM (no demo data for this available)
2. start full deployment (docker compose)
3. navigate to product and refresh
`=` char is replaced as part of the `reservedCharactersRegEx` used in generating slugs for category and product URLs.
[ ] Yes
[x] No
[AB#75910](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75910)
> fix: remove equal character from url slugs

- projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.spec.ts
- projects/requisition-management/src/app/models/requisition/requisition.mapper.spec.ts
- projects/requisition-management/src/app/models/requisition/requisition.model.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.spec.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-cost-center-approval/requisition-cost-center-approval.component.spec.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-cost-center-approval/requisition-cost-center-approval.component.ts
- projects/requisition-management/src/app/store/requisitions/requisitions.selectors.spec.ts
- src/app/core/models/basket/basket.interface.ts
- src/app/core/models/basket/basket.mapper.ts
- src/app/core/models/basket/basket.model.ts
- src/app/core/models/order/order.interface.ts
- src/app/core/models/order/order.mapper.ts
- src/app/shared/components/basket/basket-buyer/basket-buyer.component.html
- src/app/shared/components/basket/basket-buyer/basket-buyer.component.spec.ts
- src/app/shared/components/basket/basket-buyer/basket-buyer.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
When buyer information (company name, tax ID, buyer name or e-mail address) are updated via profile settings, past orders are also changed.
For past orders, the information is displayed which is valid at the time of placing the order.
[ ] Yes
[x] No
see also:
[AB#69203](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69203)
[AB#75719](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75719)
> fix: display buyer information for orders

- src/app/core/utils/api-token/api-token.service.ts
[x] Bugfix
If a logged in user opens an another tab, then the related api token cookie is removed temporary, which could lead to an automatic logout in the other tabs. The reason is, that the PWA gets new api tokens before the login process is completed.
Issue Number: Closes #938
If the logged in user gets new user api tokens before the log in process is completed, then the existing cookie should be overwritten with the new api token.
[x] No
[AB#75862](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75862)
> fix: second login in another tab gets lost

- src/app/core/store/customer/basket/basket.effects.ts
[x] Bugfix
E2E tests
```
e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
e2e/cypress/integration/specs/quoting/quote-handling-anonymous-basket-to-quote-request.b2b.e2e-spec.ts
```
are flaky and the reason could be the current merge basket logic.
Reimplemented tracking of anonymous baskets.
[ ] Yes
[x] No
[AB#76054](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76054)
> fix: reimplement tracking of anonymous basket for merge basket logic

- .github/workflows/mark-conflicts.yml
[x] Feature
GitHub has no automated way of searching for PRs with conflicts. As a contributor with a lot of open PRs it is hard to know which ones need an update.
Added action that [marks PRs with conflicts](https://github.com/intershop/intershop-pwa/pulls?q=is%3Aopen+is%3Apr+label%3A%22has+conflicts%22).
[ ] Yes
[x] No
[AB#76056](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76056)
> chore: add pipeline for marking PRs with conflicts

- schematics/src/page/factory.ts
- schematics/src/page/factory_spec.ts
- src/app/extensions/recently/pages/recently-routing.module.ts
- src/app/extensions/store-locator/pages/store-locator-routing.module.ts
- src/app/extensions/tacton/pages/tacton-routing.module.ts
[x] Bugfix
Some extension pages are missing feature toggle guards, which will make the pages available even if the feature is not activated.
- added guards
- modified schematic to add guards when generating new pages in extensions
[ ] Yes
[x] No
[AB#76049](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76049)
> fix: add missing feature guards to feature routing modules

- nginx/Dockerfile
[ ] Bugfix
[ ] Feature
[X] Build-related changes
[ ] Other: 
NGinx build is broken due to new gcc compiler being available in `ubuntu:jammy` image
Steps to reproduce the behavior:
1. Instead of `ubuntu:latest` use `ubuntu:jammy` in `nginx/Dockerfile`
2. Run `docker build nginx --no-cache -t intershoppwa-nginx:latest`
Issue Number: Closes #1136 
NGinx build is not broken and finishes successfully.
[AB#76155](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76155)
> chore: pin usage of ubuntu focal

- schematics/src/lazy-component/factory.ts
- schematics/src/lazy-component/factory_spec.ts
- schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
- Type updates in components which have the `@GenerateLazyComponent` decorator require a run of `npm run synchronize-lazy-components` to be reflected in the generated lazy components, because the initialization is copied.
- Generated lazy components contain eslint ignores, because the typing is not properly generated
- refactored lazy-component schematic to import the type of the original component and use it to delegate the typing of inputs
- improved readability of schematics template
[ ] Yes
[x] No
It is important that the original component is imported twice in the generated lazy component:
- the typing is imported with `import type` and therefor exists only in Typescript
- the lazy import with `await import` is used for webpack …
> refactor: delegate types in lazy-component schematic

- schematics/src/lazy-component/factory.ts
- schematics/src/lazy-component/factory_spec.ts
- schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
- src/app/core/utils/feature-toggle/feature-toggle.service.ts
[x] Bugfix
Lazy components use [`FeatureToggleService.enabled`](https://github.com/intershop/intershop-pwa/blob/4c8b891fa62b088e12127a0da9bcbe1a03fdd29e/src/app/core/utils/feature-toggle/feature-toggle.service.ts#L32) which does not work for lazy components on page load.
Lazy components use subscriptions to [`FeatureToggleService.enabled$`](https://github.com/intershop/intershop-pwa/blob/4c8b891fa62b088e12127a0da9bcbe1a03fdd29e/src/app/core/utils/feature-toggle/feature-toggle.service.ts#L40)
[ ] Yes
[x] No
wait for integration of #1122
> fix: use feature subscription instead of static check in lazy components

- docs/concepts/localization.md
- scripts/clean-up-localizations.js
- templates/webpack/webpack.custom.ts
[x] Feature
In projects not all out-of-box features of the PWA are used and when using component overrides, translation keys can become unused. It should be possible to run the `clean-localizations` script so it excludes keys that are in dead code considering the project customization.
`npm run clean-localizations --build` performs a build and can hereby filter out unused translation keys.
For testing (component overrides):
- add a component override `ng g override src/app/pages/search/search-result/search-result.component.ts --theme all --html --defaults`
- run `npm run clean-localizations --build`
- `Localization key search.title.text removed because it is not used` 🎉 
For testing (excluding a feature):
- remove `QuickorderRoutingModule` from `app.module.ts` (removes page routing)
- …
> feat: clean-localizations on used sources

- src/app/core/configurations/injection-keys.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/facades/shopping.facade.ts
- src/app/core/models/price/price.model.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/environments/environment.model.ts
[x] Feature
Prices are fetched whenever the `LoadProductSuccess` action is encountered. This happens also if the actual price is not being displayed.
- only fetch prices that are displayed (via context displayProperties)
- introduced two update strategies:
- *stable*: fetch prices only once per application lifetime
- *always*: re-fetch prices every time they are displayed
- when going to Product detail pages, the prices are updated if the product data is also updated (when completeness level `true` is chosen in `SelectedProductContextFacade`)
[ ] Yes
[x] No
> feat: introduce price update strategies

- src/app/core/store/core/configuration/configuration.selectors.spec.ts
- src/app/core/store/core/configuration/configuration.selectors.ts
- src/environments/environment.model.ts
[x] Feature
At the moment there is no easy way of configuring the PWA for a specific locale in `environment.development.ts`.
The default locale has to be either
- changed in the ICM
- be applied by navigating to the PWA with `;lang=...` (which does not work with SSO redirects)
- set in a full docker compose config
The already existing property `defaultLocale` can be set in `environment.development.ts` and it takes precedence in development mode.
[ ] Yes
[x] No
[AB#76387](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76387)
> fix: enable locale override for development mode

- schematics/src/helpers/override/factory.ts
- schematics/src/helpers/override/factory_spec.ts
Currently, the override schematic only accepts paths with forward slashes.
Now, it also accepts paths with backslashes.
[AB#76433](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76433)
> fix(schematics): make override schematic robust to path seperators

- src/app/pages/cookies/cookies-page.guard.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
In a ssr+nginx setup the route: /cookies will show the error page of the nginx. The ssr container have the following log: 
The cookie page guard should manage to open and close a modal to select the desired cookies. It should be clear, that modals are only available on browser and not on server side. (https://github.com/angular-slider/ngx-slider/issues/66)
The cookie page guard manages the cookie modal only on browser side.
[ ] Yes
[x] No
Reproduce: Go to demo page: …
> fix: cookie page guard should only use NgModal on browser

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/settings.json
- docs/concepts/cms-integration.md
The Angular Schematics extension does not support the "schematics" option anymore, probably due to monetization. 
I removed it until an alternative is found.
[AB#76390](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76390)
> chore: remove useless schematics vscode extension

- src/setupJest.ts
The workaround that was required to get jest running (described here https://github.com/telerik/kendo-angular/issues/1505#issuecomment-385882188) was apparently fixed in the JSDOM implementation.
All tests work without this manual mock now, so I have removed it.
[AB#76563](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76563)
> chore: remove unnecessary jest mock

- src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.html
- src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.spec.ts
- src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Currently, when you navigate to the basket page and the user has only one cost center, the cost center is nevertheless reassigned and because of this, the basket is reloaded. This leads to certain error/information messages dissapearing.
Now, the cost center is only reassigned when it actually differs from the one already set in the basket.
[ ] Yes
[x] No
[AB#76467](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76467)
> fix: only update cost center when it actually changes

- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/pages/checkout/checkout-page.guard.ts
- src/app/pages/checkout/checkout-page.module.ts
[ ] Bugfix
[ ] Feature
[X ] Refactoring (no functional changes, no API changes)
[ ] Other: 
Currently you can navigate to the checkout with a non-existent shopping cart via the address bar of the browser
Now the route is protected by a guard. Navigate to /checkout or any related childRoute without an existing basket will redirect you to the root url
[ ] Yes
[X ] No
> refactor: access to checkoutpages handled by guard

- src/app/pages/product/product-links-carousel/product-links-carousel.component.html
- src/app/pages/product/product-links-carousel/product-links-carousel.component.spec.ts
- src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
[x] Bugfix
If the property `displayOnlyAvailableProducts` is activated on `ish-product-links-carousel`, the component fetches all linked products to calculate the carousel content. This leads to a drop in page performance, especially in SSR if products have many linked accessories.
The product links are evaluated lazy slide by slide whenever the user switches to them. For SSR only the first slide is evaluated.
[ ] Yes
[x] No
[AB#76738](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76738)
> fix: lazy check for available product links

- jest.config.haste-map.js
- jest.config.js
[x] Other: Local Test Performance
Jest calculates dependencies over the whole source base. This can be time-consuming when running pre-commits with `--findRelatedTests`:
```
~$ npx jest --findRelatedTests --listTests src/app/shared/components/product/product-item/product-item.component.ts | wc -l
56
```
A custom haste map implementation breaks dependency crawling on some borders (facades, modules, ...) for a reduced test set:
```
~$ npx jest --findRelatedTests --listTests src/app/shared/components/product/product-item/product-item.component.ts | wc -l
6
```
Full runs on CI and `npm run check` don't use this and remain unaffected.
[ ] Yes
[x] No
[AB#76043](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76043)
> perf(test): local jest speedup

- .github/workflows/development.yml
- scripts/cleanup-testbed.mjs
[x] Bugfix
`cleanup-testbed` script does not run on related tests when checking PRs. That way certain removals only will be detected on `develop` when a full run is performed.
`cleanup-testbed` has a new `--related` argument that uses [jest `--findRelatedTests`](https://jestjs.io/docs/cli#--findrelatedtests-spaceseparatedlistofsourcefiles) under the hood.
[ ] Yes
[x] No
[AB#76042](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76042)
> fix: use jest test related for cleanup-testbed

- src/app/core/routing/pwa-url.serializer.spec.ts
- src/app/core/routing/pwa-url.serializer.ts
[x] Bugfix
The matrix param removal in [`PWAUrlSerializer`](https://github.com/intershop/intershop-pwa/blob/f7e0de7a9b68351f15a7d272b535e4034a29e2fa/src/app/core/routing/pwa-url.serializer.ts#L23-L24) is too greedy and also reacts on semicolons in query parameters.
In our case semicolons in query parameters are added in the SSO login state by the library `angular-oauth2-oidc` when logging in with a `returnUrl`.
Matrix param removal is not implemented by string manipulation using a regex, but instead by creating a `UrlTree` copy free of matrix parameters that is then serialized.
[ ] Yes
[x] No
[AB#76838](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76838)
> fix: preserve semicolons in query params

- src/app/extensions/tracking/store/tracking-config/tracking-config.effects.ts
If the tracking extension is enabled **AND for some reason the cookies consent check is removed (project customization to use a different cookies consent management tool)**, then the tracking-config.effect.ts will use the window object on server side if a gtmToken is found.
Making sure that the window object is only used on browser side independent from the potentially removed cookies consent handling.
[x] No
[AB#77211](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77211)
> fix: window object should only be used on browser side

- .cz-config.js
According to our docs, we follow conventional commits (which in turn follows the angular conventions).
Both allow a `ci` type for commit messages, but we don't.
Added a `ci` type.
[AB#77327](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77327)
> chore: add ci option to commitizen config

- .github/workflows/demo-server-down.yml
Demo server down action was broken for `workflow_dispatch`. Works again
[AB#77632](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77632)
> ci: fix demo server down

- src/app/core/store/content/pages/pages.effects.spec.ts
- src/app/core/store/content/pages/pages.effects.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
When an authenticated user reloads a content page, then the "Page Not Found" component is rendered. The reason for this is, that the needed personalization call is dispatched after the content page call, which should use the pgid.
The content page call is dispatched only after the personalization status is determined.
[ ] Yes
[ x ] No
[AB#77774](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77774)
> fix: content page not found when reloading a page with an authenticated user

- e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/checkout/register-before-checkout.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/checkout/shopping-anonymous.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/checkout/shopping-prices.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/checkout/shopping-user.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/shopping/browse-products-from-indexed-page.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/shopping/browse-products-homepage-to-product-detail.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/shopping/search-category-routing.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/system/change-language-family-page.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/system/change-language-product-detail.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/system/change-language-search-result.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/system/retain-basket-anonymous.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/system/retain-basket-authenticated.b2c.e2e-spec.ts
Pricehandling was changed in the inSPIRED demo data from 'Net' to 'Gross' this resulted in failing e2e tests in B2C since other prices are displayed now. Adapted the prices to the new returned data.
[AB#78071](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78071)
> test: adapt prices for e2e testing in B2C with the usage of ICM 7.10.38.11-LTS

- angular.json
- nginx/templates/multi-channel.conf.tmpl
- server.ts
- templates/webpack/webpack.custom.ts
[x] Bugfix
Issue Number: Closes #1194
`favicon.ico` is accessible from website root.
If used with context path multi-site, only the default brand favicon can be chosen. If used with domain multi-site, the correct favicon is chosen automatically.
[ ] Yes
[x] No
[AB#77775](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77775)
> fix: make default favicon accessible from root

- src/styles/pages/category/filter-panel.scss
- src/styles/pages/category/product-list.scss
* removed unused express-shop styles in addition
[x] Bugfix
`filter-layer` CSS styles were remove "optimized" by purgecss.
Issue Number: Closes #1204
`filter-layer` CSS styles are now kept by the purgecss optimization.
[x] No
[AB#78108](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78108)
> fix: purgecss exeption for generated filter-layer CSS classes (#1204)

- docs/concepts/sso.md
- src/app/core/guards/identity-provider-password.guard.ts
- src/app/core/identity-provider.module.ts
- src/app/core/identity-provider/identity-provider.factory.ts
- src/app/pages/forgot-password/forgot-password-page.module.ts
[ X ] Bugfix
[ ] Feature
[ ] Other: 
When `/invite` route is being rendered in SSR context, the identity provider instance is missing a function object leading to errors later on.
When `forgotPasword/updatePassword` route is being rendered in SSR context, the system shows the Change Password page no matter what identity provider type is configured.
Issue Number: Closes #933
See documentation [sso.md](https://github.com/intershop/intershop-pwa/blob/fix/invite-page-in-ssr/docs/concepts/sso.md)
[ ] Yes
[ X ] No …
> fix: Invite page in ssr is not working

- docs/guides/multi-site-configurations.md
- nginx/templates/multi-channel.conf.tmpl
- src/app/core/configurations/configuration.meta.ts
- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/store/core/configuration/configuration.selectors.spec.ts
- src/app/core/store/core/configuration/configuration.selectors.ts
[x] Feature
Using multi-site deployments, if you have a default feature list in the brand-specific environment.ts file, and on certain channels - but not all - you want to go live with another feature, it is currently required to repeat the whole feature list for all of those channels.
New property `addFeatures` in multi-site config, that allows adding additional features that extend the feature list for the specific channel.
[ ] Yes
[x] No
[AB#77608](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77608)
> feat: additional features extending defaults in multi-site

- .github/workflows/automated-upgrade.yml
- .github/workflows/dead-code.yml
- .github/workflows/development.yml
- .github/workflows/docs.yml
- .github/workflows/integration.yml
- .github/workflows/updates.yml
- .github/workflows/windows.yml
- CHANGELOG.md
- docs/guides/migrations.md
* fixed to node.js 16.16.0 including npm 8.11.0
docker and git actions use latest node.js 16 version that led to unexpected behavior
fixed node.js version does not introduce unexpected behavior/issues
[x] No
[AB#78109](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78109)
> deps: use a fixed node.js version to prevent build issues with unknown versions

- docker-compose.yml
- package-lock.json
- package.json
- src/app/core/store/core/configuration/configuration.actions.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/utils/functions.spec.ts
- src/app/core/utils/functions.ts
- src/app/core/utils/state-transfer/state-properties.service.spec.ts
- src/app/core/utils/state-transfer/state-properties.service.ts
- src/app/extensions/tacton/store/tacton-config/tacton-config.effects.ts
[x] Feature
Complex configurations for `IDENTITY_PROVIDER` or `TACTON` have to be supplied as JSON to the deployments:
```
IDENTITY_PROVIDERS: |
{ "Auth0": { "type": "auth0", "domain": "dev-asdf1234.eu.auth0.com", "clientID": "012ea8f1db7a838b65a8b29e8464742166877abb" } }
```
When trying to structure the data, it becomes very verbose and even then JSON parsing is very sensitive to commas and quotes and therefore prone to error:
```
IDENTITY_PROVIDERS: |
{ 
"Auth0": { 
"type": "auth0",
"domain": "dev-asdf1234.eu.auth0.com",
"clientID": "012ea8f1db7a838b65a8b29e8464742166877abb"
}
}
```
Complex configuration can be supplied as YAML:
```
IDENTITY_PROVIDERS: |
Auth0:
type: auth0
domain: dev-asdf1234.eu.auth0.com
clientID: 012ea8f1db7a838b65a8b29e8464742166877abb
```
[ ] Yes
[x] No
Depends on …
> feat: complex configuration can be supplied as yaml

- scripts/dead-files.js
- templates/webpack/webpack.custom.ts
[x] Feature
When building, the `active-files.json` report does not include the active style files (global and component).
`active-files.json` includes active global and component styles.
[ ] Yes
[x] No
[AB#77589](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77589)
> feat: active files report includes style files

- src/app/core/facades/product-context.facade.ts
- src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.spec.ts
- src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
[x] Bugfix
"Add to Cart" buttons on retail sets are active when quantity is 0.
- Navigate to a retail set (i.e. https://intershoppwa.azurewebsites.net/PCs/Fujitsu-ESPRIMO-Edition-skuM8540840-catComputers.1835.153)
- set an individual quantity of a retail set part to 0
Expected: Add to cart should not be possible
Actual: Add to cart button is enabled, clicking it will lead to an endless loading animation
- set all quantities to 0
Expected: All add to cart buttons should be disabled
Actual: Add to cart button is enabled, clicking it will lead to an endless loading animation
- disable add to cart for quantity below 1
- track quantity of children in parent context to enable the same behavior
[ ] Yes
[x] No
WAIT: Fix is based on #1063, please review and merge before this …
> fix: disable add-to-basket when quantity is zero

- src/app/pages/checkout/checkout-page.module.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user pays with a redirect after checkout payment method (e.g. online pay) he is routed to an empty basket page after returning from the redirect of the external payment provider.
He is routed to the order confirmation page after returns from redirect after checkout.
[ ] Yes
[x] No
This issue occurred because the checkout guard expects a basket, but it doesn't exist after order creation. The guard has been removed from checkout receipt page. …
> fix: display confirmation page returning from redirect after checkout

- package.json
[x] Bugfix
[ ] Feature
[ ] Other: 
If a developer wants to commit changes that doesn't include a test the precommit hook fails.
The precommit doesn't fail because of missing tests.
[ ] Yes
[x] No
This issue most probably came up after the jest 28 update.
[AB#78510](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78510)
> fix: failing precommit hook, if this commit doesn't include tests

- .eslintrc.json
- src/app/extensions/tacton/pages/configure/tacton-group/tacton-group.component.html
- src/app/extensions/tacton/pages/configure/tacton-image-text-buttons/tacton-image-text-buttons.component.html
- src/app/extensions/tacton/pages/configure/tacton-image-text-buttons/tacton-image-text-buttons.component.spec.ts
- src/app/extensions/tacton/pages/configure/tacton-selected-image/tacton-selected-image.component.html
- src/app/pages/category/category-image/category-image.component.html
- src/app/pages/product/product-master-variations/product-master-variations.component.html
- src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
- src/app/shared/components/product/product-listing/product-listing.component.html
- src/app/shared/components/promotion/promotion-details/promotion-details.component.html
- src/app/shell/header/header-checkout/header-checkout.component.html
- src/app/shell/header/header-checkout/header-checkout.component.spec.ts
- src/app/shell/header/header-default/__snapshots__/header-default.component.spec.ts.snap
- src/app/shell/header/header-default/header-default.component.html
- src/app/shell/header/header-simple/header-simple.component.html
- src/app/shell/header/header-simple/header-simple.component.spec.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
No es-lint rules are used to enforce accessibility within angular component templates.
We added some es-lint rules to improve the accessibility behavior.
[ ] Yes
[x] No
For more information see also 
[Angular A11y ESLint Rules](https://dev.to/bitovi/angular-a11y-eslint-rules-2fjc)
[Build more accessible apps in Angular](https://www.youtube.com/watch?v=Gm_bD1abFXI)
[AB#76851](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76851)
> feat: Angular A11y ESLint Rules (Accessibility)

- .eslintrc.json
Currently, vars are allowed to be unused when they're named `_`. However, `_` is not an allowed variable name so there will be another ESLint exception isntead.
=> Fixed
[AB#78545](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78545)
> chore(eslint): allow underscore variable names

- schematics/src/utils/lint-fix.ts
[x] Bugfix
Issue Number: Closes #1221
Running intershop schematics with the --dry-run option results in errors because of the appended prettier check that fails for non existing files.
Prevent the additional formatting checks with prettier for dry runs so no errors occur.
[ ] Yes
[x] No
[AB#78477](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78477)
> fix: prevent linting for running schematics with dry-run option

- src/app/core/state-management.module.ts
the comment was only necessary because of the rule's wrong behaviour.
This is fixed with https://github.com/angular-eslint/angular-eslint/pull/1001
=> comment removed
[AB#78616](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78616)
> chore: remove outdated eslint ignore comment

- projects/requisition-management/src/app/models/requisition/requisition.interface.ts
- projects/requisition-management/src/app/models/requisition/requisition.mapper.spec.ts
- projects/requisition-management/src/app/models/requisition/requisition.mapper.ts
- projects/requisition-management/src/app/models/requisition/requisition.model.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.html
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ ] Bugfix
[ x] Feature
[ ] Other: 
Requisitions that have been system rejected do not show the reject reasons.
System reject reasons are now delivered via REST API and will be shown.
[ ] Yes
[ x] No
[AB#78718](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78718)
> feat: show system reject errors for requisition

- server.ts
[X] Bugfix
It is possible to get file contents from the underlying container files system by passing a relative file system path behind any `.js` or `.css` resource url (valid for PWA 1.0 to 2.1.0).
https://host/.js?/../../../../etc/hosts would potentially leak the contents of file `/etc/hosts`
You'll get a 404 when trying to breakout of the server determined `BROWSER_FOLDER`.
(This is already fixed with 2.1.0 but this fix adds an additional check to prevent the unwanted behavior)
[X] No
https://nodejs.org/en/knowledge/file-system/security/introduction/#preventing-directory-traversal
[AB#78766](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78766)
> fix: prevent directory traversal on SSR

- src/app/core/models/product/product.helper.spec.ts
- src/app/core/models/product/product.helper.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.ts
- src/app/core/store/shopping/products/products.reducer.ts
- src/app/core/store/shopping/products/products.selectors.spec.ts
- src/app/core/utils/operators.ts
[x] Bugfix
Product images and description are sometimes missing on the product detail page when routing there from a product list.
This happens if the category products call responds later then the product details call.
Both calls are triggered when routing to the product details page.
Problem 1: There is no need for the additional category products call when routing to the product details page.
Problem 2: Product information with a lower completeness level should not overwrite product information in the state with a higher completeness level.
The first commit addresses Problem 1 by reverting the commit that introduced this wrong behavior.
The second commit fixes the product information state update handling and considers the different completeness levels.
* update the complete product …
> fix: do not overide product information in the state with information with lower completeness level

- src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Bugfix
- The missing translation key for 'Company Information' has been added on registration page.
[x] No
[AB#79014](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79014)
> fix: add missing translation key for company information on registration page

- docs/guides/migrations.md
- src/app/shared/components/product/product-image/product-image.component.html
- src/app/shared/components/product/product-image/product-image.component.ts
- src/app/shared/components/product/product-listing/product-listing.component.ts
- src/app/shared/components/product/product-name/product-name.component.html
- src/app/shared/components/product/product-name/product-name.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
After applying a product filter and switching to a master product via the "Recently viewed" section, the product variants of the master product are no longer displayed if they do not match the filter.  
The variation products are shown as expected.
[ ] Yes
[x] No
Steps to repeat:
Precondition: Advanced variation handling (List View) is checked in the channel preference of the ICM back office.
1. Navigate to a master product (e.g. "Microsoft Surface Laptop") (The variation products should be displayed in …
> fix: display variation products if a non-matching product filter has previously been set

- server.ts
[x] Bugfix
Issue Number: Closes #1257
Favicon path is no longer modified if directly requested via assets.
[ ] Yes
[x] No
[AB#79152](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79152)
> fix: do not override favicon if requested from assets

- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/store/core/configuration/configuration.selectors.ts
- src/environments/environment.model.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Precondition: the pwa cannot connect to the ICM server, e.g. because of a wrong base URL
-    without SSR (multichannel configuration) - if the user requests a page in German (route parameter lang=de_DE) the error page will be shown in English
-    with multichannel config: The translations of the json files are not returned all texts are missing in the page (missing translation is shown)
The error page is shown in the requested locale if the server doesn't respond
[ ] Yes
[x] No …
> fix: add fallbackLocales to show translations even if there is no connection to the server

- src/app/core/directives/server-html.directive.spec.ts
- src/app/core/directives/server-html.directive.ts
- src/app/extensions/compare/pages/compare/product-compare-list/product-compare-list.component.html
- src/app/extensions/compare/pages/compare/product-compare-list/product-compare-list.component.spec.ts
- src/app/pages/product/product-detail-info/product-detail-info.component.html
- src/app/pages/product/product-detail-info/product-detail-info.component.spec.ts
- src/app/pages/product/product-detail-info/product-detail-info.component.ts
- src/app/shared/components/product/product-row/product-row.component.html
- src/app/shared/components/product/product-row/product-row.component.spec.ts
* use `ishServerHtml` directive to handle embedded image resources
[x] Bugfix
* Product descriptions (short or long) are not always rendered as HTML and are not rendered with specific treatment for server side images and ICM specific link notation.
* The `ishServerHtml` directive does not handle ICM embedded images without `ismediaobject` notation. TinyMCE embedding  format after update just uses simple relative URLs in the Intershop static file system
* Directly navigating between different product detail pages does not reset a previously selected product detail tab (default would be the description tab).
* Product descriptions (short or long) are rendered with specific treatment for server side images and ICM specific link notation using the `ishServerHtml` directive.
* The …
> fix: render product descriptions with images properly

- src/app/core/models/price-item/price-item.helper.ts
- src/app/core/models/price/price.helper.ts
- src/app/core/models/price/price.model.ts
- src/app/core/models/product-prices/product-prices.interface.ts
- src/app/core/models/product-prices/product-prices.mapper.spec.ts
- src/app/core/models/product-prices/product-prices.mapper.ts
- src/app/core/models/product-prices/product-prices.model.ts
- src/app/core/models/product/product.helper.spec.ts
- src/app/core/models/product/product.helper.ts
- src/app/core/models/product/product.interface.ts
- src/app/core/models/product/product.mapper.ts
- src/app/core/models/product/product.model.ts
- src/app/shared/components/product/product-price/product-price.component.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
Retail sets and product masters use the old product REST API to display prices ranges. This should be replaced with the new product price REST api. 
The new product price REST API is used.
[ ] Yes
[ x ] No
[AB#79168](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79168)
> fix: use product price api for retail sets and product master

- src/app/core/configurations/injection-keys.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.ts
- src/app/core/store/shopping/search/search.effects.spec.ts
- src/environments/environment.model.ts
[x] Feature
There is no default mobile listing view type variable available for mobile devices
There is a default mobile listing view type variable in environments for mobile devices
[x] No
[AB#78786](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78786)
> feat: add default mobile listing viewtype

- src/app/core/configurations/injection-keys.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.ts
- src/environments/environment.model.ts
#1243 introduced a new environment config variable to handle default listing view types for mobile, while the existing variable could have been extended,
- Existing variable is extended.
- Existing variable is made optional.
[ ] Yes
[x] No
[AB#79484](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79484)
> refactor: reuse default product listing type for mobile

- .husky/post-checkout
- schematics/src/helpers/lazy-components/factory.ts
- schematics/src/utils/lint-fix.ts
Lazy Components are not removed before npm script `synchronize-lazy-components`. It can happen that removed components are still there after synchronization.
Script uses `git clean` to remove components.
[ ] Yes
[x] No
[AB#79486](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79486)
> chore: remove lazy components on synchronize

- src/app/core/models/category/category.mapper.spec.ts
- src/app/core/models/category/category.mapper.ts
so more complete data overwrites less complete one
* categoryRef was missing for categories that should already have this information
[x] Bugfix
For some category levels (second level) after the initial load of the category main navigation tree the `categoryRef` information is missing. 
The information is part of the REST response but it is somehow not mapped/copied right to the state management.
After a category details call it is available in the state.
Category Completeness Level is calculated considering more relevant response information to have better distinct completeness levels for merging the correct category information.
[x] No
[AB#79621](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79621)
> fix: rework category completeness computation

- src/app/core/guards/no-server-side-rendering.guard.ts
- src/app/core/guards/server-side-rendering.guard.ts
- src/app/pages/checkout/checkout-page.module.ts
* used for the checkout receipt page that should only be rendered in the users browser
[x] Feature
Currently the checkout receipt page is not protected by any guard. It is rendered on the server side as well as on the browser side. Since some information is missing on the server side, e.g. authentication (apiToken cookie) and user information, the needed data cannot be fetched and only an empty page can be rendered.
With the relatively simple logic of the standard checkout receipt page this is not a big problem and the page is rendered as a more or less empty page without errors in SSR and returned to the browser that will than render the page with the full content since here the needed user authentication is available.
In projects though it can happen that more information is handled for …
> feat: add "no server side rendering" guard to protect routes that should not be rendered in SSR

- schematics/src/extension/files/__name@dasherize__/store/__name@dasherize__-store.module.ts.template
- scripts/find-dead-code.ts
- server.ts
- src/app/core/services/api/api.service.ts
- src/app/core/store/store-devtools.module.production.ts
- src/app/core/utils/routing.ts
- src/app/extensions/compare/store/compare-store.module.ts
- src/app/extensions/contact-us/store/contact-us-store.module.ts
- src/app/extensions/order-templates/store/order-templates-store.module.ts
- src/app/extensions/punchout/store/punchout-store.module.ts
- src/app/extensions/quoting/store/quoting-store.module.ts
- src/app/extensions/rating/store/product-review-store.module.ts
- src/app/extensions/recently/store/recently-store.module.ts
- src/app/extensions/sentry/store/sentry-store.module.ts
- src/app/extensions/tacton/store/tacton-store.module.ts
- src/app/extensions/tracking/store/tracking-store.module.ts
- src/app/extensions/wishlists/store/wishlists-store.module.ts
[x] Bugfix
Issue Number: Closes #1222
- special case for finding exclude comment on VariableStatements
- cleanup unused dead-code excludes
[ ] Yes
[x] No
[AB#79590](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79590)
> fix: repair dead-code script exclude comments search

- .eslintrc.json
- e2e/.eslintrc.json
- eslint-rules/src/rules/ban-imports-file-pattern.ts
- eslint-rules/tests/ban-imports-file-pattern.spec.ts
- src/app/core/services/basket/basket.service.ts
- src/app/core/store/customer/basket/basket-items.effects.spec.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/shared/formly/field-library/library-config-replacement.extension.ts
[x] Bugfix
In the process of migrating to eslint (#836), the rule ban-imports-file-pattern rule lost its ability to support regex patterns in the `name` field, which left some of the migrated configuration without effect.
- `name` supports patterns again
- applied rules or changed configuration
[ ] Yes
[ ] No
[AB#79500](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79500)
> fix(eslint-rules): repair ban-imports-file-pattern rule

- src/app/core/models/filter-navigation/filter-navigation.mapper.ts
[ x ] Bugfix
If a filter facet contains a whitespace, than the ICM will encode it to '+' with the application/x-www-form-urlencoded type. This is not compatible to the url encoding on browser side, which replace a whitespace with '%20'.
Before the encoded string will be decoded on browser side, each '+' character in the string will be replaced with '%20'.
[ ] Yes
[ x ] No
[AB#79710](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79710)
> fix: replace server encoded whitespace '+' with '%20'

- src/app/core/facades/cms.facade.ts
- src/app/core/store/content/pages/pages.actions.ts
- src/app/core/store/content/pages/pages.effects.spec.ts
- src/app/core/store/content/pages/pages.effects.ts
- src/app/core/store/content/pages/pages.selectors.spec.ts
- src/app/core/store/content/pages/pages.selectors.ts
- src/app/shared/cms/components/cms-static-page/cms-static-page.component.ts
[x] Bugfix
The breadcrumb of cms pages contains always the whole path of the page tree even if a deferring navigation root is defined.
The display of the cms breadcrumb respects the defined navigation root.
[x] No
[AB#78918](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78918)
> fix: respect navigation root when displaying the breadcrumb of cms pages

- src/app/core/services/basket/basket.service.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
After a user has added a quote to cart there is no mini cart animation.
Issue Number: Closes #1041
The mini cart animation is shown if a user add a quote to cart.
[ ] Yes
[x] No
[AB#80072](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80072)
> fix: show mini cart animation after add quote to cart

- src/app/core/store/shopping/filter/filter.effects.spec.ts
- src/app/core/store/shopping/filter/filter.effects.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
1. If a logged in user navigates to a category family page with filter navigation and presses F5 (page refresh) the category page is displayed without filter navigation.
2. If an anonymous user selects a filter on a family page and clicks the login link the filter gets lost.
Issue Number: Closes #1232, #468
1. The filter navigation is displayed after refreshing the page.
2. The filter remains unchanged if a user clicks login.
[ ] Yes
[x] No
[AB#80062](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_wor …
> fix: display filter navigation after page refresh (F5)

- .vscode/launch.json
- scripts/upgrade-pwa.js
* pinned Formly 5 and Jest 28 version
* add launch configuration for upgrade-pwa script
The upgrade-pwa script no longer "downgrades" the pinned versions before trying to upgrade the dependencies. With this approach the whole automatic upgrade would no longer work. Besides that it does not seem to be a plausible approach to downgrade. So the downgrade is removed but the check for the kept pinned versions is still done at the end.
[x] No
[AB#80166](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80166)
> chore: made pinned version handling more robust in upgrade PWA script

- docs/concepts/hybrid-approach.md
- nginx/templates/multi-channel.conf.tmpl
- server.ts
- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/store/core/configuration/configuration.selectors.ts
- src/app/core/store/hybrid/hybrid.selectors.ts
- src/environments/environment.model.ts
- src/hybrid/default-url-mapping-table.ts
- src/main.server.ts
[ ] Bugfix
[ X ] Feature
[ ] Other: 
Currently you can use the hybrid mode (see below) only with one application. This has drawbacks as PWA uses the application denoted by `rest` and the classic storefront uses `-`. Certain aspects of ICM are managed application specific (e.g. CMS data) making it mandatory to merge the two applications into one. To much effort.
You can specify the used hybrid application identifier in your `environment.ts` or theme-specific `environment.<theme>.ts` with key `hybridApplication`.
```ts
export const environment: Environment = { …
```
> feat: support for two separate applications in hybrid mode

- CHANGELOG.md
- templates/header.hbs
The changelog.md file in the PWA GitHub repository contains incorrect hyperlinks within the version headlines. Headlines from version 1.2.0 to version 3.0.0 are affected.   ❌ Wrong hyperlink (example for version 2.4.1): 
https://github.com/releases/tag/2.4.1 
✅ Correct hyperlink:
https://github.com/intershop/intershop-pwa/releases/tag/2.4.1
[ ] Bugfix
[ ] Feature
[ ] Other: 
The changelog.md file in the PWA GitHub repository contains incorrect hyperlinks in the version headlines. Headlines from version 1.2.0 to version 3.0.0 are affected. …
> Update hyperlinks in version headlines

- .github/workflows/automated-upgrade.yml
- .github/workflows/dead-code.yml
- .github/workflows/demo-server-up.yml
- .github/workflows/development.yml
- .github/workflows/docs.yml
- .github/workflows/integration.yml
- .github/workflows/reports.yml
- .github/workflows/updates.yml
- .github/workflows/windows.yml
Deprecation warnings in pipeline run: `Node.js 12 actions are deprecated.` [GitHub Blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
Upgraded most actions.
[ ] Yes
[x] No
[AB#80401](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80401)
> chore: upgrade github actions

- nginx/Dockerfile
[ ] Bugfix
[ ] Feature
[ X ] Application / infrastructure changes
[ ] Other: 
Currently we use:
- nginx:1.20
- nginx-prometheus-exporter:0.10.0
We will use:
- nginx:1.22
- nginx-prometheus-exporter:0.11.0
[ ] Yes
[ X ] No
[Release page of prometheus-exporter](https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.11.0)
[Release page of nginx](https://nginx.org/en/CHANGES-1.22)
> Bump nginx and nginx prometheus exporter

- src/app/core/services/promotions/promotions.service.spec.ts
- src/app/core/services/promotions/promotions.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If a promotion is only valid for registered customers the get /promotions/id REST call ends up with a 404 (not found)
The matrix parameter spgid is added to the promotions REST call, so the REST call returns data without errors even if the promotion is only valid for registered users.
1. Create a promotion in the ICM backoffice that is only valid for registered users, e.g.
'Registered_1_37_off_for_5816351' inTRONICS Business promotion (1.37 value off for SKU 5816351 for registered users)
2. Clear …
> fix: add matrix parameter spgid to promotion REST calls 

- src/app/core/guards/login.guard.ts
- src/app/shared/components/login/login-modal/login-modal.component.html
- src/app/shared/components/login/login-modal/login-modal.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
SSR is switched on (production mode)
After a user logged in and the authentication token expired an empty login modal is displayed. If the user clicks inside the modal the content of the modal is shown.
Issue Number: Closes #1280 
The login modal is displayed with content immediately after the authentication token has expired.
[ ] Yes
[x] No
[AB#80567](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80567)
> fix: display login modal after authentication token has expired

- docs/check-sentence-newline.js
- docs/concepts/styling-behavior.md
- docs/guides/customizations.md
- docs/guides/optimizations.md
[x] Documentation content changes - regarding the integration and usage of PurgeCSS
>[PurgeCSS](https://purgecss.com/) is used to remove unused CSS classes from the CSS output. [Configuration](https://purgecss.com/configuration.html), especially [safelisting](https://purgecss.com/safelisting.html) certain classes, can be done on the plugin configuration or directly in your CSS with a special comment.
Seems to be not enough as documentation. 😉 
[x] No
[AB#80706](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80706)
> docs: extend PurgeCSS integration documentation

- schematics/src/helpers/lazy-components/factory.ts
[x] Bugfix
If the PWA 3.1.0 release assets (zip or tar.gz - https://github.com/intershop/intershop-pwa/releases/tag/3.1.0)  files are used to start a PWA it fails at the `npm install`.
This is due to the lazy components schematic needing git and a git repository but it checked only for the git command not for being in a git repository.
```
$ npm install
> intershop-pwa@3.1.0 postinstall
> npm-run-all --silent build:eslint-rules build:schematics synchronize-lazy-components init-development-environment ngcc
fatal: not a git repository (or any of the parent directories): .git
Command failed: git clean -dnx
fatal: not a git repository (or any of the parent directories): .git
npm ERR! code 1
npm ERR! path D:\intershop-pwa-3.1.0
npm ERR! command failed
npm ERR! command …
```
> fix: 'npm install' not working with PWA release zip file

- src/app/core/store/customer/basket/basket-validation.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If a user starts the checkout process on cart page a basket validation is executed but it doesn't consider properly whether all promotions are valid and applicable. The user might stay on cart page but doesn`t get any info or error message.
Promotions are included into the basket validation of the first checkout step. Errors are shown to the user if needed.
[ ] Yes
[x] No
[AB#81931](https://dev.azure.com/intershop-com/Products/_workitems/edit/80931) …
> fix: add promotion scope to basket checkout step (#80931)

- src/app/core/utils/api-token/api-token.service.ts
…guration
[ x ] Bugfix
[ ] Feature
[ ] Other: 
Api token cookies are stored with the configured multi-channel path. It cannot be shared between different configured multi sites (eg. language switch with /en, /de or /fr).
The api token is stored with '/' as path.
[ ] Yes
[ x ] No
[AB#81009](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/81009)
> fix: api token should be shared between same host

- projects/requisition-management/src/app/pages/requisition-detail/requisition-detail-page.component.html
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.spec.ts
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.ts
- src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.html
- src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.spec.ts
- src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.ts
- src/app/pages/checkout-receipt/checkout-receipt/checkout-receipt.component.html
- src/app/pages/checkout-review/checkout-review/checkout-review.component.html
- src/app/shared/components/basket/basket-address-summary/basket-address-summary.component.html
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.html
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.html
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
- src/app/shared/formly-address-forms/components/formly-address-extension-form/formly-address-extension-form.component.html
- src/app/shared/formly-address-forms/components/formly-address-extension-form/formly-address-extension-form.component.spec.ts
- src/app/shared/formly-address-forms/components/formly-address-extension-form/formly-address-extension-form.component.ts
- src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.ts
- src/app/shared/formly-address-forms/components/formly-customer-address-form/formly-customer-address-form.component.html
- src/app/shared/formly-address-forms/components/formly-customer-address-form/formly-customer-address-form.component.spec.ts
- src/app/shared/formly-address-forms/components/formly-customer-address-form/formly-customer-address-form.component.ts
- src/app/shared/formly-address-forms/formly-address-forms.module.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If an anonymous user starts the checkout he can enter an email address.
1. The email address is not shown on any checkout page
2. If the user navigates back to the checkout address page and enters another invoice address address the email address gets lost and the user is able to place the order without email address.
3. The email address cannot be changed by the user during checkout.
4. The email address is not validated in the checkout as guest form.
5. Company address fields are not shown in the checkout address form for …
> fix: entry and display of the email address during the checkout process of an anonymous user

- projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.scss
- src/styles/pages/category/product-list.scss
[ x ] Bugfix
[ ] Feature
[ ] Other: 
Two absolute positioned elements are shown in the subcategories layer when a user hovers over a catalog in the header: 
* my account: budget bar indicator
* product list and product detail page: product label ribbons
Budget bar indicator:
Budget bar indicator when hovering the catalog:
Product list product label ribbon:
Product list product label ribbon when hovering the catalog:
Product detail page product label ribbon:
Product detail page product label ribbon when hovering the catalog:
Related issue: …
> fix: prevent budget bar arrow and product label ribbons to be shown in the subcategories layer

- docs/guides/migrations.md
- src/app/core/facades/checkout.facade.ts
- src/app/core/models/line-item/line-item.interface.ts
- src/app/core/models/line-item/line-item.mapper.ts
- src/app/core/models/line-item/line-item.model.ts
- src/app/core/services/basket/basket.service.spec.ts
- src/app/core/services/basket/basket.service.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/pages/checkout-review/checkout-review-page.component.ts
- src/app/shared/components/basket/basket-desired-delivery-date/basket-desired-delivery-date.component.spec.ts
- src/app/shared/components/basket/basket-desired-delivery-date/basket-desired-delivery-date.component.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
The desired delivery date is only saved at the basket as custom attribute 'desiredDeliveryDate'. In a standard ICM back office it is not shown.
After the user has entered a desired delivery date on checkout shipping page it is additionally saved at all basket items. This way it is shown in the ICM back office in the order items table and can also be transferred to other back end systems like the IOM.
**Limitation**: In case of large baskets (> 20 items) saving the desired delivery date at all basket …
> feat: save desired delivery date at basket items

- src/app/core/facades/checkout.facade.ts
- src/app/core/models/checkout/checkout-step.type.ts
- src/app/core/store/customer/basket/basket-validation.effects.spec.ts
- src/app/core/store/customer/basket/basket-validation.effects.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/pages/checkout-address/checkout-address-page.component.ts
- src/app/pages/checkout-payment/checkout-payment-page.component.ts
- src/app/pages/checkout-shipping/checkout-shipping-page.component.ts
[ ] Bugfix
[ ] Feature
[ x ] Refactoring (no functional changes, no API changes)
[ ] Other: 
The checkout target step is set with a number. It is not really readable and understandable.
The enum 'CheckoutStepType' is implemented, which represents the available, ordered checkout steps. It should improve the understanding of the code.
[ ] Yes
[ x ] No
[AB#81268](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/81268)
> refactor: add enum CheckoutTargetStep to set next checkout step

- src/app/shared/components/search/search-box/search-box.component.ts
[x] Bugfix
When searching for products with search suggest consecutive searches that have no suggests result in errors or if ther eare suggest the result might not be as expected.
* go to the homepage of your PWA (e.g. https://intershoppwa.azurewebsites.net/)
* enter a search term that provides search suggestions (e.g. acer)
* select an entry of the suggested list (e.g. Acer C110)
* after submitting remove the search term from the search box and enter a different one without selecting (e.g. asus)
* one can see that the suggested term with the previously selected index is already selected
* pressing enter after entering the search term would trigger a search for the "selected" suggestion and not for the entered search term (probably not the expected behavior since the selection was not …
> fix: error when submitting consecutive search after submitting search from search suggestion

- e2e/cypress/e2e/specs/shopping/search-products.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/system/change-language-search-result.b2c.e2e-spec.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
[x] Feature
When searching for products and only one product is returned as the search result (either through searching explicitly for an SKU or by name) this product is displayed in the product list and a user would need to click it to switch to the product detail page.
When searching for products and only one product is returned as the search result a redirect to the product detail page is automatically done.
[x] No
[AB#80856](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80856)
> feat: route to product detail page if only one search result was found

- Dockerfile
- server.ts
- src/ssr/server-scripts/prometheus.js
[ ] Bugfix
[ x ] Feature
[ ] Other: 
When switching `PROMETHEUS=on` one metrics endpoint for SSR is exposed. That endpoint merely provides insights into PM2 "orchestrator" but [default metrics](https://github.com/siimon/prom-client#default-metrics) of Node.js processes are missing.
Provide above mentioned default metrics of Node.js + the possibility to include custom metrics on aggregated metrics registries.
[ ] Yes
[ x ] No
[AB#81853](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/81853)
> feat: provide and combine metrics of theme instances

- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
The basket will not be loaded again, when the user navigates to the /basket route. There is a possibility, that the rendered basket informations on the basket page are outdated. The basket could be updated in an another tab.
When the user has navigated to the /basket route, then the basket will be loaded from the server. 
[ ] Yes
[ x ] No
[AB#81895](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/81895)
> fix: prevent outdated informations on /basket route

- tsconfig.json
[x] Other: fix for test development environment
Since the update of cypress v10 new global types were introduced. This causes to problems for all jest tests, because the wrong `Assertion` type from cypress is used.
All files within the e2e folder will be excluded by default within the `tsconfig.json` configuration.
[x] No
[AB#81914](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/81914)
> fix: avoid cypress global types pollution in jest tests

- e2e/cypress/e2e/pages/account/order-templates-details.page.ts
- e2e/cypress/e2e/pages/quickorder/quickorder.page.ts
- e2e/cypress/e2e/specs/extras/order-templates-shopping.b2b.e2e-spec.ts
- src/app/core/facades/product-context.facade.ts
- src/app/extensions/order-templates/store/order-template/order-template.actions.ts
- src/app/extensions/order-templates/store/order-template/order-template.reducer.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Bug 1:  If the user enters a product quantity at product detail page but doesn't commit the changes and switches directly to a different product e.g. to a product of the recently viewed product the quantity input field is not reset to the product min order quantity.
Bug 2: If the user enters a retail set at product detail page and switches directly to a different single product, then quantity is set to 0 and product and quantity errors occur.
Issue Number: Closes #1330
Product informations, which are related to the product …
> fix: reset product quantity input field when switching products

- .github/workflows/demo-server-up.yml
- docs/concepts/cms-integration.md
- src/app/core/core.module.ts
- src/app/core/interceptors/preview.interceptor.ts
- src/app/core/services/preview/preview.service.spec.ts
- src/app/core/services/preview/preview.service.ts
- src/app/pages/app-routing.module.ts
[x] Feature
Initial Design Preview support (!!! NOT Design View with editing capabilities !!!)
[x] No
[AB#78271](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78271)
> feat: design preview support

- e2e/cypress.config.ts
- e2e/cypress/e2e/framework/index.ts
- e2e/cypress/e2e/pages/shopping/product-detail.page.ts
- e2e/cypress/e2e/specs/system/retain-authentication.b2c.e2e-spec.ts
- e2e/cypress/support/commands.js
- e2e/package.json
[ ] Bugfix
[ ] Feature
[ x ] Other: Dependency Update
Cypress with version 10 is used right now. It should be updated to the newest release 12.
The new cypress version enabled the testIsolation configuration option per default. It has to be disabled in the PWA. 
[ ] Yes
[ ] No
[AB#82313](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/82313)
> update: cypress to version 12.3.0

- src/app/core/utils/api-token/api-token.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user selects a payment method that requires a redirect before checkout the user is redirected to the cart page instead of the checkout review page after returning back from the payment provider. This problem occurs because the basket is not loaded in time and the checkout guard doesn`t allow to show the review page.
Refreshing the page (F5 in the browser) does also not work.
Issue Number: Closes #1355
The redirect to a checkout page is working properly again.
[ ] Yes
[x] No
This issue is related to #1156 …
> fix: redirect before checkout (checkout guard) due to a cookie restore timing issue

- src/app/core/services/prices/prices.service.spec.ts
- src/app/core/services/prices/prices.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The product price call respects the customer's default shipping address for the (gross) price display, but if the user changes his basket ship-to-address to a country that has different taxes the prices shown on the cart page might differ from the prices on the product pages.
The customer's basket ship-to-address is added as a query parameter to the product price REST call to make the result more precise and avoid differences between prices on product pages and cart prices.
[ ] Yes
[x] No …
> fix: add basket ship-to-address to product prices call 

- src/app/core/utils/api-token/api-token.service.ts
- src/app/extensions/quoting/facades/quote-context.facade.ts
- src/app/extensions/quoting/facades/quoting.facade.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If you load initially a PWA quoting detail page, than the application does not get stable. The reason for it is, that the state$ method from the quoting facade and the state property from the quote-context.facade are using a timer observable to retrieve current quoting informations. This is not necessary, because the underlying quotingEntity selector will always emit new values. Other functionality like the automaticQuoteRefresh is not used.
The timer observable is removed from the quoting and the quote …
> fix: quoting pages should be stable once

- src/app/core/services/api/api.service.ts
When the browser does not have the apiToken cookie and the angular application is in SSR mode, the ApiService#constructUrlForPath function is called before the getRestEndpoint selector is properly initialized.
This leads to an incorrect ICM token retrieval URL
[x ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[ ] No
> fix: oAuth configuration is sometime invalid on SSR mode

- src/styles/global/global.scss
[ X] Bugfix
[ ] Feature
[ ] Other: 
On the phone view, the tabs have long names in the approval section. The complete page gets a horizontal scrollbar.
Issue Number: Closes #988
The horizontal scrollbar is only usable for the tabs. The rest of the content is fixed. 
[ ] Yes
[X ] No
[AB#82472](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/82472)
> fix: scrollbar added to the approval tabs

- e2e/cypress/e2e/pages/checkout/cart.page.ts
- e2e/cypress/e2e/specs/checkout/basket-handling.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/extras/order-templates-shopping.b2b.e2e-spec.ts
- src/app/core/models/basket-info/basket-info.mapper.ts
- src/styles/global/notifications.scss
[X] Bugfix
[ ] Feature
[ ] Other: 
1. In the shopping cart item related info messages have no space on top.
2. if a product is added to the cart again there is an info message.
1. In the shopping cart item related info messages have a space on top.
2. There is no info message any more if a product is added again to the shopping cart unless the maximum purchasing policy is not met. 
[ ] Yes
[X] No
[AB#82592](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/82592)
> fix: shopping cart message needs more space

- src/typings.spec.d.ts
Add `/// <reference types="jest-extended" />` due to the fact that some editors (ie. WebStorm) do not recognizes the custom jest-extended matchers properly.
Currently, some editors do not recognize `jest-extended` matchers. 
For example:
```shell
TS2551: Property 'toBeFalse' does not exist on type 'JestMatchers<boolean>'. Did you mean 'toBeFalsy'?
```
Editor properly recognize `jest-extended` matchers without any hassle.
[ ] Yes
[X] No
> feat: add reference for jest-extended in typings.spec.d.ts

- docs/guides/migrations.md
- docs/guides/ssr-startup.md
- src/app/core/store/core/configuration/configuration.effects.ts
- src/environments/environment.model.ts
[x] Bugfix
* did not work as expected anymore anyways because of the set default `identityProvider: 'ICM' | string;` in `environment.model.ts`
* removed default from `environment.model.ts` so only hardcoded fallback from `configuration.effects.ts` works as fallback
[x] No (just removed deprecated code)
[AB#83887](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/83887)
> fix: remove deprecated SSR environment variable 'ICM_IDENTITY_PROVIDER'

- .vscode/intershop.txt
- docs/guides/accessibility.md
- projects/organization-management/src/app/components/cost-center-buyer-edit-dialog/cost-center-buyer-edit-dialog.component.html
- projects/requisition-management/src/app/pages/requisition-detail/requisition-reject-dialog/requisition-reject-dialog.component.html
- src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.html
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
- src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
- src/app/extensions/wishlists/shared/wishlist-preferences-dialog/wishlist-preferences-dialog.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
Forms in dialogs (modals) cannot be submitted using the "Enter" key if the form includes more than one form field. 
Reason: The submit button is positioned outside the `form` tag.
Forms in dialogs (modals) can now be submitted using the "Enter" key. 
[ ] Yes
[x] No
[AB#84027](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/84027)
> Correct dialog form submission with enter key

- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
When the user navigates to a basket page in the browser the PWA will dispatch a `loadBasket()` action to insure that the basket is up-to-date (the user might have changed the basket in other devices or browser tabs). The PWA doesn't wait if the user is logged in or not. This may lead to problems, so the merge basket might fail or the basket page freezes in a loading animation after browser refresh on the basket page.
Issue Number: Closes #1375
On the basket page the basket action `loadBasket()` will only be triggered, if the …
> fix: basket page errors on reload

- src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
- src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.ts
- src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.ts
- src/app/pages/forgot-password/update-password-form/update-password-form.component.spec.ts
- src/app/pages/forgot-password/update-password-form/update-password-form.component.ts
- src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
- src/app/shared/formly/types/types.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ x ] Bugfix
[ ] Feature
[ ] Other: 
For all confirmation fields the `ish-password-field` or `ish-email-field` is used. These fields are configured with a validator, which checks, that the form value follows some specified rules. This is not intended, because a confirmation input field should only check, if the value equals the form value of a related field.
All confirmation fields are configured with the default `ish-text-input` field type. All necessary validators are added seperatly. Furthermore the missing tranlation key …
> fix: validation for passwort and email confirmation fields

- docs/guides/migrations.md
- schematics/src/store/factory.ts
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.actions.ts.template
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.effects.spec.ts.template
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.effects.ts.template
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.reducer.ts.template
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.selectors.spec.ts.template
[ ] Bugfix
[ ] Feature
[ ] Other: 
The store schematics uses action creator to create store actions.
The store schematics uses the Action Group Creator to create store actions now. Find more information in this [article](https://dev.to/ngrx/ngrx-action-group-creator-1deh)
[ ] Yes
[x] No
[AB#84626](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/84626)
> refactor: use action group creator in the store action schematics

- docs/guides/angular-component-development.md
- docs/guides/migrations.md
- src/app/core/facades/product-context.facade.ts
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.html
- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.ts
- src/app/extensions/quoting/shared/quote-line-item-list/quote-line-item-list.component.html
- src/app/extensions/quoting/shared/quote-line-item-list/quote-line-item-list.component.ts
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.html
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.ts
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.html
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
**Actual Behavior**
When I change the quantity of an item in the shopping cart, right after I have already changed the quantity before, the price of the item is not updated
Issue Number: Closes #1380
**Expected Behavior**
If I have the possibility to change the item quantity, I expect a correct update of the item
[ ] Yes
[x] No
[AB#84676](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/84676)
> fix: quick quantity change on item lists

- src/app/shared/cms/cms.module.ts
- src/app/shared/cms/components/cms-product-list-rest/cms-product-list-rest.component.html
- src/app/shared/cms/components/cms-product-list-rest/cms-product-list-rest.component.spec.ts
- src/app/shared/cms/components/cms-product-list-rest/cms-product-list-rest.component.ts
- src/app/shared/shared.module.ts
[x] Feature
Adds support for an additional CMS component "Product List (REST)" that can render product lists based on any generic REST request (not just from ICM) that provides a simple or complex Array of product SKUs.
[x] No
Requires additional CMS Content Model `component.common.productListRest.pagelet2` available with ICM 7.10.40.1
[AB#84814](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/84814)
> feat: add "Product List (REST)" CMS component

- src/app/core/store/core/messages/messages.effects.ts
- src/app/core/store/customer/basket/basket.effects.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
All toaster messages will currently be rendered on SSR, if a toaster action will be dispatched during the runtime on the server.
(empty basket on basket page)
It is not possible to dismiss the SSR rendered toaster on browser side.
Furthermore basket informations will be fetched on all basket pages even on SSR. It is not possible to retrieve a personalized basket on server side.
Issue Number: Closes #1403
The message  and the loadBasketOnBasketPage effects will only subscribe to the action stream if the app is running on …
> Basket error modal window cant be closed

- docs/guides/migrations.md
- src/app/core/utils/routing.ts
- src/app/extensions/seo/store/seo/seo.effects.ts
- src/app/pages/app-last-routing.module.ts
- tsconfig.json
[x] Bugfix
* encode canonical link to match actual link URLs
* improve matcher routing for SEO URLs (#1387)
* reordered check for routing matches to first check product routes then category routes and at the end content page routes (to be less eager to assume it is a content page)
* replace all occurences of object markers (pg, prd, ctg) in slug data instead of only the first (to prevent unintended object markers with multiple occurences)
* updated ts configuration to use the Angular 15 standard configuration of `ES2022` for `lib` that includes `replaceAll`
- `replaceAll('pg', 'Pg')` could be replaced by `replace(/pg/g, 'Pg')`
[x] No
[AB#85110](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/85110)
> fix: SEO URL improvements

- src/app/core/facades/shopping.facade.ts
- src/app/core/store/shopping/products/products.selectors.ts
- src/app/extensions/recently/pages/recently/recently-page.component.html
- src/app/extensions/recently/pages/recently/recently-page.component.spec.ts
- src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.html
- src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.spec.ts
- src/app/extensions/recently/store/recently/recently.integration.spec.ts
- src/app/extensions/recently/store/recently/recently.selectors.ts
- src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.html
- src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.spec.ts
- src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.ts
- src/app/shared/components/product/product-item/product-item.component.html
- src/app/shared/components/product/product-row/product-row.component.html
- src/app/shared/components/product/product-tile/product-tile.component.html
- src/app/shared/components/product/products-list/products-list.component.html
- src/app/shared/components/product/products-list/products-list.component.spec.ts
- src/app/shared/components/product/products-list/products-list.component.ts
[x] Bugfix
When setting a product to offline in the ICM, this product will still be displayed in the Intershop PWA under the "Recently Viewed" section. The display of the product is changed as soon as the page cache is invalidated via the ICM.
The product that was set offline is no longer displayed in the "Recently Viewed" section.
[ ] Yes
[x] No
This is the same for featured products and the wish list widget in my account area.
[AB#85105](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/85105)
> fix: display offline products

- src/app/pages/product/product-images/product-images.component.html
- src/app/pages/product/product-images/product-images.component.ts
- src/app/shared/components/common/modal-dialog/modal-dialog.component.ts
- src/styles/global/modals.scss
- src/styles/global/swiper.scss
- src/styles/pages/productdetail/product-images.scss
[ ] Bugfix
[X] Feature
[ ] Other: 
Product Zoom feature has been added to the Product Detail Page.
[ ] Yes
[X] No
[AB#82318](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/82318)
> feat: product zoom feature

- src/app/core/identity-provider/identity-provider.factory.ts
`ICMIdentityProvider` can trigger a token refresh during the init phase.
https://github.com/intershop/intershop-pwa/blob/a0e0ebda056a135a1e4affeea942f41e0533c8ca/src/app/core/identity-provider/icm.identity-provider.ts#L62-L69
In the case of optimized SSR rendering, all ngrx storage conditions will be met when the `IdentityProviderFactory` constructor is called.
As a side effect, token refresh call an http request.
This http request is then intercepted by `identity-provider`
https://github.com/intershop/intershop-pwa/blob/a0e0ebda056a135a1e4affeea942f41e0533c8ca/src/app/core/interceptors/identity-provider.interceptor.ts#L12-L17
In the worst case, if all of this chain of effect can be trigger before the constructor initialization and `identityProviderFactory` will be `undefined`
```
Error …
```
> fix: identity Provider init() should be triggered async

- docs/guides/migrations.md
- src/app/core/guards/hybrid-redirect.guard.ts
- src/app/core/store/hybrid/hybrid-store.module.ts
- src/app/core/utils/routing.ts
[x] Bugfix
The changes for "refactor(Angular 15): replace class-based route guards by functional guards" (https://github.com/intershop/intershop-pwa/commit/289e1616ce4093acb35b4e070291088693e1a192) broke the registration of the global `hybridRedirectGuard` needed for the Hybrid Approach. So the Hybrid Approach is not working with PWA 4.0.0.
The global guard registration works again and the Hybrid Approach can be used with current PWA versions again.
[x] No
[AB#85701](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/85701)
> fix: adapt 'addGlobalGuard' function to work with functional guards

- src/app/core/services/basket/basket.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user applies a promotion code to the basket that contains special characters like '%' and afterwards he/she removes this promotion code an error page is shown and the promotion code has not been removed.
The removal of promotion codes that include special characters works as expected.
[ ] Yes
[x] No
ICM release 7.10.40.2 or higher is needed to use promotion codes with special characters.
[AB#84823](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/84823) …
> fix: add promotion code encoding to the REST call for promotion code removal

- docs/guides/migrations.md
- src/app/core/directives/intersection-observer.directive.ts
[X] Bugfix
[ ] Feature
[ ] Other: 
Currently the `ishIntersectionObserver` can be used as directive on a target element to determine whether the element is visible. Whenever the element moves into view and becomes visible it will emit the `IntersectionStatus` `Visible`. Given the type definition for `IntersectionStatus` [`export type IntersectionStatus = 'Visible' | 'Pending' | 'NotVisible';`] I would expect that the directive also emits a `NotVisible` event when the target element becomes invisible. This is not the case, it only emits `Pending` and `Visible` …
> chore: emit 'NotVisible' events when target element moves out of viewport

- src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Company name is not stored on address during registration of a b2b customer.
Company name is saved at the address after registration.
[B2B PWA](https://intershoppwa.azurewebsites.net/home):
- Click on registration
- Select business customer
- Fill in all required fields plus company name2, tax number, VAT number
- My Account
Profile settings > Company profile =Company name plus company name2 ✅
Addresses > Address from registration = Company name plus company name2 is missing 
--> expected:  Company name …
> fix: save company name(s) at address after b2b customer registration

- src/app/core/services/api/api.service.spec.ts
- src/app/core/services/api/api.service.ts
When the first page of the site is displayed, requests can be sent to the icm before the redux ServerConfiguration store is initialized.
This can be problematic in the case of localized URLs such as content retrieval, as the icm channel configuration can influence the value of the `;loc` and `;cur` parameters.
The fix makes sure that this store is configured before launching other localized rest requests
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[ ] No
> fix: parameters ;loc and ;cur may overlook server configuration

- src/app/core/models/product-variation/product-variation.helper.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
The product variations of a product variation master is selected by checking their `variableVariationAttributes` with the current selected facets. `val === attr.value` is used for equality check. A problem occurs when the attribute value of one of the   `variableVariationAttributes` is not a string. The check would always return false.
Issue Number: Closes #1439
[ ] Yes
[ ] No
[AB#86822](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/86822)
> fix: product variation master facet selection does not work for non-string filters

- src/app/core/models/viewtype/viewtype.types.ts
It might be useful when building some custom view for other devices or when you're in need to create a different product listing view that requires a bit different look compared to the OOTB solution but still, you may want 
to remain everything else to be fully backward compatible.
```ts
export type MyViewType = ViewType<'simple' | 'detailed'>;
export type MyDeviceType = DeviceType<'wearable' | 'smartTv'>;
```
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[x] No
> chore: add generic intersection types for ViewType & DeviceType

- src/app/core/utils/api-token/api-token.service.ts
In the case of local development, you can change the target back-end by modifying the value of the `icmBaseURL` variable  in `environment.developement.ts`. By doing so, you will need a new api token.
However, as your local DNS is still \"localhost\", there is no token renewal and the old token is kept. 
This small modification corrects this problem.
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[ ] No
> fix: fix: handle token errors for local development

- src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
There are 2 minor issues regarding the address form:
1. If the user clicks the edit address icon on the myAccount address page and the countries are not in the store yet, the country of the address is missing in the prefilled address form.
2. If the user updates an invoice or shipping address on the checkout address page and clicks the 'Add Address' link afterwards the edited address is shown in the address form instead of an empty form.
These issues have been fixed.
[ ] Yes
[x] No …
> fix: minor address form issues

- src/app/core/store/customer/addresses/addresses.effects.spec.ts
- src/app/core/store/customer/addresses/addresses.effects.ts
- src/app/shared/formly-address-forms/components/formly-customer-address-form/formly-customer-address-form.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
After changing the country of a customer address on the myAccount address page the previous country is still shown in the address tile.
The updated country is shown as expected in the address tile.
[ ] Yes
[x] No
[AB#87418](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/87418)
> fix: display updated customer address on the myAccount address page

- src/app/core/utils/translate/icm-translate-loader.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
The PWA have different places to configure the state. ICM configurations like the icmChannel can be set by the data from the theme or by the route params from the first initial PWA router action (/home?icmChannel=abc). First the PWA will set all local configurations (theme) after ROOT_INIT. After that this configuration state can be overwritten with the route applied parameters, when the routerNavigation action is triggered.
On SSR the localization.service.ts loads on server side localizations from the ICM and adds it to the …
> fix: not correct /localization call for specific MULTI_CHANNEL configuration

- src/app/shared/forms/validators/special-validators.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The date validator noSunday is supposed to check a date input field to be not a Sunday, but the check is not working.
The date validator works as expected.
[ ] Yes
[x] No
> fix: NoSunday date validator does not work properly

- Dockerfile
[x] Bugfix
After npm upgrade, the command `npm config set active-themes` does no longer work for a partial build in the Dockerfile.
Test by uncommenting the build args of the SSR image `activeThemes: b2c` in the `docker-compose.yml`:
https://github.com/intershop/intershop-pwa/blob/2c79d9704ab8644d5c57c7b1370cd2ea2a718b41/docker-compose.yml#L6-L12
Using `npm pkg set config.active-themes` to modify the package.json in the Dockerfile when building.
[ ] Yes
[x] No
[AB#88442](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88442)
> fix: repair partial build after npm upgrade

- server.ts
[x] Bugfix
Static files with calculated output hash do not send a cache-control header, but output-hashed files can be cached indefinitely as their name changes whenever the content changes.
Repaired and generalized mechanism to set cache-control header.
[ ] Yes
[x] No
[AB#88364](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88364)
> fix: repair caching for output-hashed files

- .eslintrc.json
- e2e/cypress-ci-e2e.ts
- eslint-rules/src/rules/sort-testbed-metadata-arrays.ts
- schematics/src/utils/lint-fix.ts
- scripts/find-dead-code.ts
I was typing an if statement as a one-liner and after hitting save, I expected that braces are added and my one-liner is broken to the new line. I remember this to be default behavior before.
Reactivated eslint rule `curly`.
[ ] Yes
[x] No
[AB#88491](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88491)
> chore: reactivate curly rule

- src/app/pages/product/product-images/product-images.component.ts
...on product detail page
[x] Bugfix
[ ] Feature
[ ] Other: 
When switching between product detail pages in the PWA ( e.g. via the Recently Viewed list), it may happen that instead of the primary product image (the first one), another one of the available product images is displayed. This depends on which product image was displayed on the previous PDP (e.g. if the second image of Product A was displayed, the second product image of Product B will be displayed after opening the PDP of Product B). 
After changing the product on product …
> fix: display first product image after switching products

- src/app/core/core.module.ts
- src/app/core/interceptors/pgid-change.interceptor.ts
- src/app/core/utils/api-token/api-token.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user's pgid changes due to data changes in the ICM backoffice, e.g. assigning/unassigning the user to a customer group, promotion etc. the personalized REST calls will fail with a 400 error: Bad Request (The provided matrix parameter "pgid" does not match the authenticated user.) and an error page is shown in most cases.
There is a new error handler that checks for the error above and if this error occurs the current page is reloaded. The relaod is necessary because a lot of data in the ngrx store …
> fix: reload the application after the pgid changed

- Dockerfile
- dist/entrypoint.sh
- docker-compose.yml
[x] Bugfix
When trying to stop the PWA running with docker or kubernetes, it always takes some time (~10 seconds) for the container to stop. That's because the grace period times out and the container is killed.
Signals are properly propagated to the running process:
- using `exec` in scripts
- using [`tini`](https://github.com/krallin/tini) for standalone node processes
[ ] Yes
[x] No
[AB#88361](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88361)
> fix: properly handle system signals in pwa docker container

- src/app/shared/components/product/product-image/product-image.component.html
- src/app/shared/components/product/product-name/product-name.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
When "paging" is enabled instead of "endless-scrolling" on product list pages, the query parameter "page" is part of the URL to determine the current page. If a product detail page is opened from a paged product listing page, this query parameter "page" is part of the product detail page URL. If a master product detail page is opened, the parameter "page" is also used for the paging in the master product detail page and the paged page from the product listing page is opened in the master product detail page (e.g. product …
> fix: remove query parameter "page" for product detail page routes

- src/app/core/utils/api-token/api-token.service.ts
- src/app/core/utils/cookies/cookies.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The api-token needs to be removed, when the user logs out succesfully. It's not working in a multi-site PWA setup with a custom configured `baseHref` property (e.g. /en).  The used `cookieService.remove(key)` method, to remove the apiToken, overwrites the cookie property from the window with the value `apiToken=;path=/en;expires=Thu, 01 Jan 1970 00:00:00 GMT`. The created path (e.g. '/en') differs with the initial path property from the apiToken ('/'). With the SameSite=Strict the browser doesn't allow to remove the cookie. …
> fix: remove api-token cookie just for created '/' path

- .dockerignore
- dist/.gitignore
`dist/healthcheck.js` is still excluded in `dist/.gitignore` even though it is compiled output since 9946ca26a.
removed exclude
[ ] Yes
[x] No
[AB#88757](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88757)
> chore: ignore compiled health check script

- e2e/cypress/e2e/specs/account/login-user.b2c.e2e-spec.ts
- src/app/core/identity-provider/icm.identity-provider.spec.ts
- src/app/core/identity-provider/icm.identity-provider.ts
- src/app/core/services/token/token.service.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.spec.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
[x] Bugfix
During the logout process for the icm and punchout identity provider only the apiToken cookie will be removed. The related access token information within the localStorage, which is handled by the OAuthService, will not be deleted. This can lead to unwanted behavior, that the OAuthService triggers an action to refresh the revoked access_token.
The pwa will remove for the icm and punchout identity provider all access_token informations, when the logout of the user is successful.
[x] No
[AB#88809](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88809)
> fix: remove token informations from local storage after succesful logout

- src/app/core/store/content/page-tree/page-tree.effects.ts
- src/app/core/store/content/parameters/parameters.effects.ts
- src/app/core/store/content/viewcontexts/viewcontexts.effects.ts
- src/app/core/store/core/server-config/server-config.effects.ts
- src/app/core/store/customer/basket/basket-items.effects.ts
- src/app/core/store/customer/basket/basket-payment.effects.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/core/store/general/countries/countries.effects.ts
- src/app/core/store/general/regions/regions.effects.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/extensions/contact-us/store/contact/contact.effects.ts
- src/app/extensions/punchout/store/punchout-types/punchout-types.effects.ts
[ x ] Refactoring (no functional changes, no API changes)
NGRX Effects are one of the core functionality of the PWA. It uses different actions, where the business logic is written with rxjs methods and operators. When the concatMap() operator is used, then each new subscriptions to a new observable has to wait until the previous is completed. This can lead to the problem, that http request are send sequentially although it could be done in parallel. Mainly loading actions  
[x] No
[AB#88843](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88843)
> perf: use better suited operators for REST requests

- src/app/core/facades/account.facade.ts
- src/app/core/identity-provider/icm.identity-provider.ts
- src/app/core/utils/api-token/api-token.service.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
When browsing the site using different tabs, the identification status is not well persisted across tabs.
This is particularly annoying when a user opens several tabs to compare products before adding them to the shopping cart.
The following fix corrects these problems
[X] Bugfix
[ ] Feature
[ ] Other: 
Step to reproduce the bug 
- Open 2 product tab without being logged in
- Add those product to cart on each tab
- Only the last product will be association to the current basket
When an anonymous or user token is created on one tab, the …
> fix: handle multitab browsing

- src/ssr/server-scripts/build-ecosystem.js
[ ] Bugfix
[ ] Feature
Monitoring showed that 400 MB is not enough memory for peak performance and will cause restarts by PM2.
Increased default limit.
[ ] Yes
[x] No
[AB#89006](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89006)
> perf: increase pm2 ssr max memory

- src/app/shared/cms/components/cms-carousel/cms-carousel.component.html
- src/app/shared/cms/components/cms-carousel/cms-carousel.component.ts
[x] Bugfix
While doing load tests I observed the following errors:
```
5 b2c ERROR TypeError Cannot read properties of undefined (reading 'length') at templateFn (/dist/b2c/server/webpack:/src/app/shared/cms/components/cms-carousel/cms-carousel.component.html:6:23)
5 b2c
5 b2c /dist/b2c/server/webpack:/src/app/shared/cms/components/cms-carousel/cms-carousel.component.ts:55
this.carousel.interval = val;
^
5 b2c TypeError: Cannot set properties of undefined (setting 'interval')
at Object.next (/dist/b2c/server/webpack:/src/app/shared/cms/components/cms-carousel/cms-carousel.component.ts:55:25)
at ConsumerObserver2.next (/dist/b2c/server/webpack:/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
at SafeSubscriber2._next (/dist/b2c/server/webpack:/node_modules/rxjs/dist/cjs/internal/Su …
```
> fix: prevent setting values on uninitialized field

- src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.html
- src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.spec.ts
- src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.ts
[x] Refactoring
Replaces usage of [`TranslateService.instant`](https://github.com/ngx-translate/core#methods).
[ ] Yes
[ ] No
[AB#88620](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88620)
> fix: replace translate.instant

- docs/guides/migrations.md
- src/app/core/utils/api-token/api-token.service.ts
- src/app/core/utils/browser-detection.ts
- src/app/core/utils/cookies/cookies.service.spec.ts
- src/app/core/utils/cookies/cookies.service.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.spec.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
- src/app/shell/application/cookies-banner/cookies-banner.component.html
- src/app/shell/application/cookies-banner/cookies-banner.component.ts
[x] Feature
feat: implement better handling for cookie 'SameSite' and 'secure' settings
* defaults to 'SameSite=Strict' and 'secure' if not explicitly set to other values
* sets all cookies with 'SameSite=None' if run within an iframe
* if run with 'http' (should only be in development environments) 'secure' is not set
* inspired by https://medium.com/trabe/cookies-and-iframes-f7cca58b3b9e
[x] Yes
The `cookies.service` has new defaults: `SameSite=Strict` and `secure` (see [Migrations / 4.1 to 4.2](https://github.com/intershop/intershop-pwa/blob/develop/docs/guides/migrations.md#41-to-42) for more details).
[AB#88753](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88753)
> feat: implement better handling for cookie 'SameSite' and 'secure' settings

- src/ssr/server-scripts/build-ecosystem.js
[ ] Bugfix
[ ] Feature
Load Tests show that one distributor performs better than multiple.
Removed distributor scaling.
[ ] Yes
[x] No
[AB#89013](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89013)
> perf: reduce number of distributors

- src/app/core/store/shopping/product-prices/product-prices.effects.ts
[ ] Bugfix
[ ] Feature
Every product-related page takes significantly longer to render in SSR mode than other pages.
Reduced price window debouncing for SSR.
[ ] Yes
[x] No
[AB#89001](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89001)
> perf: reduce product price call aggregation delay

- src/app/core/utils/module-loader/module-loader.service.ts
[x] Bugfix
While doing performance tests, the SSR deployments regularly crash with the following stacktrace:
```
1 b2c /dist/b2c/server/webpack:/node_modules/@angular/core/fesm2020/core.mjs:7970
throw new RuntimeError(205 /* RuntimeErrorCode.INJECTOR_ALREADY_DESTROYED */, ngDevMode && 'Injector has already been destroyed.');
^
1 b2c Error: NG0205
at R3Injector.assertNotDestroyed (/dist/b2c/server/webpack:/node_modules/@angular/core/fesm2020/core.mjs:7970:19)
at R3Injector.get (/dist/b2c/server/webpack:/node_modules/@angular/core/fesm2020/core.mjs:7877:14)
at Object.next (/dist/b2c/server/webpack:/src/app/core/utils/module-loader/module-loader.service.ts:23:36)
at ConsumerObserver2.next (/dist/b2c/server/webpack:/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
at …
```
> fix: prevent invoking destroyed injector

- docker-compose.yml
Enables running the project after checkout fast with `docker compose up` which pulls `latest` images.
[AB#89774](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89774)
> chore: add docker image names to compose file

- src/app/shared/forms/utils/forms.service.spec.ts
- src/app/shared/forms/utils/forms.service.ts
[x] Bugfix
The salutations on the registration form are not translated when refreshing the page.
The salutations on the registration are being translated when refreshing the page.
[x] No
[AB#89942](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89942)
> fix: display salutions on registration page rendering

- src/app/app.server.module.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/error/error.reducer.ts
- src/app/core/utils/state-transfer/state-properties.service.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
On SSR the PWA renders a given page. It sets a transferState, which will be used on browser side afterwards. When an error for the given ICM occurs on SSR (e.g. wrong certificate), it is possible, that wrong error properties are set in state. This can lead to  the problem, that `JSON.stringify(state)` throws an error due to the incorrect state. The outcome is, that no transferState is set on SSR. The browser side cannot retrieve the configured ICM anymore and incorrectly use the fallback (configured in …
> fix: wrong icm fallback is used when configured icm throws errors on SSR

- src/ssr/deploy-url.ts
[x] Bugfix
With the setting
```
DEPLOY_URL: '/extranet/'
```
and font definition in the SCSS files like this
```
/* Helvetica Neue Condensed Heavy - latin */
@font-face {
font-family: 'HelveticaNeue-CondensedBold';
font-style: normal;
font-weight: 400;
src: local('HelveticaNeue-CondensedBold '),
//  Super Modern Browsers
url('/assets/fonts/HelveticaNeueBold.woff2') format('woff2'),
// Modern Browsers
url('/assets/fonts/HelveticaNeueBold.woff') format('woff');
font-display: swap;
}
/* Helvetica Neue Condensed - latin */
@font-face {
font-family: 'HelveticaNeue-Condensed';
font-style: normal;
font-weight: 400;
src: local('HelveticaNeue-Condensed '),
//  Super Modern Browsers
url('/assets/fonts/HelveticaNeueNormal.woff2') format('woff2'),
// Modern Browsers …
```
> fix: deploy URL not set right for all CSS url references (e.g. fonts)

- .eslintrc.json
- projects/organization-management/src/app/store/users/users.effects.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/server-config/server-config.effects.ts
- src/app/core/store/customer/addresses/addresses.effects.ts
- src/app/core/store/customer/authorization/authorization.effects.ts
- src/app/core/store/customer/basket/basket-addresses.effects.ts
- src/app/core/store/customer/basket/basket-items.effects.ts
- src/app/core/store/customer/basket/basket-payment.effects.ts
- src/app/core/store/customer/basket/basket-validation.effects.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/core/store/customer/user/user.effects.ts
- src/app/core/store/general/countries/countries.effects.ts
- src/app/core/store/general/regions/regions.effects.ts
- src/app/core/store/shopping/categories/categories.effects.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/extensions/compare/store/compare/compare.effects.ts
- src/app/extensions/order-templates/store/order-template/order-template.effects.ts
- src/app/extensions/punchout/store/punchout-users/punchout-users.effects.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.ts
- src/app/extensions/sentry/store/sentry-config/sentry-config.effects.ts
- src/app/extensions/store-locator/store/store-locator-config/store-locator-config.effects.ts
- src/app/extensions/tacton/store/product-configuration/product-configuration.effects.ts
- src/app/extensions/tacton/store/saved-tacton-configuration/saved-tacton-configuration.effects.ts
- src/app/extensions/tacton/store/tacton-config/tacton-config.effects.ts
- src/app/extensions/tracking/store/tracking-config/tracking-config.effects.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.effects.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Find more information here: https://ngrx.io/guide/eslint-plugin/rules/prefer-concat-latest-from
[ ] Yes
[x] No
[AB#90176](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/90176)
> refactor: enable eslint rule @ngrx/prefer-concat-latest-from

- nginx/nginx.conf
- nginx/templates/multi-channel.conf.tmpl
- server.ts
[x] Bugfix
The protocol used on the topmost reverse proxy is not correctly forwarded to the SSR container.
1. Install Intershop Helm Charts:
```sh
helm repo add intershop https://intershop.github.io/helm-charts
helm repo update
```
2. create minimal `values.yaml` file for proxying ICM:
```yaml
environment:
- name: PROXY_ICM
value: "true"
- name: TRUST_ICM
value: "true"
```
3. Install release:
```sh
helm install dev-release intershop/pwa-main -f values.yaml
```
4. Forward `pwa.example.local` to `127.0.0.1` in your hosts file
5. Check the release https://pwa.example.local and observe you are getting mixed content errors
The protocol is correctly forwarded to the SSR container using and trusting the `X-Forwarded-Proto` header.
[ ] Yes
[x] No …
> fix: forward proto from reverse proxy

- src/app/core/interceptors/icm-error-mapper.interceptor.spec.ts
- src/app/core/interceptors/icm-error-mapper.interceptor.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/error/error.reducer.ts
- src/app/core/utils/state-transfer/state-properties.service.ts
improvent of #1519
* reverted: icmBaseURL no longer uses environment.ts fallback in production mode
* reverted: make usage of default/fallback configuration in environment.ts configurable for getting state properties
* refactored: errors should only contain properties of defined HttpError interface - this is now handled at the error interceptor
* kept: do not log an error that can't be stringified, it floods the log with irrelevant information
BREAKING CHANGES: No longer a breaking change regarding "No longer falls back to `environment.ts` configured `icmBaseURL` in production mode."
[x] Bugfix
The error object properties in the ~~error.reducer.ts~~ `icm-error-mapper.interceptor.ts` are reduced to the defined set of the predefined HttpError interface.
Unnecessary changes of #1519 are …
> fix: revert irrelevant changes of "wrong ICM is used with errors on SSR"

- src/ssr/deploy-url.ts
[X] Bugfix
Whenever you include external scripts in `angular.json`, angular creates a `scripts.js` file which is injected in the `index.html` file for bootstrapping the application.
This script is not yet handled properly by the deployUrl rewriting mechanism.
Fixed
[ ] Yes
[X] No
[AB#91192](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91192)
> fix: include rewriting for scripts artifact in deploy-url handling

- .github/workflows/windows.yml
Warning in [Windows Job](https://github.com/intershop/intershop-pwa/actions/workflows/windows.yml): `The following actions uses node12 which is deprecated and will be forced to run on node16: 1arp/create-a-file-action@0.2. For more info: `[`...`](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/)
Upgrade action from 0.2 to 0.3
[ ] Yes
[X] No
[AB#91155](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91155)
> build: upgrade 1arp/create-a-file-action

- src/app/pages/product/product-master-variations/product-master-variations.component.html
- src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
[X] Bugfix
When using the filter navigation for product master pages, the page navigates to the top every time something is selected.
Steps to repeat:
- go to [public demo master product](https://intershoppwa.azurewebsites.net/computers/tablets/microsoft/microsoft-surface-book-2-prd201807231-ctgComputers.897.897_Microsoft)
- select a filter (i.e. "Display size")
expected: table stays in view
actual: page navigates to top
analysis: this functionality somehow was lost during 0435372df979810854bd496ac8193cba44c82a4b
Added `fragmentOnRouting`.
[ ] Yes
[X] No
[AB#91311](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91311)
> fix: navigate to anchor on master filter selection

- src/app/core/directives/server-html.directive.spec.ts
- src/app/core/directives/server-html.directive.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
When inserting a link with a relative path to a Free Style HTML Component via TinyMCE (Full Mode) in the ICM backoffice, displaying this component in the PWA lead to a wrong absolute path, as the PWA host is set instaead of the ICM base URL. 
This works without any issues when inserting images instead of links. 
Relative paths of free style HTML components are handled correctly.
[ ] Yes
[x] No
see also [AB#91284](https://dev.azure.com/intershop-com/Products/_workitems/edit/91284) …
> fix: handle relative links in cms content

- nginx/templates/multi-channel.conf.tmpl
[x] Bugfix
`http://localhost:4200/b2c/home`
compared to
`http://localhost:4200/b2c/home/`
results in different storefronts even though the result should be the same
This problem is reproducible with the standard PWA with the following multi channel configuration with a docker compose deployed NGING + SSR container:
```yaml
MULTI_CHANNEL: |
.+:
- baseHref: /b2c
channel: inSPIRED-inTRONICS-Site
theme: b2b
- baseHref: /b2b
channel: inSPIRED-inTRONICS_Business-Site
theme: b2b
```
Using the wrong channel when working with a trailing `/` is the actual problem. The used themes configured channel of the `environment.b2b.ts` is used instead of the one configured in the multi channel configuration of the deployment.
The problem occurs with any path after adding a trailing `/`. 
An additional …
> fix: trailing '/' in path results to a wrong multi channel configuration

- src/app/core/services/products/products.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The REST call for fetching products for a product family page contains always a parameter 'sortKey' even if no special sort option is selected (in this case sortKey = 'default')
The parameter 'sortKey' is not appended at the product REST request if the default sorting is selected.
[ ] Yes
[x] No
[AB#91958](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91958)
> fix: remove sortkey 'default' from product list REST call

- src/app/extensions/order-templates/models/order-template/order-template.mapper.ts
- src/app/extensions/order-templates/services/order-template/order-template.service.spec.ts
- src/app/extensions/order-templates/services/order-template/order-template.service.ts
- src/app/extensions/wishlists/models/wishlist/wishlist.mapper.ts
- src/app/extensions/wishlists/services/wishlist/wishlist.service.spec.ts
- src/app/extensions/wishlists/services/wishlist/wishlist.service.ts
…and wishlist titles
[x] Bugfix
[ ] Feature
[ ] Other: 
It is not possible to add a malicious script (XXS) to the order template/wishlist title.
But if there is a XSS in the order template or wishlist title it is executed after the user adds a product to this order template/wishlist.
After fetching the order templates/wishlists from the server any malicious script will be removed from the title field. This scrips is not executed any more.
[ ] Yes
[x] No
[AB#92013](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_wo …
> fix: sanitize potentially dangerous values in order template... 

- src/app/core/utils/translate/fallback-missing-translation-handler.ts
[x] Bugfix
When translations are missing in both current and fallback language, the `FallbackMissingTranslationHandler` throws `EmptyError`s.
1. remove translation key `quickorder.page.link` in both en_US and de_DE localization files.
2. visit any page
Actual:
and `EmptyError` in console.
Expected:
Replaced all `first` with `take(1)` as this could happen with other sources, too.
[ ] Yes
[x] No
[AB#92108](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92108)
> fix: use take instead of first to prevent EmptyError on missing translation

- src/app/core/utils/functions.ts
- src/app/core/utils/meta-reducers.ts
`omit` is now typesafe
[ ] Yes
[x] No
[AB#92015](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92015)
> refactor: type-safe omit helper

- projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.html
- projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.spec.ts
- projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The fixes are related to user roles selection form of the the MyAccount user management, e.g. on the user creation page or the updating user roles selection page.
1. If the user clicks show/hide permissions link the page will be scrolled to the top and the user has to navigate to the appropriate role again.
2. After the user has saved a roles selection (creating a user, updating roles selection) there is an error in the console (NG0911: View has already been destroyed)
1. After clicking the show/hide …
> fix: issues regarding user roles selection

- .github/workflows/demo-server-up.yml
- .github/workflows/development.yml
- .github/workflows/integration.yml
- docs/concepts/hybrid-approach.md
- docs/concepts/software-architecture.md
- docs/guides/development.md
- docs/guides/migrations.md
- docs/guides/nginx-startup.md
- e2e/cypress/e2e/framework/users.ts
- e2e/cypress/e2e/specs/checkout/checkout-payments.b2c.e2e-spec.ts
- src/app/core/models/basket/basket.model.ts
- src/environments/environment.model.ts
BREAKING CHANGES: switch to ICM 11 and `-` as default application
With this pull request the PWA development will from now on be done mainly against ICM 11 versions.
Required data changes in the ICM
- assignment of featured products (b2b, b2c)
- free gift promotion (included categories, free gift product selection)
[AB#92178](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92178)
> feat: switch to ICM 11 demo servers

- .vscode/intershop.txt
- docker-compose.yml
- docs/README.md
- docs/guides/authentication_co_browse.md
- docs/guides/authentication_punchout.md
- docs/guides/updating-pwa.md
- src/app/core/identity-provider.module.ts
- src/app/core/identity-provider/co-browse.identity-provider.spec.ts
- src/app/core/identity-provider/co-browse.identity-provider.ts
- src/app/pages/app-routing.module.ts
- src/app/pages/co-browse/co-browse-page.guard.ts
- src/app/pages/co-browse/co-browse-page.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ ] Bugfix
[x] Feature
[ ] Other: 
Co-browsing feature enables an administrative Intershop Contact Center user to be able to login in into the pwa as a user with no need to have the credentials of that user giving him/her (the admin) the ability to see how the site looks from a real user perspective.
A new route 'cobrowse' has been introduced that has to be called together with a parameter 'token' to support this feature.
[ ] Yes
[x] No
[AB#88392](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88392)
> feat(ICM 11): co-browsing support via CEC

- docs/guides/migrations.md
- projects/organization-management/src/app/pages/cost-center-detail/cost-center-detail-page.component.html
- src/app/core/facades/account.facade.ts
- src/app/core/services/order/order.service.spec.ts
- src/app/core/services/order/order.service.ts
- src/app/core/store/customer/orders/orders.actions.ts
- src/app/core/store/customer/orders/orders.effects.spec.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/core/store/customer/orders/orders.selectors.spec.ts
- src/app/pages/account-order-history/account-order-history-page.component.html
- src/app/pages/account-order-history/account-order-history-page.component.spec.ts
- src/app/pages/account-order-history/account-order-history-page.component.ts
- src/app/shared/components/order/order-list/order-list.component.html
- src/app/shared/components/order/order-list/order-list.component.spec.ts
- src/app/shared/components/order/order-list/order-list.component.ts
- src/app/shared/components/order/order-widget/order-widget.component.html
- src/app/shared/components/order/order-widget/order-widget.component.spec.ts
- src/app/shared/components/order/order-widget/order-widget.component.ts
`ish-order-list` has too many tasks:
- can be fed with a list of orders
- can alternatively fetch orders themself
- switches the no-orders message themself depending if supplied with order list
- truncates the list if supplied with input parameter
- implicitly disables linking to details page if orders supplied directly
Performance issue:
- for the account order widget 30 orders are fetched, but only 5 displayed
- all additional properties for orders are fetched even if not used
`ish-order-list` is strictly presentational, components using it supply the data.
[x] Yes
[ ] No
BREAKING CHANGE: orders API call now uses additionally the new `limit` parameter (requires ICM 11.6), the deprecated `page[limit]`will be removed soon …
> refactor: make order list presentational

- src/app/core/facades/checkout.facade.ts
- src/app/core/services/basket/basket.service.spec.ts
- src/app/core/services/basket/basket.service.ts
- src/app/core/store/customer/addresses/addresses.reducer.ts
- src/app/core/store/customer/addresses/addresses.selectors.spec.ts
- src/app/core/store/customer/basket/basket-addresses.effects.spec.ts
- src/app/core/store/customer/basket/basket-addresses.effects.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/core/store/customer/basket/basket.selectors.spec.ts
- src/app/core/store/customer/basket/basket.selectors.ts
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.ts
- src/app/pages/checkout-address/checkout-address/checkout-address.component.html
- src/app/pages/checkout-address/checkout-address/checkout-address.component.spec.ts
- src/app/pages/checkout-address/checkout-address/checkout-address.component.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.html
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
If the user enters the checkout shipping page customer addresses were requested by the ICM. The result list contains a link list, so for each address a detail call has to be triggered. In case of many customer addresses this behavior causes a performance issue.
Relates to issue number: #1528
Now the REST call get /baskets/<basketId>/eligible-addresses is used to show addresses on checkout address page. 
All address information is returned by this call so there are no further requests necessary.
[ ] Yes
[x] No
[AB#92525](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92525)
> refactor: fetching eligible basket addresses

- docs/concepts/localization.md
- src/app/core/pipes.module.ts
- src/app/core/pipes/html-encode.pipe.spec.ts
- src/app/core/pipes/html-encode.pipe.ts
- src/app/pages/account-overview/account-overview/account-overview.component.html
- src/app/pages/account-overview/account-overview/account-overview.component.spec.ts
- src/app/pages/search/search-no-result/search-no-result.component.html
- src/app/pages/search/search-no-result/search-no-result.component.spec.ts
- src/styles/pages/category/search-result.scss
[x] Bugfix
[x] Feature
If the user enters a search term in the search bar, that contains HTML it is rendered on the search-no-result page. This represents a security risk.
The search term is not rendered as HTML but as an encoded string on the search-no-result page.
[x] No
[AB#92726](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92726)
[AB#92341](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92341)
> fix: html injection on search page if there is no result

- .eslintrc.json
- schematics/src/extension/factory.ts
- schematics/src/extension/factory_spec.ts
- schematics/src/utils/registration.ts
- schematics/src/utils/testHelper.ts
- src/app/core/configurations/configuration.meta.ts
- src/app/core/directives/feature-toggle.directive.spec.ts
- src/app/core/directives/feature-toggle.directive.ts
- src/app/core/directives/not-feature-toggle.directive.spec.ts
- src/app/core/directives/not-feature-toggle.directive.ts
- src/app/core/feature-toggle.module.ts
- src/app/core/guards/feature-toggle.guard.spec.ts
- src/app/core/identity-provider/identity-provider.factory.ts
- src/app/core/pipes/feature-toggle.pipe.spec.ts
- src/app/core/pipes/feature-toggle.pipe.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/configuration/configuration.integration.spec.ts
- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/store/core/server-config/server-config.effects.ts
- src/app/core/utils/feature-event/feature-event.service.ts
- src/app/core/utils/feature-toggle/feature-toggle.service.spec.ts
- src/app/core/utils/feature-toggle/feature-toggle.service.ts
- src/app/core/utils/module-loader/module-loader.service.ts
- src/app/pages/account/account-navigation/account-navigation.component.ts
Feature toggles in code are handles as `string` even though typing is available.
- Typed feature toggles
- extension schematic adds feature toggle
[ ] Yes
[x] No
[AB#91638](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91638)
> refactor: typed environment feature toggle

- src/app/core/facades/shopping.facade.ts
- src/app/core/store/customer/basket/basket-items.effects.ts
- src/app/core/store/shopping/products/products.effects.ts
[x] Other: Performance Implrovement
Some actions are unnecessarily fired quite often in sequence.
Reduced number of actions fired.
[ ] Yes
[x] No
[AB#93243](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/93243)
> perf: prevent unnecessary actions

- docs/concepts/configuration.md
- docs/guides/migrations.md
- projects/requisition-management/src/app/pages/requisition-detail/requisition-detail-page.component.html
- projects/requisition-management/src/app/pages/requisition-detail/requisition-detail-page.component.spec.ts
- src/app/core/core.module.ts
- src/app/core/interceptors/icm-compatibility.interceptor.ts
- src/app/pages/account-order/account-order/account-order.component.html
- src/app/pages/account-order/account-order/account-order.component.spec.ts
- src/app/pages/checkout-receipt/checkout-receipt/checkout-receipt.component.html
- src/app/pages/checkout-receipt/checkout-receipt/checkout-receipt.component.spec.ts
- src/app/pages/checkout-review/checkout-review/checkout-review.component.html
- src/app/pages/checkout-review/checkout-review/checkout-review.component.spec.ts
- src/app/pages/checkout-shipping/checkout-shipping-page.component.html
- src/app/pages/checkout-shipping/checkout-shipping-page.component.spec.ts
- src/environments/environment.b2b.ts
- src/environments/environment.model.ts
[x] Feature
In ICM 11 `messageToMerchant` is a flag supplied by the `configurations` call, so the according feature toggle is replaced.
For compatibility with ICM 7.10 an `ICMCompatibilityInterceptor` is provided that can be used to simulate the old behavior where the feature is controlled by a configured feature toggle (see the migration guide for further explanation https://github.com/intershop/intershop-pwa/blob/develop/docs/guides/migrations.md#from-50-to-51).
[x] Yes
requires ICM 11.5 or higher
[AB#93333](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/93333)
> refactor: use server setting for message-to-merchant checkout field

- src/app/core/models/cost-center/cost-center.interface.ts
- src/app/core/models/cost-center/cost-center.mapper.spec.ts
- src/app/core/models/cost-center/cost-center.mapper.ts
- src/app/core/models/order/order.interface.ts
- src/app/core/models/order/order.mapper.spec.ts
- src/app/core/models/order/order.model.ts
- src/app/core/pipes/date.pipe.spec.ts
- src/app/core/pipes/date.pipe.ts
- src/app/extensions/order-templates/models/order-template/order-template.interface.ts
- src/app/extensions/order-templates/models/order-template/order-template.model.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
1. Dates formatted by the date pipe are displayed in GMT if no timezone is given. If the user's timezone is GMT+1 and the date doesn't have a time the date of the previous day is shown to the user. You could see this behavior in the cost center order list. The dates differ from the order list dates by one day.
2. The data types for some data objects are not correct, e.g. the order creation date of the cost center orders are provided as a number array,  but they are defined as a number field.
1. The dates …
> fix: display dates that don't have a time specification

- src/app/shared/cms/components/cms-image-enhanced/cms-image-enhanced.component.html
[x] Bugfix
* Angular hydration needs a valid HTML structure that was not given with the surrounding `<p>` tag for the text/description on the image since the standard freestyle HTML is included in `<p>` tags and `<p>` in `<p>` resulted in hydration errors
* use `<div>` instead of `<p>` element for freestyle HTML on enhanced image teaser to prevent rendering errors
* see https://angular.io/guide/hydration#valid-html-structure
[x] No
[AB#93448](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/93448)
> fix: prevent rendering errors for text on enhanced image teaser caused by Angular hydration

- docs/guides/migrations.md
- src/app/core/models/viewtype/viewtype.types.ts
- src/app/core/store/core/viewconf/viewconf.selectors.ts
- src/app/shell/header/header/header.component.html
- src/app/shell/header/header/header.component.ts
[x] Bugfix
When loggin in with `/cobrowse` or `/punchout` two headers are rendered for a short time. The simple header of the loading page and the standard header once the user was logged in. After a second the simple header will disappear and everything looks as expected.
This is only visible with Server Side Rendering and the newly introduced hydration of Angular 16 (https://angular.io/guide/hydration).
Switching from the usage of `ngSwitch` to `ngIf` for selecting the different headers solved the rendering problem for the login header combinations, even though the HTML source code does not look better this way. :(
An alternative could have been to disable the hydration for the header.
```
<ish-header ngSkipHydration />
```
But this would also mean to loose these improvements for the …
> fix: display of duplicated headers for special logins with activated hydration

- src/styles/components/header/search-container.scss
- src/styles/global/forms.scss
- src/styles/pages/category/search-result.scss
[x] Bugfix
[ ] Feature
[ ] Other: 
Google Chrome is showing a small "x" inside the search input field `<input type="search">` when the user enters anything in the field. The field is shown in the header and on the "No search result" page. This element should be removed because there is already "x" as an icon to remove the user input.
The Chrome default "x" is removed. Other default Chrome styling and elements for this specific field are removed too.
[ ] Yes
[x] No
[AB#94200](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit …
> fix: remove default search input field specific elements in Chrome

- src/app/core/store/shopping/categories/categories.effects.ts
- src/app/shell/header/header-navigation/header-navigation.component.html
- src/app/shell/header/header-navigation/header-navigation.component.ts
[x] Feature
[x] Other: performance improvement
Currently, the configured level of main navigation categories (`mainNavigationMaxSubCategoriesDepth`) is loaded already on the server side. Therefore the SSR rendered HTML page contains a lot of unneeded category data (main navigation HTML, transfer state, transfered REST call content).
The goal is to reduce the load time/size of HTML pages in the project. Only the top-level categories are now being loaded and rendered on SSR while the sub-level categories are loaded and rendered on the client side.
* "lazy loading" of sub categories for the main navigation only on client side
* reduce rendered main navigation code in SSR rendered HTML
* reduce categories content of the transfer state
* decrease needed transfer size per SSR page
[x] No …
> feat: Lazy Loading of Sub categories

- nginx/templates/multi-channel.conf.tmpl
[x] Bugfix
The fix for " trailing '/' in path results to a wrong multi channel configuration (#1553)" results in NGINX re-writting errors ("the rewritten URI has a zero length") for `MULTI_CHANNEL` configurations that use the default `baseHref` of `/` when accessing the root route with https://intershoppwa.azurewebsites.net instead of https://intershoppwa.azurewebsites.net/home.
In addition the canonical link element is not correctly generated at the root. The double `//` between the domain name and the `home` route can be interpreted by search enginesas a duplicate, and thus impact the SEO ranking of the website.
The NGINX route rewrite handling for '/home' and '/loading' was improved to work with `MULTI_CHANNEL` configurations with and without the default `baseHref` of `/`.
The NGINX …
> fix: improved NGINX route rewrite handling for '/home' and '/loading'

- docs/guides/address-doctor.md
- docs/guides/nginx-startup.md
[x] No
[AB#94887](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94887)
> docs: documentation improvements (Redis, Address Doctor)

- src/app/core/models/product-variation/product-variation.helper.ts
- src/app/core/models/product-variation/variation-attribute.mapper.ts
- src/app/core/routing/product/product.route.ts
- src/app/pages/product/product-master-variations/product-master-variations.component.html
- src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
- src/app/pages/product/product-master-variations/product-master-variations.component.ts
[x] Bugfix
The PWA cannot display master products without variable variation attributes correctly.
To reproduce, remove all variable variation attributes from a master product.
Safety checks added to PWA.
[ ] Yes
[x] No
[AB#94631](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94631)
> fix: display variations when there are no variation attributes

- e2e/cypress/e2e/specs/account/login-user.b2c.e2e-spec.ts
- src/app/core/services/token/token.service.spec.ts
- src/app/core/services/token/token.service.ts
- src/app/core/utils/instance-creators.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Currently, the pwa uses a dedicated instance of `OauthService` for `token.service.ts`.
But as it doesn't redefine the associated `OAuthStorage`, all persistent data is shared between SSO implementations (like the bearer token).
This fix adds the `token_` prefix in front of all keys read and written by `token.service.ts`.
[ ] Yes
[x ] No
> Use a prefix for internal token oauth storage

- src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.spec.ts
- src/app/core/models/content-pagelet/__snapshots__/content-pagelet.mapper.spec.ts.snap
- src/app/core/models/content-pagelet/content-pagelet.mapper.spec.ts
- src/app/core/models/content-pagelet/content-pagelet.mapper.ts
[x] Bugfix
If the CMS content uses nested component templates the rendering result might not look as expected and result in the display of duplicated content.
Using component templates won't result in duplicated content because all pagelets get a unique ids in the ngrx state management even if component templates are used.
[x] No
[AB#95047](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95047)
> fix: render CMS content based on component templates correctly

- src/app/core/models/product-variation/product-variation.helper.spec.ts
- src/app/core/models/product-variation/product-variation.helper.ts
- src/app/core/models/product-variation/variation-attribute.model.ts
- src/app/core/pipes.module.ts
- src/app/core/pipes/variation-attribute.pipe.spec.ts
- src/app/core/pipes/variation-attribute.pipe.ts
- src/app/shared/components/product/product-variation-display/product-variation-display.component.html
[x] Bugfix
[x] Feature
[ ] Other: 
Variation attribute values can be supplied in different data types by the ICM, like string, number or even a complex data type 'quantity' consisting of a number value and a unit, which is often used in customer projects.
The inSPIRED store currently only supports string attributes, other attribute data types don't work properly.
Number and complex values of variation attributes are supported.
[ ] Yes
[x] No
[AB#94653](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94653)
> feat: handle complex values of variation attributes

- src/app/core/models/product-variation/product-variation.helper.spec.ts
- src/app/core/models/product-variation/product-variation.helper.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If a product has more than 2 variation attributes in the variation select options all options are displayed as not available.
The calculation of the variation availabilty works now properly and only attribute (combinations) that are not available are shown as not available.
[ ] Yes
[x] No
[AB#94629](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94629)
[AB#95151](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95151)
> fix: product variation availability for more than 2 variation attributes combinations

- projects/requisition-management/src/app/pages/requisition-detail/requisition-reject-dialog/requisition-reject-dialog.component.ts
- src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.ts
- src/app/extensions/wishlists/shared/wishlist-preferences-dialog/wishlist-preferences-dialog.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
After saving data in dialogs, e.g. after order template creation. wishlist creation or requisition rejection a validation form error is shown before the dialog is automatically closed.
There is no validation error shown in this case.
[ ] Yes
[x] No
[AB#95292](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95292)
> fix: suppress validation error after data creation in dialogs

- src/app/core/models/content-page-tree-view/content-page-tree-view.model.spec.ts
- src/app/core/models/content-page-tree-view/content-page-tree-view.model.ts
- src/app/core/models/content-page-tree/content-page-tree.mapper.ts
[x ] Bugfix
[ ] Feature
[ ] Other: 
In production, we encountered a particular case, occurring only in server-side rendering, which contained the formation of a content-page-tree looping back on itself. 
It was not possible to identify the code that led to this case. 
However, the mapper was strengthened to avoid iterating indefinitely in the previous case.
[ ] Yes
[x ] No
> fix: infinite loop can occur in the mapping of the content page tree

- src/app/core/directives/scroll.directive.ts
- src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.html
- src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.ts
[X] Bugfix
[ ] Feature
[ ] Other: 
When validation messages appear in the PWA during checkout, the page scrolls down, causing the focus to shift away from the message. This disrupts user experience as the message is no longer in view.
The scroll behavior of the basket validation results component has been simplified. The scroll duration has been set to 0 because in case of a delay the scroll target element might not be available any more if validation results lead to (automatical) route changes.
[ ] Yes
[X] No …
> fix: wrong scrolling behavior

- docs/guides/customizations.md
- docs/guides/getting-started.md
[ ] Bugfix
[ ] Feature
[ ] Other: 
The icmBaseUrl was outdated in some documentation files.
The ismBaseUrl has been updated  so it is up to date now in the documentation files.
[ ] Yes
[x] No
[AB#95680](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95680)
> docs: update default icmBaseUrl in doc files

- docs/guides/ssr-startup.md
- scripts/icm-cache.js
- src/app/core/store/core/configuration/configuration.selectors.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
SSR process uses the same external URL for the ICM as the browser application.
Introduced `ICM_BASE_URL_SSR` which can be optionally set to use a different URL for the ICM in the SSR process.
This is useful for testing and could be used in deployments, were the ICM runs in the same Kubernetes cluster as the PWA deployment.
[ ] Yes
[x] No
[AB#95720](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95720)
> feat: exclusive ICM url for SSR process

- .eslintrc.json
- src/app/core/models/product-variation/product-variation.helper.ts
- src/app/core/models/product/product.mapper.ts
- src/app/core/services/products/products.service.ts
- src/app/core/store/shopping/product-listing/product-listing.selectors.ts
- src/app/extensions/quoting/services/quoting/quoting.service.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.selectors.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Lodash [`flatten`](https://lodash.com/docs/4.17.15#flatten) is used.
Lodash `flatten` is disallowed and replaced by the new TypeScript [`Array.flat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)
[ ] Yes
[x] No
[AB#95730](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95730)
> refactor: replace lodash flatten with built-in function

- docs/guides/nginx-startup.md
- nginx/Dockerfile
- nginx/docker-entrypoint.d/40-gomplate.sh
- nginx/nginx.conf.tmpl
[x] Feature
`worker_processes auto` and `worker_connections 1024` is currently hard coded in the `nginx.conf` and cannot easily be changed via deployment.
`nginx.conf` is changed to a gomplate template and `worker_processes` and `worker_connections` are now configurable via environment variables `NGINX_WORKER_PROCESSES` and `NGINX_WORKER_CONNECTIONS`.
[x] No
[AB#95876](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95876)
> feat(nginx): make `worker_processes` and `worker_connections` configurable

- docs/guides/address-doctor.md
- src/app/extensions/address-doctor/exports/address-doctor-exports.module.ts
- src/app/extensions/address-doctor/services/address-doctor/address-doctor.service.spec.ts
- src/app/extensions/address-doctor/services/address-doctor/address-doctor.service.ts
- src/app/extensions/address-doctor/store/address-doctor-store.module.ts
- src/app/extensions/address-doctor/store/address-doctor-store.ts
- src/app/extensions/address-doctor/store/address-doctor/address-doctor.actions.ts
- src/app/extensions/address-doctor/store/address-doctor/address-doctor.effects.spec.ts
- src/app/extensions/address-doctor/store/address-doctor/address-doctor.effects.ts
- src/app/extensions/address-doctor/store/address-doctor/address-doctor.reducer.ts
- src/app/extensions/address-doctor/store/address-doctor/address-doctor.selectors.spec.ts
- src/app/extensions/address-doctor/store/address-doctor/address-doctor.selectors.ts
- src/app/extensions/address-doctor/store/address-doctor/index.ts
[x] Bugfix
The Address Doctor has to be configured in the `environment.ts` file. The feature does not take effect when providing the necessary configurations in a YAML file for a Flux deployment or in a `docker_compose` file. 
The address doctor can be configured in a YAML file for a Flux deployment or in a `docker_compose` file as well.
[x] No
[AB#95679](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95679)
> fix: save address doctor configuration in the ngrx store

- docs/guides/development.md
- scripts/init-development-environment.js
[x] Feature
When the template for `environment.development.ts` has to be customized for a project, it has to be done in the script.
The script searches for a template file first.
[ ] Yes
[ ] No
[AB#96075](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96075)
> feat: use template for environment.development.ts if avalable

- schematics/customization/add/index.js
- schematics/src/helpers/override/factory_spec.ts
[X] Feature
When adding a default theme with the customization starter script, the new theme is just added in front of the list of theme recommendations when using the override schematic.
When adding a default theme, the list of recommended themes is replaced with the new theme.
[ ] Yes
[X] No
[AB#96039](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96039)
> feat: set default theme also as default for override schematic

- src/app/app.module.ts
[X] Application / infrastructure changes
The introduction of SSR hydration with the last Angular Upgrade also activated HTTP Cache transfer which is not desired in all cases. The PWA version before was designed to specifically refetch certain resources when booting up on the client (i.e. CMS and Product Data).
HTTP Client Cache is disabled again.
[ ] Yes
[X] No
[AB#95994](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95994)
> fix: disable hydration HTTP transfer cache

- .github/workflows/mark-conflicts.yml
When resolving conflicts on PRs, the `has conflicts` label is not automatically removed.
The workflow is retriggered for PR updates.
[ ] Yes
[X] No
[AB#96290](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96290)
> build: reevaluate has-conflicts label on PR push

- docs/guides/migrations.md
- projects/organization-management/src/app/services/cost-centers/cost-centers.service.spec.ts
- projects/organization-management/src/app/services/cost-centers/cost-centers.service.ts
- projects/organization-management/src/app/services/users/users.service.spec.ts
- projects/organization-management/src/app/services/users/users.service.ts
- src/app/core/services/address/address.service.ts
- src/app/core/services/api/api.service.ts
- src/app/core/services/authorization/authorization.service.ts
- src/app/core/services/newsletter/newsletter.service.spec.ts
- src/app/core/services/newsletter/newsletter.service.ts
- src/app/core/services/payment/payment.service.ts
- src/app/core/services/products/products.service.ts
- src/app/core/services/user/user.service.ts
- src/app/core/utils/url-resource-ids.ts
- src/app/extensions/order-templates/services/order-template/order-template.service.ts
- src/app/extensions/product-notifications/services/product-notifications/product-notifications.service.ts
- src/app/extensions/punchout/services/punchout/punchout.service.ts
- src/app/extensions/quoting/services/quoting/quoting.service.ts
- src/app/extensions/rating/services/reviews/reviews.service.ts
- src/app/extensions/wishlists/services/wishlist/wishlist.service.ts
* encode all URI components
* only constants doesn't need to be encoded
[x] Bugfix
[ ] Feature
[ ] Other: 
Issue Number: Closes #1640
The PR provides a central function to select two behavior:
* duplicated component encoding (for former ICM releases)
* single component encoding (for future fixed versions)
see encodeResourceID at src/app/core/utils/url-resource-ids.ts
[] Yes
[X] No
To be able to use "single" encoded URI components a new versions of ICM application server and HTTPD configuration are necessary. 
ICM-AS fix required - removes duplicate decoding …
> fix: URI components are not encoded correctly (#1640)

- .prettierignore
- docs/concepts/cms-integration.md
- docs/guides/migrations.md
- src/app/pages/category/category-categories/category-categories.component.html
- src/app/pages/category/category-products/category-products.component.html
- src/app/pages/product/product-detail/product-detail.component.html
- src/app/pages/product/product-detail/product-detail.component.spec.ts
- src/app/pages/product/product-page.component.html
- src/app/pages/product/product-page.component.spec.ts
- src/assets/sample-data/view_contexts_import.xml
* commented out view context integration in HTML templates
* providing an sample import file with the used view contexts for ICM
* added documentation
[x] Other: disabled for better performance
Up till now we render a set of view contexts throughout the PWAs category and product pages. This creates a lot of REST calls and decreases SSR rendering performance in an unnecessary way if this feature is not used.
The view context integration is now commented out and no longer active. It needs to be actively enabled where wanted in a customer project or demo system.
[x] No - if view context rendering was not used
[AB#96291](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96291)
> perf: disable rendering of view contexts by default

- src/app/core/utils/design-view/design-view.service.ts
- src/app/pages/content/content-page.component.html
- src/app/shared/cms/components/content-viewcontext/content-viewcontext.component.ts
[AB#92782](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92782)
> feat: provide page structure tree information for the Design View

- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.scss
[x] Bugfix
The border and the edit tab / panel of the highlighted component in the Design View is shown outside the component area. If a component is formatted using the CSS property `overflow: hidden;`, the highlight (surrounding) border and the edit tab / panel was cut and not shown.
The border and the edit tab / panel of the highlighted component in the Design View is shown **inside** the component area to always show it when hovering the component even if the CSS property `overflow: hidden;` is used.
[x] No
[AB#96418](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96418)
> fix: show Design View editing frame highlighting inside the component to avoid cut display

- src/app/core/utils/translate/icm-translate-loader.ts
[x] Bugfix
The fix addresses the issue https://github.com/intershop/intershop-pwa/issues/1646 when adding a new locale.
`first()` expects the source Observable to emit at least one item. If the Observable completes without any emissions, `first()` will throw a NoSuchElementException to indicate that no elements were emitted. In the context of the issue, if the Observable is expected to emit at least one value but doesn't, `first()` enforces the emission of at least one item. This could happen if, for example, the translation data isn't loaded as expected due to a network issue, incorrect configuration, or if the data is filtered out before it reaches `first()`. It is now changed to `take(1)`. 
[x] No
[AB#96420](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_worki …
> fix: localization - avoid NoSuchElementException when adding a new locale

- src/app/core/directives.module.ts
- src/app/core/directives/browser-lazy-view.directive.ts
- src/app/core/directives/intersection-observer-util.ts
- src/app/core/directives/intersection-observer.directive.ts
- src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.html
- src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.spec.ts
- src/app/extensions/tacton/pages/configure/tacton-group/tacton-group.component.ts
[X] Feature
[X] Refactoring (no functional changes, no API changes)
Added `*ishBrowserLazyView` directive to lazy load content when it is in the viewport on the browser side. This helps limiting requests made in the SSR process.
[ ] Yes
[X] No
[AB#96475](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96475)
> feat: add *ishLazyBrowserView directive

- docs/guides/mocking-rest-calls.md
- src/app/core/interceptors/mock.interceptor.spec.ts
- src/app/core/interceptors/mock.interceptor.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Mocking to potentially personalized resources fails due to the fact that the full request URL is passed as the target point in the Mock Interceptor class.
Setup:
```ts
apiMockPaths: ['^products.*/1005182'],
```
Console Log:
>  redirecting 'http://localhost:4200/INTERSHOP/rest/WFS/Camfil-CamfilFI-Site/rest;loc=fi_FI;cur=EUR/products;spgid=UEyi3WOuZg2RpGp_3Xqb4c3l0000/1005182' to './assets/mock-data/products;spgid=UEyi3WOuZg2RpGp_3Xqb4c3l0000/1005182/get.json'`
Response:
```
Request URL: …
```
> fix: improve mock data redirection for urls w/ matrix parameter

- src/app/pages/checkout-payment/payment-parameter-form/payment-parameter-form.component.ts
[x] Bugfix
Currently input masking  is used only for budgets and price notifications.
Issue Number: Closes #1645
Consistent behavior would be great. Implement input masking also for IBAN and BIC.
[x] No
There is currently no solution to use ngbdatepicker, formly and ngx-mask together. We have therefore decided not to use a mask for dates.  
[AB#96479](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96479)
> fix: implement input mask for IBAN and BIC

- src/app/extensions/product-notifications/shared/product-notification-edit-form/product-notification-edit-form.component.ts
[x] Bugfix
Trying to set a price notification for a product without a price is currently not possible because a dialog without the needed form inputs is presented and it results in browser Javascript errors.
If the product has no price `99.99` is used as initial value and the price notification form is presented as expected in the dialog. No Javascript errors are logged.
[x] No
[AB#96603](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96603)
> fix: handle setting price notification for products without a price

- src/app/core/pipes/html-encode.pipe.ts
- src/app/extensions/order-templates/models/order-template/order-template.mapper.ts
- src/app/extensions/order-templates/services/order-template/order-template.service.spec.ts
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
- src/app/extensions/wishlists/models/wishlist/wishlist.mapper.ts
- src/app/extensions/wishlists/services/wishlist/wishlist.service.spec.ts
- src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
[x] Bugfix
Wishlist and order templates titles with special characters (e.g. ä,ö,ü) are not displayed correct.
This is a result of PR #1551 that sanitizes potentially dangerous wishlist/order template titles coming from the REST API.
The changes from #1551 where reverted to correctly display wishlist/order template titles.
The danger from self given titles for wishlists/order templates seems low compared to the strange rendering of special characters.
To prevent the only known place where possibly dangerous code is evaluated the `ishHtmlEncode` pipe is used.
[x] No
[AB#96600](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96600)
> fix: wishlist and order templates title with special characters not displayed correct

- docs/guides/migrations.md
- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/utils/product-context-display-properties/product-context-display-properties.service.ts
- src/app/extensions/punchout/exports/punchout-product-context-display-properties/punchout-product-context-display-properties.service.ts
- src/app/extensions/tacton/exports/tacton-product-context-display-properties/tacton-product-context-display-properties.service.ts
[x] Bugfix
On product detail pages and product listings products without a sale price display an "Add to Cart" button that will result in an error message regarding the failed action because of the missing price.
Products without a sale price no longer have an "Add to Cart" button.
The `ExternalDisplayPropertiesProvider` `setup` notation was changed from providing only the `product` context to providing a combined `{ product, prices }` context object to be able to depend the visibility of the add to basket button on an existing price.
For that reason any custom `ContextDisplayPropertiesService` that implements the `ExternalDisplayPropertiesProvider` needs to be adapted accordingly.
[x] Yes
[AB#96517](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/9 …
> fix: do not display "add to cart" button if product has no price

- docs/guides/customizations.md
- schematics/src/component/factory.ts
- schematics/src/component/factory_spec.ts
- schematics/src/component/schema.json
[X] Feature
When creating components via schematics, you cannot skip creating tests.
You can skip creating tests with `--skip-tests`
[ ] Yes
[X] No
[AB#96750](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96750)
> feat(schematics): skip creating tests for components

- src/app/core/utils/routing.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Product URLs that have a '%' in the SEO slug part don't work properly and lead to a 'Not Found' page.
The '%' signs are removed from the SEO slugs and they aren't part of the URL any more.
[ ] Yes
[x] No
[AB#97477](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/97477)
> fix: remove '%' signs from product slugs

- package.json
- scripts/sort-i18n.mjs
Language files are not sorted in npm `format` task, only in pre-commit hook.
Language files are also sorted in `format` task.
[ ] Yes
[X] No
[AB#96980](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96980)
> chore: sort i18n files in format task

- src/app/core/facades/selected-product-context.facade.ts
- src/app/core/utils/routing.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Product URLs are not encoded if they are called programmatically. This might cause issues if the URL contains special characters like % signs if a variation product is switched on product detail page.
Product URLs are encoded if they are called programmatically. 
[ ] Yes
[x] No
[AB#97578](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/97578)
> fix: encode product urls

- src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.ts
- src/app/core/store/shopping/search/search.effects.spec.ts
- src/app/core/store/shopping/shopping-store.spec.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
When searching for a search term in the PWA and applying a filter afterwards, a subsequent search leads to a short display of "NO RESULTS FOUND" before the correct search results are returned. 
The "NO RESULTS FOUND" is not shown in this case any more.
##Steps to repeat
1. Open the PWA storefront and search for a search term (e.g. "PC").
2. Select a filter (e.g. Color = "Red").
3. Search for another search term (e.g. "HDMI").
-> "NO RESULTS FOUND" is displayed for a short time before the correct results …
> fix: suppress the wrong display of Search-No-Results page after a search

- src/app/pages/account-profile-user/account-profile-user-page.component.html
- src/app/pages/account-profile-user/account-profile-user-page.component.spec.ts
- src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.html
- src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.spec.ts
- src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.ts
[X] Refactoring (no functional changes, no API changes)
AccountProfileUserComponent uses `currentUser$` as an Observable input and subscribes to it on the template to use it synchronouslly in the TS file. Both of this is considered bad practice.
Refactored using RxState and reintroduced normal Component Input.
[ ] Yes
[X] No
[AB#96966](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96966)
> refactor: rework account-profile-user component

- e2e/cypress/e2e/specs/shopping/variation-handling.b2b.e2e-spec.ts
- src/app/core/facades/selected-product-context.facade.ts
- src/app/core/utils/routing.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Our variations e2e tests fail. One reason is the PR #1688 with changes regarding the encoding of product URLs. The other reason might be some hydration problems on product detail page.
The PR #1688 has been reverted and the flaky test has temporarily been disabled.
[ ] Yes
[x] No
[AB#97873](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/97873)
> test: fix flaky variations e2e test

- src/app/extensions/captcha/shared/captcha-v3/captcha-v3.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If a form is secured by the captcha V3 component the captcha V3 token is fetched for the 1st time after the form gets valid. If the user sends the form immediately after the form is getting valid the response from the token request is still missing and the form submission ends with a 401 error  "Unauthorized (Captcha authentication required)"
The captcha V3 token is fetched for the 1st time after the user has started to edit the form. The token is supposed to be available before the user submits the …
> fix: fetch captcha V3 token after first form input

- src/app/core/store/customer/basket/basket-validation.effects.spec.ts
- src/app/core/store/customer/basket/basket-validation.effects.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/pages/checkout-address/checkout-address/checkout-address.component.html
- src/app/pages/checkout-address/checkout-address/checkout-address.component.spec.ts
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
- src/app/pages/checkout-review/checkout-review/checkout-review.component.html
- src/app/pages/checkout-review/checkout-review/checkout-review.component.spec.ts
- src/app/pages/checkout-shipping/checkout-shipping-page.component.html
- src/app/pages/checkout-shipping/checkout-shipping-page.component.spec.ts
- src/app/shared/components/common/error-message/error-message.component.html
- src/app/shell/header/mini-basket/mini-basket.component.html
- src/app/shell/shell.module.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
1. If an error occurs because the basket has expired an error message 'undefined' is shown on checkout pages.  
2. If the user clicks on the mini cart icon of an empty cart in mobile view the empty cart page is shown with an error message.
Find a more detailed bug descriptions in the issues below.
Issue Number: Closes #1669 , #1675
1. The message 'The cart could not be found' is shown instead. If the user tries to continue checkout he is navigated to the (empty) cart page.
2. Clicking the cart icon shows a popup message …
> fix: error message in the checkout after basket has expired

- src/app/core/facades/checkout.facade.ts
[x ] Bugfix
[ ] Feature
[ ] Other: 
After user login on the checkout address page the determination of the eligible addresses failed. The reason for this that the corresponding rest request is executed against the wrong basket. 
Issue Number: Closes #98413
[ ] Yes
[x ] No
[AB#98417](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/98417)
> fix: change facade method for eligible address determination (#98413)

- .github/workflows/automated-update.yml
- .github/workflows/dead-code.yml
- .github/workflows/updates.yml
- .nsprc
- .prettierignore
- package-lock.json
- package.json
* `npm audit --omit=dev` will result always in a vulnerability issue as long as we have a dependency to Bootstrap 4.6.2
* since we only use the styling of Bootstrap in combination with ng-bootstrap the vulnerability should not be an issue
* so we now use a vulnerability checker that allows for exceptions for checking for vulnerabilities in the develop branch
[x] Other: deps checking
[x] No
[AB#99145](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/99145)
> deps: use "Better NPM Audit" to check for production vulnerabilities with allowed exceptions

- .eslintrc.json
[x] Bugfix
The eslint-rule `no-intelligence-in-artifacts` only checks component files with the pattern `*.component.ts` and `*.component.spec.ts`. That's why files for specific themes, like `*.component.b2b.ts`, are not being checked by this lint rule.
The eslint-rule `no-intelligence-in-artifacts` checks basic component files as well as components of arbitrary specific themes.
[x] No
[AB#100457](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/100457)
> fix: eslint-rule "no-intelligence-in-artifacts" also checks components of different themes

- src/app/core/facades/checkout.facade.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/pages/basket/shopping-basket-payment/shopping-basket-payment.component.ts
* move the loading to the fastpay component to avoid REST requests if the component is not used
[ ] Bugfix
[ ] Feature
[ ] Other: 
The eligible payment methods are always loaded if the user enters the basket page, no matter if it is needed (only needed for the display of the fastpay payment methods)
The eligible payment methods are loaded by the shoppingBasketPaymentComponent - if this component is not used by a project the REST call will not be executed.
[ ] Yes
[x] No
[AB#100622](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927 …
> refactor: load eligible payment methods on basket page

- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
On cart page the eligible cost centers are fetched from the ICM using a call like this:
/customers/OilCorp/users/bboldner%40test.intershop.de//costcenters
There is an unwanted double slash in it.
This leads to a 404 error on cart page for b2b users if ICM version 13 is used.
The double slash is changed into a single slash
[ ] Yes
[x] No
[AB#101454](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/101454)
> fix: remove double slashes in cost center REST call

- docs/guides/migrations.md
- src/app/core/services/user/user.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
It is possible to change the e-mail address in the user profile of the My Account without correct password, while there is a need to enter the password. The password is sent in the request header of the user put request, but is is not checked by the ICM any more.
The password is sent to the ICM in the request body of the user put request (updateUser method of the user.service.ts) now.
There the password is validated by the ICM when the user's email is changed. 
[ ] Yes
[x] No
Requires ICM 13.0, 12.3.1, or 7.10.41.7 or higher …
> fix: password check for user email update

- src/app/core/guards/no-server-side-rendering.guard.ts
- src/app/pages/loading/loading-page.module.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
If the user is on a checkout page and refreshes the browser (F5) he sees the header twice for a short time (due to an hydration issue)
The header is shown on once.
[ ] Yes
[x] No
[AB#100906](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/100906)
> fix: double header display in checkout

- projects/organization-management/src/app/services/cost-centers/cost-centers.service.spec.ts
- projects/organization-management/src/app/services/cost-centers/cost-centers.service.ts
- src/app/core/models/cost-center/cost-center.mapper.spec.ts
- src/app/core/models/cost-center/cost-center.mapper.ts
- src/app/core/models/cost-center/cost-center.model.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/pages/account-order-history/account-order-filters/account-order-filters.component.ts
- src/app/shared/components/order/order-list/order-list.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
1. On cost center list/widget there is a get REST request for every single cost center to provide the list data. This is really slow if a project has many cost centers and leads to performance issues on the cost center list page and the myAccount overview page (cost center widget).
2. On the cost center details page the related orders and assigned buyers are not shown.
2. The cost center data that are needed for the list are read from the attributes costcenters get REST response, there is no need to …
> fix: cost center loading and display

- .eslintrc.json
- src/app/pages/product/product-images/product-images.component.ts
[x] Bugfix
[ ] Feature
[x] Other: eslint change
On a production-like deployed PWA (with SSR) the product image is shortly shown twice on product detail page. This is due to an hydration issue regarding the swiper (image slider).
The hydration is switched off for the product images component. This leads also to an improved performance (lighthouse score) for mobile devices.
The eslint rule '@angular-eslint/no-host-metadata-property' has been switched off because it will be deprecated with Angular 18.
[ ] Yes
[x] No …
> fix: display product image twice on PDP

- src/app/pages/product/product-images/product-images.component.html
- src/app/shared/components/product/product-image/product-image.component.html
- src/app/shared/components/product/product-image/product-image.component.ts
* because it is the LCP on this page
[ ] Bugfix
[ ] Feature
[x] Other: Performance improvements
The main product image on PDP is lazily loaded. On mobile devices and also sometimes on desktop this image is the LCP of the product detail page and for performance reasons it should be loaded as fast as possible.
The main product image on PDP is loaded eagerly. Especially on mobile devices the LCP will decrease significantly.
[ ] Yes
[x] No
[AB#100535](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/1005 …
> perf: load the main product image eagerly on PDP

- nginx/features/cache.conf
[x] Bugfix
If the connected ICM goes in maintenance mode the PWA is supposed to return the maintenance page with status code 503.
This works fine if the SSR process is directly answering the request.
In production like systems an active NGINX caching is usually enabled to increase the rendering performance. But with an active cache it is likely that the result is fetched from the cache and with this it is likely a previous rendering with status code 200 is returned at least as long as the NGINX cache setting `CACHE_DURATION_NGINX_OK` lasts.
Unfortunately the current NGINX cache configuration returned responses with status 200 even much longer than the `CACHE_DURATION_NGINX_OK` configurations since it is configured to return stale/expired cache results if the SSR process returns 503 status …
> fix: SSR rendered pages with status code 404 or 503 should be returned

- .github/scripts/docker-compose.py
- .github/scripts/requirements.txt
[ ] Bugfix
[ ] Feature
[ X ] CI-related changes
[ ] Other: 
Demoserver Up workflow is broken as `PyYAML==5.4.1` cannot be installed on Python 3.12.
See [PyYAML #724](https://github.com/yaml/pyyaml/issues/724)
Demoserver Up workflow is working again.
[ ] Yes
[X] No
I rewritten part of the script to not be dependent on the discontinued python package `easyargs`
> ci: fix demoserver workflow

- docker-compose.yml
- docs/guides/cookie-consent.md
- src/app/core/identity-provider/auth0.identity-provider.ts
- src/app/core/identity-provider/co-browse.identity-provider.spec.ts
- src/app/core/identity-provider/co-browse.identity-provider.ts
- src/app/core/identity-provider/icm.identity-provider.spec.ts
- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.spec.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
- src/app/extensions/punchout/services/punchout/punchout.service.spec.ts
- src/app/extensions/punchout/services/punchout/punchout.service.ts
- src/app/extensions/punchout/store/punchout-functions/punchout-functions.effects.ts
- src/environments/environment.model.ts
[x] Feature
Customer tested OCI punchout from a punchout system. Login to the webshop was successful but returning to the punchout system from the basket with the HOOK_URL failed.
Reason: The integrated browser within the punchout client is not able to set cookies. But the HOOK_URL is saved as a cookie within the PWA.
To avoid problems with OCI and cXML punchout clients that are not able to set cookies, we now save the punchout information in session storage.
Additionally, errors regarding missing punchout information that is supposed to be available in the session storage (`punchout_SID, punchout_ReturnURL, punchout_HookURL`) are now presented in the UI on basket transfer and in the error log.
[x] No …
> feat: save punchout information in session storage instead of in cookies

- docs/guides/migrations.md
- src/app/core/facades/app.facade.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/store/core/configuration/configuration.selectors.spec.ts
- src/app/core/store/core/configuration/configuration.selectors.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.spec.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
- src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.html
- src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.spec.ts
- src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.ts
- src/app/extensions/punchout/services/punchout/punchout.service.ts
- src/environments/environment.model.ts
[x] Feature
In B2B my account under the Punchout > OCI tab there is a Punchout configuration URL pointing to the PWA, this needs to be changed to the ICM pipeline ViewOCICatalogPWA-Start.
The OCI Punchout URL has been changed to be a pipeline endpoint.
A new URL configuration selector has been added to generate a pipeline URL.
[x] No
The new OCI Punchout URL is available as of ICM versions 7.10.41.3, 11.11.1 or 12.2.0.
We need to wait with merging at least until ICM 12.2.0 is released.
[AB#98435](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/98435)
> feat: change OCI punchout URL to ICM Pipeline

- .github/workflows/azure-devops-issue-sync.yml
- .github/workflows/azure-devops-pr-sync.yml
- src/app/extensions/punchout/services/punchout/punchout.service.ts
[x] Bugfix
After adding error messages in the UI regarding missing punchout information for the Hook URL or Return URL false error messages popped up that where not supposed to be even relevant.
Not using the `iif` operator prevents the false evaluation and false error messages.
[x] No
The second commit fixes the ADO sync workflows.
[AB#103134](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/103134)
> fix: remove evaluation of both punchout type transfers to prevent false error messages (#1737)

- .github/workflows/integration.yml
[ ] Bugfix
[ ] Feature
[ ] Other: 
The github integration pipeline failed with the following error message:
'This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`
We use the v4 versiom fpr the github actions upload-artifact and download-artifact.
[ ] Yes
[x] No
[AB#103177](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/103177)
> chore: use v4 of upload and download github actions

- docs/guides/migrations.md
- e2e/cypress/e2e/pages/meta-data.module.ts
- e2e/cypress/e2e/specs/system/seo-product-detail-page.b2c.e2e-spec.ts
- src/app/core/services/api/api.service.spec.ts
- src/app/core/services/api/api.service.ts
- src/app/core/services/payment/payment.service.spec.ts
- src/app/core/services/payment/payment.service.ts
- src/app/extensions/punchout/services/punchout/punchout.service.spec.ts
- src/app/extensions/punchout/services/punchout/punchout.service.ts
**Wait for the GA release of ICM 12.2.1 before this PR can be merged**
[ ] Bugfix
[ ] Feature
[ ] Other: 
Options calls are used to fetch the oci punchout configurations as well as the customer payment methods. This is not the way to go anymore and can cause CORS issues if the ICM web adapter is not configured properly.
Alternative 'get' requests are used to fetch the data mentioned above.
[ ] Yes
[x] No
Required ICM versions:
11.10.0 and above to fetch the customer payment methods
12.2.1 and above to fetch the oci punchout configuration
> refactor: replace options calls by appropriate get requests

- src/app/core/standalone/component/suggest/advanced-search-box/advanced-search-box.component.html
- src/app/core/standalone/component/suggest/advanced-search-box/advanced-search-box.component.spec.ts
- src/app/core/standalone/component/suggest/advanced-search-box/advanced-search-box.component.ts
- src/app/core/standalone/component/suggest/simple-search-box/simple-search-box.component.html
- src/app/core/standalone/component/suggest/simple-search-box/simple-search-box.component.spec.ts
- src/app/core/store/customer/customer-store.spec.ts
- src/app/shell/header/header-default/__snapshots__/header-default.component.spec.ts.snap
- src/app/shell/header/header-default/header-default.component.html
- src/app/shell/header/header-default/header-default.component.spec.ts
- src/app/shell/header/header-default/header-default.component.ts
- src/styles/components/header/header-sticky.scss
- src/styles/components/header/header.scss
- src/styles/components/header/search-container.scss
- src/styles/pages/errorpage/errorpage.scss
[x] Feature
Solr is used for the suggest only.
Suggest terms are shown using Sparque in the header suggest. The PR includes the first changes for the new visual design and interaction:
- apply new basic styling for both Solr and Sparque search box in the header and main content (no search result page, error page)
- apply Sparque specific suggest IAD to the header suggest search box 
- show / hide suggest (focus handling)
- scroll inside suggest layer and outside suggest (page)
- responsive behavior
- sticky header behavior
- gray background 
- move "Quick Order" to top header 
[x] No
> feat: add Sparque (advanced) suggest IAD and VD

- .github/workflows/integration.yml
- src/app/core/services/basket-items/basket-items.service.spec.ts
- src/app/core/services/basket-items/basket-items.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The common shipping method is send within the POST /basket/:id/items request every time. 
This is necessary to avoid the creation of multiple buckets if the ICM shipping preference `multipleShipmentsSupported` is set to true. 
However, if the ICM shipping preference `multipleShipmentsSupported` is set to false this causes a 422 response from ICM.
The PWA uses the configuration preference `multipleShipmentsSupported` to distinct between both usecases.
The commonShippingMethod is only send if `multipleShipmentsSupported` is …
> fix: don't send shipping method in POST items request when ICM runs in single-shipment-mode

- .eslintrc.json
- src/app/extensions/compare/shared/product-add-to-compare/product-add-to-compare.component.html
- src/app/extensions/quoting/shared/basket-add-to-quote/basket-add-to-quote.component.html
- src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.html
- src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.spec.ts
- src/app/pages/account-order-history/account-order-history-page.component.html
- src/app/pages/basket/shopping-basket-payment/shopping-basket-payment.component.html
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.html
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.spec.ts
- src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.html
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.html
- src/app/shared/components/common/in-place-edit/in-place-edit.component.html
- src/app/shared/components/common/in-place-edit/in-place-edit.component.spec.ts
- src/app/shared/components/filter/filter-dropdown/filter-dropdown.component.html
- src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.html
- src/app/shared/components/product/product-variation-select-enhanced/product-variation-select-enhanced.component.html
- src/app/shared/components/product/product-variation-select-enhanced/product-variation-select-enhanced.component.spec.ts
- src/app/shell/header/language-switch/language-switch.component.html
- src/styles/components/header/language-switch.scss
[ ] Bugfix
[ ] Feature
[x] Other: add eslint rule @angular-eslint/template/button-has-type
If buttons don't have a type property most browsers use the button type 'submit' as default. It may happen the button type is accidentally not set and a unintentional submit will be triggered.
The eslint rule @angular-eslint/template/button-has-type is added as warning to avoid issues mentioned above. All missing types for buttons have been added.
[X] No
[AB#104009](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/e …
> chore: add eslint rule to secure button types

- src/app/pages/checkout-payment/payment-payone-creditcard/payment-payone-creditcard.component.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
The current implementation uses an `eval()` expression to resolve the Payone Client API object for localization. That's unsafe.
The Payone connector will be updated to provide a simplified access to this object in the Payone API using an attributed named `languageCode`. The fallback uses the old response attribute `language` and extracts the locale code from it without using `eval()` anymore. There are no visual changes. 
- prepare use of adapted API for hosted payment page configuration of Payone Hosted Payment Page (Client …
> refactor: access to the Payone language object

- docs/guides/sparque-integration.md
- e2e/cypress/e2e/specs/filter/filter-search-results.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/shopping/search-box.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/shopping/search-products.b2c.e2e-spec.ts
- src/app/core/facades/shopping.facade.ts
- src/app/core/models/sparque/sparque-config.model.ts
- src/app/core/services/sparque-api/sparque-api.service.spec.ts
- src/app/core/services/sparque-api/sparque-api.service.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.html
- src/app/core/standalone/component/suggest/search-box/search-box.component.spec.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.ts
- src/app/core/standalone/component/suggest/suggest-brands-tile/suggest-brands-tile.component.spec.ts
- src/app/core/standalone/component/suggest/suggest-categories-tile/suggest-categories-tile.component.spec.ts
- src/app/core/standalone/component/suggest/suggest-keywords-tile/suggest-keywords-tile.component.spec.ts
- src/app/core/standalone/component/suggest/suggest-products-tile/suggest-products-tile.component.spec.ts
- src/app/core/standalone/component/suggest/suggest-search-terms-tile/suggest-search-terms-tile.component.html
- src/app/core/standalone/component/suggest/suggest-search-terms-tile/suggest-search-terms-tile.component.spec.ts
- src/environments/environment.b2b.ts
- src/styles/components/header/search-container.scss
[x] Bugfix
[x] Feature
* feat: add the suggested term value to the input field when selecting the term inside the suggest
* feat: update Sparque config naming, remove demo config from environment file
* doc: update Sparque documentation
* test: add Jest and update Cypress tests
* refactor: focus and tab handling to get it working on touch devices
* refactor: general ESC handling, better naming, expand when focus is on buttons too
* refactor: always check for changes in input field when searching and trigger (cached) suggest request
* refactor: better name for minimum characters count method
* fix: prevent empty suggest layer on mobile if there are neither results nor recent terms
* fix: use available …
> feat: Sparque suggest focus handling, config

- src/app/core/standalone/component/suggest/search-box/search-box.component.html
- src/styles/components/header/search-container.scss
[x] Bugfix
When the search input has focus and user clicks on backdrop layer, the suggest does not de-focus.
When the search input has focus and user clicks on backdrop layer, the suggest receives de-focus.
[x] No
> fix: backdrop layer de-focus

- docs/concepts/configuration.md
- docs/guides/migrations.md
- src/app/core/store/core/viewconf/viewconf.effects.ts
- src/app/core/store/core/viewconf/viewconf.integration.spec.ts
- src/environments/environment.model.ts
[X] Feature
The sticky header is always active and could not be turned off.
The sticky header can be turned on and off via the feature toggle `stickyHeader`.
The sticky header is enabled by default.
[X] No
[AB#104896](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/104896)
> feat(accessibility): sticky header feature toggle

- docs/check-dead-links.mjs
[x] Bugfix
Some websites have to be manually excluded from the Docs > "Check Dead Links for Changed Files"-action because the requested website would throw a 403 status code, even if the website is reachable.
Adding a request header with a user-agent to the request makes the request look more like a real browser request, and is therefor less likely to be blocked. This also reduces the number of websites that have to be manually blocked.
The intershop and azure URLs are excluded because they are internal links.
The GitHub URLs are excluded because there are way too many in the files (~3500) and mostly just reference commits, 3rd party licenses and packages.
[x] No
[AB#104907](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/104907)
> docs: fix dead link detection

- .prettierignore
- docs/check-dead-links.mjs
- docs/guides/migrations.md
- src/app/core/utils/script-loader/script-loader.service.ts
- src/app/extensions/copilot/shared/copilot/copilot.component.ts
- src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.spec.ts
- src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.ts
Upgrade Cybersource Credit Card integration to Microform v2. Microform v1 will reach end of life by July 1, 2025.
More details can be found in the pages of [Cybersource Support center](https://support.visaacceptance.com/knowledgebase/knowledgearticle/?code=KA-07550).
[ ] Bugfix
[x] Feature
[ ] Other: 
[x] Yes
[ ] No
The signature of the `ScriptLoader`'s `load`function was changed.
The used Microform v1 reaches end of life soon and was removed completely.
The integration requires the Cybersource Service connector 2 or higher for ICM. …
> feat: add support for Cybersource Microform v2

- src/app/extensions/seo/store/seo/seo.effects.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The following errors are thrown in case the search result page is reloaded in a language other than the default language: 
- `missing translation in en_US: seo.applicationName`
- `missing translation in en_US: seo.defaults.description`
Furthermore, the text for these keys is not translated.
- start PWA with `ng s` or in Docker using `docker compose up --build`
- open the homepage with default language en_US
- search for something, e.g. *: error does not occur
- switch to French in the header using the …
> fix: missing translation on search result page

- src/app/shell/header/login-status/login-status.component.ts
[x] Bugfix
Because of the expanding search box for sparque, the quickorder link was moved to the top of the header next to the compare link. This causes an overlap of the quickorder link and the language switch button when the user is logged in on tablet view (992px-768px).
VD Decision: The name is hidden on tablet view, only the account icon is displayed. This prevents an overlap, no matter how long the name is.
[x] No
> fix: hide account name in header on tablet view to prevent overlap with quickorder link

- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.html
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.scss
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.spec.ts
- src/styles/components/header/main-navigation.scss
[x] Bugfix
[x] Feature
When components are assigned to the header navigation include, they wrap instead of being positioned next to each other in the Design View. Moreover, the action bar (for editing) of some components cannot be reached.
Components added to the header navigation include are displayed in a row by default in the Design View, and the action bar of each component is reachable. Additionally, the whole action bar can be clicked to trigger the edit action.
[x] No
[AB#106245](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/106245)
> fix: item positioning in header navigation (design view)

- projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.html
- projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.spec.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
When the buyer and cost center manager are the same individual, the name appears twice in the approver field on the requisition detail page.
Issue Number: Closes #1664
The approver name is only showing once in this case.
[ ] Yes
[x] No
[AB#106591](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/106591)
> fix: same approver name is displayed twice on requisition detail page

- docs/guides/migrations.md
- docs/guides/nginx-startup.md
- nginx/Dockerfile
Currently the NGINX docker image builds fail because of failing downloads from luarocks (see https://github.com/luarocks/luarocks/issues/1797).
Since we are only downloading the `lua-resty-redis-connector` from luarocks this part can be disabled for now since the shared Redis cache integration is not actively used yet in any project.
Not installing the `lua-resty-redis-connector` from luarocks for now to prevent the install problems.
[x] Yes
This change completely disables the possibility to connect to Redis for a shared NGINX pod cache.
Since this feature is not actively used yet in any project, disabling it should not be a problem for now.
[AB#107374](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/107374)
> fix: disable luarocks `lua-resty-redis-connector` installation

- src/styles/components/carousel/carousel.scss
- src/styles/global/global.scss
[x] Other: Accessibility Improvements
The keyboard focus on the ngbCarousel (b2c homepage teaser carousel) is hidden via CSS.
The keyboard focus also is not visible on the image links inside the carousel slides.
Issue Number: Closes #1826
Changed the CSS so that the keyboard focus is visible of the ngbCarousel content inside the carousel.
[x] No
[AB#107649](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/107649)
> fix(accessibility): tab focus outline for carousel (#1826, #1843)

- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
[x] Bugfix
When adding a payment instrument via the payment instrument form on the checkout payment page, after submitting a valid form there is an error displayed, stating that the same payment instrument can't be added because it already exists. The payment method is still successfully created.
The behavior only appears on forms that use the <ish-payment-parameter-form> component.
This can visually confuse users, but especially users that rely on a screen reader, because the error message is read out as important information, making the user think that adding the payment method was not successful.
Issue Number: Closes #1850
Removed the redundant `(submitPayment)="submitParameterForm()"` on the `<ish-payment-parameter-form>`, since the function is already called in the form submit in the …
> fix: checkout "add payment instrument" submit is called twice (#1850, #1852)

- src/app/pages/category/category-categories/category-categories.component.html
- src/app/pages/category/category-products/category-products.component.html
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[x] Other: Accessibility Improvements
The category navigation is used to navigate between different pages on the website, but is not wrapped inside a `<nav>` landmark element.
Issue Number: Closes #1834
The category navigation is wrapped inside a `<nav>`-element to make it easier to find and identify this section as a navigation landmark for the website.
[x] No
[AB#107931](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/107931)
> feat(accessibility): wrap category navigation into `<nav>` element (#1834, #1853)

- src/app/pages/category/category-navigation/category-navigation.component.html
- src/app/pages/category/category-navigation/category-navigation.component.spec.ts
- src/app/shared/components/filter/filter-swatch-images/__snapshots__/filter-swatch-images.component.spec.ts.snap
- src/app/shared/components/filter/filter-swatch-images/filter-swatch-images.component.html
- src/app/shared/components/filter/filter-text/filter-text.component.html
- src/app/shared/components/filter/filter-text/filter-text.component.spec.ts
[x] Other: Accessibility Improvements
Assistive technology cannot detect which categories or filters are selected (category & product list pages).
Issue Number: Closes #1832
Active categories and filters are marked with `aria-current="true"`, so assistive technology can detect which categories/filters are currently selected.
[x] No
[AB#107979](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/107979)
> feat(accessibility): indicate which categories/filters are selected (#1832, #1858)

- package-lock.json
- package.json
>  [!IMPORTANT]
> #1859 adds the necessary dev-dependency for the plugin `@babel/plugin-proposal-decorators` that is a prerequisite for the `babel.config.js` that is added in #1857
>
> #1857 adds the `babel.config.js` to enable the `-u` parameter for tests with Angular `@Component`/`@Input`/`@Output` decorators
[x] Other: jest test fix
The `babel.config.js` that was added in #1857 is not enough to enable the `-u` parameter for running tests that have Angular `@Component`/`@Input`/`@Output` decorators.
Running such a test with `-u` throws the error:
> Cannot find module '@babel/plugin-proposal-decorators'
The missing plugin `@babel/plugin-proposal-decorators` is added to the `"devDependencies"` in the `package.json`.
This in combination with the `babel.config.js` from #1857 enables to run …
> test: add `@babel/plugin-proposal-decorators` to dev dependencies (#1857, #1859)

- src/app/pages/account/account-page.component.html
[x] Bugfix
[x] Other: Accessibility Improvement
The target of the `<skip-content-link>` on the "My Account" navigation is set to the main content of the page, which causes unnecessary scrolling on longer pages, because the skip-link scrolls to the center of the target.
The `<skip-content-link>` on the "My Account" navigation focuses on the breadcrumbs to prevent unnecessary scrolling.
[x] No
Related to #1824 and #1838
[AB#108360](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/108360)
> fix(accessibility): use skip content link component (#1824, #1838)

- projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.html
- src/app/extensions/punchout/pages/account-punchout-configuration/oci-configuration-form/oci-configuration-form.component.html
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.html
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.html
- src/app/extensions/wishlists/pages/account-wishlist/account-wishlist-page.component.html
- src/app/pages/account-order-history/account-order-filters/account-order-filters.component.html
- src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.html
- src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.html
- src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.spec.ts
- src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.html
- src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.spec.ts
- src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.html
- src/app/shared/components/basket/clear-basket/clear-basket.component.html
- src/app/shared/components/filter/filter-collapsible/filter-collapsible.component.html
- src/app/shared/components/filter/filter-collapsible/filter-collapsible.component.spec.ts
- src/app/shared/components/filter/filter-dropdown/filter-dropdown.component.html
- src/app/shared/components/filter/filter-navigation-badges/filter-navigation-badges.component.html
- src/app/shared/components/filter/filter-navigation-badges/filter-navigation-badges.component.spec.ts
- src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.html
- src/app/shared/formly/components/field-tooltip/field-tooltip.component.html
- src/styles/global/buttons.scss
- src/styles/global/global.scss
- src/styles/pages/category/filter-panel.scss
- src/styles/pages/checkout/shopping-cart.scss
[ ] Bugfix
[x] Feature
[ ] Other: 
Tabs do not underline when hovered.
The “Remove items” button for the quoting basket was part of the h2 and therefore not formatted correctly.
Buttons with text and an icon were not underlined and were separated by spaces.
Closes: #1790
Box-shadow below the tab when hovered similar to when active 
The position of the “Remove items” button has been corrected and aligned with the “Clear cart” button.
All buttons with text and an icon are now underlined when hovered and the text and icon are separated by a padding. The class …
> fix: link styling

- src/app/pages/account-order-history/account-order-filters/account-order-filters.component.ts
[x] Bugfix
Order search filters are opening automatically after triggering a search on order history page, even none filters are applied. 
Problem:
After introducing the buyer filter, the logic for handling the expansion of the filter panel did not account for this additional filter. There are some parameters that are always being applied with a default value and that result in  unnecessary empty url search parameters.
Order history filters are now only opening automatically if the filter toggle link has been clicked or if the order search contains a filter other than the order number.
[ ] Yes
[x] No
[AB#108218](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/108218)
> fix: Order history filters open unintended

- src/app/core/facades/cms.facade.ts
- src/app/core/store/content/content-store.module.ts
- src/app/core/store/content/content-store.ts
- src/app/core/store/content/design-view/design-view.actions.ts
- src/app/core/store/content/design-view/design-view.reducer.ts
- src/app/core/store/content/design-view/design-view.selectors.spec.ts
- src/app/core/store/content/design-view/design-view.selectors.ts
- src/app/core/store/content/design-view/index.ts
- src/app/core/utils/design-view/design-view.service.ts
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.html
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.scss
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.spec.ts
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
Selecting a leaf pagelet component in the design view page structure tree is not supported.
If a user selects a leaf pagelet component in the design view it is highlighted in the pwa. After closing the page structure panel the pagelet component is not highlighted any more.
The interaction between the pwa and the design view is still incomplete, e.g. if the user starts to edit a pagelet component the previously selected component in the design view page structure tree as well as the selected component in …
> feat: select a pagelet triggered by design view

- src/app/core/facades/shopping.facade.ts
After dispatching a search request a suggestions request is unnecessarily executed a second time!
Fixes: #<issue-number>
_If this PR contains a breaking change, please describe the impact and migration path for existing applications below._
- [x ] No
---
[AB#109518](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/109518)
> fix: prevent unnecessary multiple dipatching of suggestions action

- src/app/shared/components/search/suggest-categories/suggest-categories.component.spec.ts
- src/app/shared/components/search/suggest-products-tile/suggest-products-tile.component.spec.ts
- src/app/shared/components/search/suggest-products/suggest-products.component.spec.ts
The Jest tests for the component suggest-products.component.html were missing and needed to be added. 
---
[x] Feature
---
---
_If this PR contains a breaking change, please describe the impact and migration path for existing applications below._
[x] No
---
[AB#109373](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/109373)
> test: add tests for Sparque suggest products component
