- e2e/package-lock.json
- schematics/package-lock.json
- tslint-rules/package-lock.json
fix sub project vulnerabilities in all sub project with `npm audit fix` after GitHub automation dependabot found vulnerabilities in the e2e sub project
> fix: update dependencies with vulnerabilities in sub projects

- .stylelintrc.json
- .vscode/settings.json
- package-lock.json
- package.json
- tslint.json
chore: improve prettier + linter integration and fix vscode settings for prettier with tslint integration
> chore: prettier vscode settings

- src/app/core/models/search-parameter/search-parameter.mapper.ts
- src/app/pages/compare/components/product-compare-list/product-compare-list.component.ts
- src/app/pages/contact/components/contact-form/contact-form.component.ts
- src/app/shared/cms/components/cms-video/cms-video.component.spec.ts
- src/app/shared/cms/components/cms-video/cms-video.component.ts
Sebastian G and I went through the Sonar reports – it was not much that was really worth fixing.
> chore: fixes pointed out by Sonar

- src/app/pages/category/components/category-image/category-image.component.html
- src/app/shared/cms/components/cms-image/cms-image.component.html
- src/app/shared/cms/components/cms-image/cms-image.component.spec.ts
- src/app/shell/header/components/product-image/product-image.component.html
> fix: chromium defer-load: directive only on block-elements

- src/app/pages/basket/basket-page.container.html
- src/app/pages/basket/components/shopping-basket-empty/shopping-basket-empty.component.html
- src/app/pages/basket/components/shopping-basket-empty/shopping-basket-empty.component.spec.ts
- src/app/pages/basket/components/shopping-basket-empty/shopping-basket-empty.component.ts
Issue Number: (ISREST-954)
Error messages are shown on empty cart/basket.
> fix: error message on empty cart

- src/app/extensions/quoting/facades/quoting.facade.ts
- src/app/extensions/quoting/services/quote-request/quote-request.service.ts
- src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
- src/app/extensions/quoting/store/quote-request/quote-request.reducer.spec.ts
- src/app/extensions/quoting/store/quote-request/quote-request.reducer.ts
- src/app/extensions/quoting/store/quote-request/quote-request.selectors.spec.ts
- src/app/extensions/quoting/store/quote-request/quote-request.selectors.ts
- src/app/extensions/quoting/store/quote/quote.effects.ts
- src/app/extensions/quoting/store/quote/quote.reducer.spec.ts
- src/app/extensions/quoting/store/quote/quote.reducer.ts
- src/app/extensions/quoting/store/quote/quote.selectors.spec.ts
- src/app/extensions/quoting/store/quote/quote.selectors.ts
This is the starting point for the quoting refactoring.
First steps done:
> refactor: use ngrx/entity in quoting feature

- src/app/core/facades/checkout.facade.ts
- src/app/core/services/basket/basket.service.spec.ts
- src/app/core/services/basket/basket.service.ts
- src/app/core/store/checkout/basket/basket-promotion-code.effects.spec.ts
- src/app/core/store/checkout/basket/basket-promotion-code.effects.ts
- src/app/core/store/checkout/basket/basket.actions.ts
- src/app/core/store/checkout/basket/basket.reducer.spec.ts
- src/app/core/store/checkout/basket/basket.reducer.ts
- src/app/shared/components/basket/basket-promotion/basket-promotion.component.html
- src/app/shared/components/basket/basket-promotion/basket-promotion.component.spec.ts
- src/app/shared/components/promotion/promotion-remove/promotion-remove.component.html
- src/app/shared/components/promotion/promotion-remove/promotion-remove.component.spec.ts
- src/app/shared/components/promotion/promotion-remove/promotion-remove.component.ts
- src/app/shared/shared.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
- src/theme/global/promotions.scss
- Feature
Once added, a promotion code cannot be removed from the basket.
Promotion Codes can be removed from the basket
> feat: remove promotion code from basket

- src/app/core/store/locale/locale.effects.spec.ts
- src/app/core/store/locale/locale.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
> fix: ngx-meta translate on load is not working

- src/app/core/models/product/product.helper.spec.ts
- src/app/core/models/product/product.helper.ts
- src/app/pages/compare/product-compare-list/product-compare-list.component.html
- src/app/pages/compare/product-compare-list/product-compare-list.component.spec.ts
- src/app/pages/compare/product-compare-list/product-compare-list.component.ts
- tslint.json
\[ \] Bugfix
\[ \] Feature
\[ \] Code style update (formatting, local variables)
\[x\] Refactoring (no functional changes, no API changes)
\[ \] Build-related changes
\[ \] CI-related changes
\[ \] Documentation content changes
\[ \] application / infrastructure changes
\[ \] Other... Please describe:
- common methods for products are moved from product compare list component into product helper
- tests are added
\[ \] Yes
\[x\] No
> refactor: move methodes from product compare component to product helper

- src/app/pages/category/category-image/category-image.component.html
- src/app/shared/cms/components/cms-image-enhanced/cms-image-enhanced.component.html
- src/app/shared/cms/components/cms-image/cms-image.component.html
- src/app/shared/cms/components/cms-image/cms-image.component.spec.ts
- src/app/shared/cms/components/cms-video/cms-video.component.html
- src/app/shell/header/product-image/product-image.component.html
- src/theme/global/global.scss
Issue Number: N/A
defer-load works as expected
> fix: defer-load set min-height of container

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
[ ] Bugfix
[ ] Feature
[ ] application / infrastructure changes
[x] Other: Github workflow
Github templates are adapted to our needs. Confusing details are removed.
[ ] Yes
[x] No
> docs: update github templates

- src/app/pages/product/product-detail/product-detail.component.html
- src/app/shared/components/product/product-row/product-row.component.html
- src/theme/pages/category/product-list.scss
Issue Number: ISREST-947
master products does not show availability and shipping informations
eventually an api-issue, and should not fixed in the pwa?!?
> fix: masterproduct show availability and shipping

- e2e/cypress/integration/pages/shopping/product-detail.page.ts
- e2e/cypress/integration/specs/checkout/cart-variation-handling.b2c.e2e-spec.ts
- src/app/shared/components/product/product-variation-select/product-variation-select.component.html
- src/app/shared/components/product/product-variation-select/product-variation-select.component.ts
Issue Number: https://github.com/intershop/intershop-pwa/issues/74
no multiple html-ids
> prevent multiple html-ids in product-variation-select-component

- .gitignore
- dist/.gitignore
- package-lock.json
- package.json
- server.ts
> feat: seo support for robots.txt

- src/app/shared/components/product/product-quantity/product-quantity.component.html
- src/app/shared/components/product/product-quantity/product-quantity.component.spec.ts
- src/app/shared/components/product/product-quantity/product-quantity.component.ts
- src/app/shared/forms/components/counter/counter.component.html
- src/app/shared/forms/components/counter/counter.component.spec.ts
- src/app/shared/forms/components/counter/counter.component.ts
- src/app/shared/forms/forms.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
- src/jest-serializer/NgrxActionSerializer.js
\[ \] Bugfix
\[x\] Feature
\[ \] Code style update (formatting, local variables)
\[ \] Refactoring (no functional changes, no API changes)
\[ \] Build-related changes
\[ \] CI-related changes
\[ \] Documentation content changes
\[ \] application / infrastructure changes
\[ \] Other... Please describe:
Adds a third way of selecting quantities with a counter component.
\[ \] Yes
\[x\] No
> feat: counter quantity input component

- README.md
- docs/README.md
- docs/migrations.md
- docs/project-structure.md
- docs/state-management.md
- docs/state-management.svg
- Documentation content changes
> docs: documentation for pattern without containers

- .gitlab-ci.yml
[ ] Bugfix  
[ ] Feature  
[x] CI-related changes  
[ ] Other: 
Over-night corporate GitLab pipeline fails due to wrong reference to demo server branches.
References to demo server branches work again
[ ] Yes  
[x] No
> chore: repair gitlab pipeline

- docs/README.md
- docs/search-engine-optimization.md
[x] Documentation content changes  
Issue Number: N/A
New docs file for search engine optimizations 
[ ] Yes  
[x] No
> docs: documentation for search engine optimizations

- docs/exclude.properties
- docs/intershop_progressive_web_app.ditamap
- docs/project-structure.md
- docs/state-management.md
[ ] Bugfix  
[x] Feature  
[x] Documentation content changes  
[ ] Other: 
Added a DITA-Map so the generation can be transformed with Oxygen Webhelp.
Issue Number: 
[ ] Yes  
[x] No
> docs: add DITA-map for available documentation

- src/app/shared/shared.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/fr_FR.json
> chore: localization key fixes

- tsconfig.app.json
[x] Bugfix  
compodoc works as expected
[ ] Yes  
[x] No
> chore: repair compodoc generation

- src/app/shared/components/basket/line-item-list/line-item-list.component.html
[x] Bugfix  
Missing titles (product names) in line item list e.g. quote-detail-page
[ ] Yes  
[x] No
> fix: missing product names in quote items listing (#111)

- e2e/cypress/integration/specs/quoting/quote-display.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
- schematics/src/extension/files/__name@dasherize__/store/__name@dasherize__-store.__tsext__
- schematics/src/utils/registration.js
- schematics/src/utils/registration.ts
- src/app/extensions/quoting/store/quoting-store.ts
[ ] Bugfix  
[ ] Feature  
[x] Refactoring (no functional changes, no API changes)  
[ ] Other: 
[ ] Yes  
[x] No
> Prevent warning '@ngrx/store: The feature name "..." does not exist in the state'

- e2e/test-schematics.sh
- schematics/src/extension/factory_spec.ts
- schematics/src/extension/files/__name@dasherize__/facades/__name@dasherize__.facade.__tsext__
- schematics/src/store/factory.js
- schematics/src/store/factory.ts
- schematics/src/store/factory_spec.ts
[x] Bugfix  
[x] Feature  
[ ] Other: 
Closes #109 
[ ] Yes  
[x] No
> Schematics improvements

- e2e/cypress/integration/pages/shopping/quote-request.dialog.ts
- e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
[ ] Bugfix  
[ ] Feature  
[ ] Other: 
Issue Number: 
[ ] Yes  
[ ] No
> test: stabilize quote-handling cypress test

- e2e/cypress/integration/pages/account/quote-list.page.ts
- src/app/app.module.ts
- src/app/extensions/quoting/pages/quote-edit/quote-edit-page.module.ts
- src/app/extensions/quoting/pages/quote-list/quote-list/quote-list.component.ts
- src/app/extensions/quoting/pages/quote-request-edit/quote-request-edit-page.module.ts
- src/app/extensions/quoting/pages/quoting-routing.module.ts
- src/app/extensions/quoting/shared/account/quote-widget/quote-widget.component.html
- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.ts
- src/app/extensions/quoting/store/quote-request/quote-request.effects.spec.ts
- src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
- src/app/extensions/quoting/store/quote/quote.effects.spec.ts
- src/app/extensions/quoting/store/quote/quote.effects.ts
- src/app/pages/account/account-navigation/account-navigation.component.ts
- src/app/pages/account/account-page.module.ts
[x] Bugfix  
- Breadcrumb display dynamic quote-id on quote-detail-page
- quote account menu item is selected on everey "quotes" route
(part of issue ISREST-461)
[ ] Yes  
[x] No
> account menu & breadcrumb for quoting

- src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
[x] Bugfix  
Steps to Repeat:
Login inTRONICS Business SF
Search a product and click "Add to a quote request"
Click "Submit Quote Request"
Click on the quote number or on the "quotes" link (quotes1)
Actual Behavior: A "Page not found" error appears.
(Issue Number: ISREST-1008)
The quote number link  lead you to the quote request details page. The "quotes" link lead you to the quote list.
[ ] Yes  
[x] No
> Thank you for your order! - Quote Links are not working

- e2e/cypress/integration/pages/checkout/cart.page.ts
- e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
- src/app/core/models/http-error/__snapshots__/http-error.mapper.spec.ts.snap
- src/app/core/models/http-error/http-error.mapper.spec.ts
[x] Bugfix  
[ ] Feature  
[x] Application / infrastructure changes  
[ ] Other: 
ICM server response to error messages in cart changed from 7.10.16.6 to 7.10.17.10
[ ] Yes  
[n] No
> test: adapt test for 7.10.17.0 release

- .cz-config.js
- CONTRIBUTING.md
- package-lock.json
- package.json
[ ] Bugfix  
[ ] Feature  
[x] Build-related changes  
[ ] Other: 
introduce [commitizen](https://github.com/commitizen/cz-cli) and [commitlint](https://github.com/conventional-changelog/commitlint) using a shared custom config via [commitlint-config-cz](https://github.com/whizark/commitlint-config-cz)
[ ] Yes  
[x] No
> build: introduce commitizen and commitlint

- .gitlab-ci.yml
- Dockerfile
- angular.json
- dist/entrypoint.sh
- e2e/e2e-partition.sh
- e2e/package-lock.json
- e2e/package.json
- e2e/test-e2e.sh
- nginx/README.md
- nginx/channel.conf.tmpl
- nginx/entrypoint.sh
- package.json
- schematics/src/kubernetes-deployment/files/charts/pwa-nginx/templates/deployment.yaml
- schematics/src/kubernetes-deployment/files/charts/pwa-nginx/values.yaml
- src/app/core/store/configuration/configuration.effects.ts
- templates/docker-compose.yml
[ ] Bugfix  
[ ] Feature  
[x] Build-related changes  
[x] CI-related changes  
[ ] Other: 
- nginx can be run with default coniguration
- multi-channel domains are now configurable
- PWA docker build can be run with different configurations from angular.json
also included:
- minor tweaks for GitLab CI
[ ] Yes  
[x] No
> feat: nginx config adaption

- e2e/package-lock.json
- package-lock.json
- package.json
- schematics/package-lock.json
- tslint-rules/package-lock.json
bump acorn dependencies to 6.4.1 plus additional fix updates
> build(deps): update dependencies to fix vulnerabilities within acorn

- .gitlab-ci.yml
- package.json
- src/app/app.server.module.ts
- src/app/core/interceptors/universal-log.interceptor.ts
- src/app/core/services/categories/categories.service.spec.ts
- src/app/core/services/categories/categories.service.ts
- src/app/core/store/shopping/products/products.effects.ts
…egories tree call
[x] Other: Performance
[ ] Yes  
[x] No
> perf: use new parameter omitHasOnlineProducts for more performant category tree call

- src/app/core/models/line-item/line-item.interface.ts
- src/app/core/models/line-item/line-item.mapper.ts
- src/app/core/models/line-item/line-item.model.ts
- src/app/shared/components/basket/line-item-list/line-item-list.component.html
[ ] Bugfix  
[x] Feature  
[ ] Other: 
Issue Number: ISREST-608  
Item quantity of a quote is a fix value.
Steps to Repeat:
Create a quote request and submit it
Respond the quote in the BO
Open the quote detail page in "My Account"
Click "Add to Cart"
Item quantity of a quote is editable in the cart.
Single quote items can be deleted from cart.
Item quantity of a quote is a fix value.
If the user deletes one quote item from cart all other items of this quote are also be deleted.
[ ] Yes  
[x] No
this feature needs icm 7.10.17.0
> ISREST-608: added quantity fixed handling

- README.md
[ ] Bugfix  
[ ] Feature  
[x] Documentation content changes  
[ ] Other: 
Issue Number: 
[ ] Yes  
[x] No
Updated titles since KB sync uses the h1 headline for generating titles. With the previous title, the document's name in the KB would have been "Intershop Progressive Web App - Intershop Progressie Web App".
> chore: remove labels from root readme for Knowledge Base sync

- src/app/core/store/orders/orders.effects.spec.ts
- src/app/core/store/orders/orders.effects.ts
- src/app/pages/account-order-history/account-order-history-page.module.ts
- src/app/pages/account/account-page.module.ts
[x] Bugfix  
[x] Feature  
[x] Refactoring (no functional changes, no API changes)  
[ ] Other: 
Breadcrumb for order details display the order id.
Refactoring acount & orders routes.
(Issue Number: ISREST-461)
[ ] Yes  
[x] No
> refactor: routing & breadcrumb of account orders (history/detail)

- src/app/shell/header/language-switch/language-switch.component.html
- src/app/shell/header/language-switch/language-switch.component.spec.ts
- src/app/shell/header/language-switch/language-switch.component.ts
- src/app/shell/header/user-information-mobile/user-information-mobile.component.html
- src/styles/components/header/user-information-mobile.scss
[x] Bugfix  
[ ] Feature  
[ ] Other: 
In the user-information-mobile.component.html template the HTML structure uses the Bootstrap grid system in a wrong manner. The language switch can not be used for mobile devices.
The user-information-mobile component uses Bootstrap in a correct way. The language switch can be used also on mobile devices.
[ ] Yes  
[x] No
> fix: fix styling of user information box for mobile (#90)

- src/app/pages/product/product-links-carousel/product-links-carousel.component.html
- src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
- src/app/shared/components/product/product-item/product-item.component.ts
- src/app/shell/header/user-information-mobile/user-information-mobile.component.html
- src/styles/global/swiper.scss
- src/styles/pages/category/product-list.scss
collection of minor bug fixes
display swiper navigation buttons (fixed styling issue)
fix styling for product-row product items in carousels
add tille configuration options to the product link carousel
improve feature toggle positioning for user information component
> swiper carousel improvements

- e2e/cypress-ci-e2e.js
- e2e/cypress/integration/specs/account/edit-user-email.b2c.e2e-spec.ts
[x] Bugfix  
[x] CI-related changes  
[ ] Yes  
[x] No
> test: wrap cypress run in try to catch chrome connection issues

- .github/workflows/test.yml
- .gitlab-ci.yml
- e2e/.gitignore
- e2e/cypress-ci-e2e.js
- e2e/package-lock.json
- e2e/package.json
> test: correctly capture browser connection issues, removed workarounds

- src/app/extensions/quoting/models/quote-request/quote-request.interface.ts
- src/app/extensions/quoting/models/quote-request/quote-request.model.ts
- src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
[ ] Bugfix  
[x] Feature  
[ ] Other: 
Issue Number: ISREST-917
Show the proper alert info on the quote request detail page.  
Use the new attribute "submittedDate" of the quote request from REST call REST Call  "/customers/<customerID>/users/<userID>/quoterequests/<quoteRequestID>".
[ ] Yes  
[x] No
> feat: integrated quote request submittedDate

- .gitlab-ci.yml
- e2e/test-universal.sh
- nginx/Dockerfile
- nginx/channel.conf.tmpl
- nginx/device.conf
- nginx/nginx.conf
- src/app/core/configurations/configuration.meta.ts
- src/app/core/facades/app.facade.ts
- src/app/core/guards/login.guard.ts
- src/app/core/models/viewtype/viewtype.types.ts
- src/app/core/store/configuration/configuration.effects.spec.ts
- src/app/core/store/configuration/configuration.effects.ts
- src/app/core/store/configuration/configuration.integration.spec.ts
- src/app/core/store/configuration/configuration.reducer.ts
- src/app/core/store/configuration/configuration.selectors.spec.ts
- src/app/core/store/configuration/configuration.selectors.ts
- src/app/core/store/viewconf/viewconf.actions.ts
- src/app/core/store/viewconf/viewconf.effects.ts
- src/app/core/store/viewconf/viewconf.integration.spec.ts
- src/app/core/store/viewconf/viewconf.reducer.ts
- src/app/core/store/viewconf/viewconf.selectors.ts
- src/app/shell/header/header-default/__snapshots__/header-default.component.spec.ts.snap
- src/app/shell/header/header-default/header-default.component.html
- src/app/shell/header/header-default/header-default.component.spec.ts
- src/app/shell/header/header-default/header-default.component.ts
- src/environments/environment.model.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- templates/docker-compose.yml
[x] Feature  
SSR always serves a initial page response for mobile devices. This way some flickering is visible, when accessing the response with desktop browsers.
Issue Number:
Closes #171 
Device type is detected in nginx and forwarded to SSR, so an appropriate response can be rendered and individually cached.
[ ] Yes  
[x] No
Builds on top of #167
> nginx device type detection

- e2e/package-lock.json
- package-lock.json
- package.json
- schematics/package-lock.json
- tslint-rules/package-lock.json
update dependencies to fix vulnerabilities (especially the minimist warnings)
> build(deps): update dependencies to fix vulnerabilities

- e2e/cypress/integration/pages/checkout/cart.page.ts
- e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
- e2e/cypress/integration/specs/checkout/shopping-prices.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/checkout/shopping-prices.b2c.e2e-spec.ts
- src/app/core/facades/account.facade.ts
- src/app/core/models/price/price.pipe.spec.ts
- src/app/core/store/configuration/configuration.effects.spec.ts
- src/app/core/store/configuration/configuration.effects.ts
- src/app/core/store/configuration/configuration.reducer.ts
- src/app/core/store/configuration/configuration.selectors.spec.ts
- src/app/core/store/configuration/configuration.selectors.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/app/core/store/user/user.selectors.spec.ts
- src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.html
- src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.spec.ts
- src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.ts
- src/assets/i18n/en_US.json
[ ] Bugfix  
[ ] Feature  
[ ] Other: 
Issue Number: 
[ ] Yes  
[ ] No
> fix: repair pricing for SSR

- src/app/core/models/payment-method/payment-method.mapper.spec.ts
- src/app/core/models/payment-method/payment-method.mapper.ts
- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
- src/app/shared/forms-dynamic/components/input-dynamic/input-dynamic.component.html
- src/app/shared/forms-dynamic/components/select-dynamic/select-dynamic.component.html
- src/app/shared/forms-dynamic/forms-dynamic.spec.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
An error occurs on checkout payment page if the payment method Concardis Direct Debit is eligible.
Issue Number: Closes #238 
It occurs no error on checkout payment page if the payment method Concardis Direct Debit is eligible and the user can pay with this payment method.
[ ] Yes
[x] No
Is related to the Angular 9 upgrade
> fix: display concardis direct debit form on checkout payment page

- docs/README.md
- docs/guides/upgrading-pwa.md
> docs: guide for upgrading dependencies

- docs/guides/angular-component-development.md
> docs: replace dead link

- dist/healthcheck.js
[x] Bugfix
PWA container healthcheck does not properly work for https ICM so only unhealthy containers are reported.
It does!
[ ] Yes
[x] No
> fix: PWA container healthcheck now supports ICM https

- .github/workflows/windows.yml
- .prettierignore
- docs/guides/development.md
- package.json
- scripts/init-local-environment.js
[x] Other: Development helpers
- script `npm run clean` for cleaning unversioned files
- automagically create `environment.local.ts` if it does not exist
[ ] Yes
[x] No
> development helpers

- e2e/test-universal.sh
Universal tests are failed if server connection is unstable.
Retry requests.
[ ] Yes
[x] No
> build: automatically retry universal tests

- src/app/core/services/address/address.service.spec.ts
- src/app/core/services/address/address.service.ts
- src/app/core/services/api/api.service.spec.ts
- src/app/core/services/api/api.service.ts
- src/app/core/services/cms/cms.service.ts
- src/app/core/services/order/order.service.spec.ts
- src/app/core/services/payment/payment.service.spec.ts
- src/app/core/services/payment/payment.service.ts
- src/app/extensions/quoting/services/quote-request/quote-request.service.spec.ts
- src/app/extensions/quoting/services/quote-request/quote-request.service.ts
- src/app/extensions/quoting/services/quote/quote.service.spec.ts
- src/app/extensions/quoting/services/quote/quote.service.ts
- src/app/extensions/quoting/store/quoting-store.spec.ts
[x] Feature  
Issue Number:  Closes #192 
[x] Yes - resolveLinks was refactored
[ ] No
> feat: adapt cms.service to handle personalized requests

- docs/README.md
- docs/check-kb-labels.js
> chore: remove KB labels from documentation overview

- src/app/core/interceptors/auth.interceptor.spec.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/customer-store.spec.ts
- src/app/core/store/customer/orders/orders.actions.ts
- src/app/core/store/customer/orders/orders.effects.spec.ts
- src/app/core/store/customer/user/user.actions.ts
- src/app/core/store/customer/user/user.effects.spec.ts
- src/app/core/store/general/countries/countries.actions.ts
- src/app/core/store/general/regions/regions.actions.ts
- src/app/core/store/shopping/categories/categories.actions.ts
- src/app/core/store/shopping/categories/categories.effects.spec.ts
- src/app/core/store/shopping/compare/compare.actions.ts
- src/app/core/store/shopping/filter/filter.actions.ts
- src/app/core/store/shopping/product-listing/product-listing.actions.ts
- src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
- src/app/core/store/shopping/products/products.actions.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/store/shopping/recently/recently.actions.ts
- src/app/core/store/shopping/search/search.actions.ts
- src/app/core/store/shopping/search/search.effects.spec.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/app/extensions/order-templates/store/order-template/order-template.actions.ts
- src/app/extensions/quoting/store/quote-request/quote-request.actions.ts
- src/app/extensions/quoting/store/quote/quote.actions.ts
- src/app/extensions/sentry/store/sentry-config/sentry-config.actions.ts
- src/app/extensions/seo/store/seo/seo.actions.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.actions.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
> refactor: rename and correctly label action types

- projects/organization-management/src/app/facades/organization-management.facade.ts
- projects/organization-management/src/app/pages/organization-management-routing.module.ts
- projects/organization-management/src/app/pages/users-detail/users-detail-page.component.html
- projects/organization-management/src/app/pages/users-detail/users-detail-page.component.spec.ts
- projects/organization-management/src/app/pages/users-detail/users-detail-page.component.ts
- projects/organization-management/src/app/pages/users/users-page.component.html
- projects/organization-management/src/app/pages/users/users-page.component.spec.ts
- projects/organization-management/src/app/pages/users/users-page.component.ts
- projects/organization-management/src/app/services/users/users.service.spec.ts
- projects/organization-management/src/app/services/users/users.service.ts
- projects/organization-management/src/app/store/users/users.actions.ts
- projects/organization-management/src/app/store/users/users.effects.spec.ts
- projects/organization-management/src/app/store/users/users.effects.ts
- projects/organization-management/src/app/store/users/users.reducer.ts
- projects/organization-management/src/app/store/users/users.selectors.spec.ts
- projects/organization-management/src/app/store/users/users.selectors.ts
- src/app/core/models/customer/customer.interface.ts
- src/app/core/models/customer/customer.mapper.ts
- src/app/core/models/user/user.interface.ts
- src/app/core/models/user/user.mapper.ts
- src/app/core/models/user/user.model.ts
- src/app/pages/account/account-navigation/account-navigation.component.html
- src/app/pages/account/account-navigation/account-navigation.component.spec.ts
- src/app/pages/account/account-navigation/account-navigation.component.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[*] Feature
style improvements for detail & list page
> feat: user management - ui/ux improvements

- docs/README.md
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[x] No
> Added labels and adjusted title

- e2e/cypress/integration/pages/organizationmanagement/users-detail.page.ts
- e2e/cypress/integration/pages/organizationmanagement/users.page.ts
- e2e/cypress/integration/specs/organizationmanagement/user-management-browsing.b2b.e2e-spec.ts
[x] Bugfix
[ ] Feature
[ ] Other
There are e2e tests available for user list and user detail view of user management.
[ ] Yes
[x] No
> Fix: add e2e tests for user management list and detail view

- projects/organization-management/src/app.component.html
- projects/organization-management/src/app.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Simple styling is provided for user management as standalone app.
Issue Number: Closes #305 
[ ] Yes
[x] No
> fix: add styling for user management as standalone app

- projects/organization-management/src/app/facades/organization-management.facade.ts
- projects/organization-management/src/app/pages/users/users-page.component.html
- projects/organization-management/src/app/pages/users/users-page.component.spec.ts
- projects/organization-management/src/app/pages/users/users-page.component.ts
- projects/organization-management/src/app/services/users/users.service.spec.ts
- projects/organization-management/src/app/services/users/users.service.ts
- projects/organization-management/src/app/store/users/users.actions.ts
- projects/organization-management/src/app/store/users/users.effects.spec.ts
- projects/organization-management/src/app/store/users/users.effects.ts
- projects/organization-management/src/app/store/users/users.reducer.ts
[*] Feature
remove user functionality for b2b user management
> feat: user management - delete user

- src/app/core/facades/account.facade.ts
- src/app/core/store/customer/user/user.actions.ts
- src/app/core/store/customer/user/user.effects.spec.ts
- src/app/core/store/customer/user/user.effects.ts
Closes  #264
[x] Bugfix
Issue Number: Closes #264 
routing delayed into separate effect.
[ ] Yes
[x] No
> fix: delay routing after user profile edit

- .github/workflows/test.yml
- projects/organization-management/src/app/store/users/users.selectors.spec.ts
- schematics/src/store/files/__name@dasherize__/__name@dasherize__.selectors.spec.ts.template
- src/app/core/store/shopping/product-listing/product-listing.selectors.ts
> style: fix typo

- .github/workflows/demo-server-down.yml
- .github/workflows/demo-server.yml
- .github/workflows/docs.yml
- .github/workflows/test.yml
- .github/workflows/windows.yml
- Dockerfile
- angular.json
- nginx/channel.conf.tmpl
- schematics/customization/service-worker/index.js
- scripts/init-local-environment.js
[x] Feature
Demo Servers are deployed using Azure App Services:
- no nginx
- App Service Plan: Free (60 Minutes compute time / d)
- resource group created is torn down when PR is closed
- no demo servers for external pull requests (no secrets available for build)
[ ] Yes
[x] No
> feat: demo server for GitHub pull requests

- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.spec.ts
- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
[X] Bugfix
[ ] Feature
[ ] Other: 
In Concardis SEPA direct debit, BIC value is not getting saved to database.
After this fix BIC value will be saved to database.
[ ] Yes
[X] No
> fix: save bic for concardis direct debit payment method

- src/app/core/models/payment-instrument/payment-instrument.interface.ts
- src/app/core/models/payment-method/payment-method.mapper.ts
> feat: show account identifier attribute of payment instrument

- .github/workflows/demo-server-down.yml
- .github/workflows/demo-server.yml
Azure is used with dedicated service prinicipal.
[ ] Yes
[x] No
> build: use service principal for azure demo servers

- docs/guides/migrations.md
- src/app/core/store/content/content-store.module.ts
- src/app/core/store/core/core-store.module.ts
- src/app/core/store/shopping/shopping-store.module.ts
- src/app/core/utils/dev/ngrx-testing.ts
- src/app/extensions/quoting/store/quoting-store.module.ts
- src/app/extensions/wishlists/store/wishlists-store.module.ts
- tslint.json
BREAKING CHANGES:
removed deprecated exports concerning the NgRx testing refactorings introduced in version 0.21
removed deprecated exports concerning the NgRx testing refactorings introduced in version 0.21
[x] Yes
[ ] No
> refactor: remove deprecated exports

- src/app/extensions/tacton/pages/configure/configure-page.component.html
- src/app/extensions/tacton/pages/configure/configure-page.component.spec.ts
- src/app/extensions/tacton/pages/configure/tacton-bom/tacton-bom.component.html
- src/app/extensions/tacton/pages/configure/tacton-bom/tacton-bom.component.spec.ts
- src/app/extensions/tacton/pages/configure/tacton-parameter/tacton-parameter.component.html
- src/app/extensions/tacton/pages/configure/tacton-parameter/tacton-parameter.component.spec.ts
- src/app/extensions/tacton/pages/configure/tacton-selected-image/tacton-selected-image.component.html
- src/app/extensions/tacton/pages/configure/tacton-selected-image/tacton-selected-image.component.spec.ts
- src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.html
- src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.spec.ts
- src/app/extensions/tacton/shared/product/tacton-configure-product/tacton-configure-product.component.html
- src/app/extensions/tacton/shared/product/tacton-configure-product/tacton-configure-product.component.spec.ts
- src/assets/i18n/en_US.json
[x] Bugfix
[ ] Feature
[ ] Other: 
Texts for tacton extonsion are not localized.
Texts for tacton extonsion are not localized.
[ ] Yes
[x] No
> fix: tacton localization

- docs/README.md
- docs/check-dead-links.js
- docs/guides/tacton-product-configuration.md
> documentation for tacton integration

- docs/README.md
- docs/guides/icm-http-error-mapping.md
> docs: improve api error handling

- docs/guides/ssr-startup.md
- server.ts
[x] Feature
[x] Application / infrastructure changes
`PROXY_ICM` is essentially a boolean flag and rewrites ICM URL depending on incoming request using protocol and host.
`PROXY_ICM` can be set to URL replacing ICM location completely.
[ ] Yes
[x] No
> feat: enhance option to overwrite URL for ICM in express server

- docs/guides/sentry-error-monitoring.md
dead link.
link updated
[ ] Yes
[x] No
> docs: provide new link to sentry sensitive data

- src/app/core/guards/login.guard.ts
- src/app/pages/app-routing.module.ts
- src/app/pages/login/login-page.module.ts
- src/app/shell/shell.module.ts
- LoginGuard is provided in app-routing.module
- LoginGuard is used in lazy loaded page module
[ ] Yes
[x] No
> refactor: provide login guard handling in lazy module instead of app routing module

- src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-line-item/account-order-template-detail-line-item.component.html
- src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
- src/app/extensions/quoting/shared/quote-interactions/quote-interactions.component.html
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.html
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/shared/components/line-item/line-item-list/line-item-list.component.html
- src/styles/global/buttons.scss
- src/styles/global/tables.scss
- src/styles/pages/account/account.scss
- src/styles/pages/checkout/shopping-cart.scss
improved margins for button groups without direct button siblings, clean up of wrong used Bootstrap 'btn-group' usage
> fix: improved button groups styling and clean up

- projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.html
- projects/organization-management/src/app/models/b2b-role/b2b-role.interface.ts
- projects/organization-management/src/app/models/b2b-role/b2b-role.mapper.spec.ts
- projects/organization-management/src/app/models/b2b-role/b2b-role.mapper.ts
- projects/organization-management/src/app/models/b2b-role/b2b-role.model.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
On the b2b user creation/editing form the user role description is displayed.
[ ] Yes
[x] No
> feat: display user role description

- src/app/core/routing/category/category.route.spec.ts
- src/app/core/routing/category/category.route.ts
- src/app/core/routing/product/product.route.ts
[x] Bugfix
Issue Number: Closes #394
[ ] Yes
[x] No
> fix: replace parantheses in URL slugs

- .github/workflows/demo-server-down.yml
- .github/workflows/demo-server.yml
- .github/workflows/development.yml
- .github/workflows/docs.yml
- .github/workflows/integration.yml
- .github/workflows/windows.yml
- scripts/ci-test-no-changes.sh
- Changes to documentation only run Docs workflow
- ci-test-no-changes script replaced by `git diff --exit-code`
[ ] Yes
[x] No
> chore: CI tuning

- .github/pull_request_template.md
- .prettierignore
[x ] Code style update (formatting, local variables)
Update the prettier to not format font files (.woff2 and .eot)
[x] No
> update .prettierignore for font types

- src/app/core/store/customer/addresses/addresses.reducer.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
After the user has submitted a new address in the checkout the loading animation doesn't disappear.
After the user has submitted a new address in the checkout the loading animation disappears.
[ ] Yes
[x] No
> fix: remove loading animation after creating an address during checkout

- src/app/extensions/quoting/pages/quote-list/quote-list/quote-list.component.html
bugfix
quote list item padding is wrong
Issue Number: Closes #291
quote list item padding is consistent with other account tables
No
> fix: adjust quote list item padding

- src/app/core/store/core/core-store.module.ts
[x] Bugfix
#415 inconveniently deactivates language change for `ng serve`.
re-activate configuration meta reducer for development.
[ ] Yes
[x] No
> chore: re-activate configuration meta reducer for development

- e2e/cypress/integration/pages/shopping/product-detail.page.ts
- e2e/cypress/integration/specs/checkout/shopping-user.b2c.e2e-spec.ts
> test: cypress stabilization

- src/app/core/store/core/configuration/configuration.effects.spec.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/configuration/configuration.integration.spec.ts
- src/app/core/utils/theme/theme.service.ts
[x] Bugfix
#389 restricted setting of theme in header also for `ng serve --prod`
Fixed.
[ ] Yes
[x] No
> fix: repair limitation for theme apply to fix prod mode with webpack-dev-server

- docs/guides/customizations.md
> docs: customization for cypress tests

- docs/concepts/configuration.md
configuration documentation additions
> docs: improve configuration documentation e.g. with code examples

- .github/workflows/dead-code.yml
- .github/workflows/development.yml
- .github/workflows/docs.yml
- .github/workflows/integration.yml
- .github/workflows/updates.yml
- .github/workflows/windows.yml
- Dockerfile
- Dockerfile_reports
- docs/guides/getting-started.md
- docs/guides/migrations.md
- package-lock.json
- package.json
- templates/Dockerfile_dev
- tslint-rules/src/ishUsefulImportsRule.ts
update required/tested Node.js version to 14.15.0 LTS (including npm 6.14.8)
> chore: update required/tested Node.js version to 14.15.0 LTS (including npm 6.14.8)

- CHANGELOG.md
- docs/guides/migrations.md
Migration note was missing from #432
> docs: add migration note for new multi-channel format

- src/app/core/store/general/server-config/server-config.effects.ts
[x] Bugfix
When there is a redirect while doing SSR, the configurations call is triggered more than once.
For SSR the server configuration is only loaded once.
[ ] Yes
[x] No
> perf: run configurations call only once for SSR

- schematics/src/extension/schema.json
- schematics/src/model/schema.json
- schematics/src/page/schema.json
- schematics/src/utils/ts-morph.ts
> fix: repair schema build

- projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.spec.ts
- projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
On the b2b user list it is not to be seen whether the user is inactive or not.
On the b2b user list inactive users are marked as inactive.
[ ] Yes
[x] No
An ICM 7.10.25+ is needed for this functionality.
> fix: display the user's inactive status on the b2b user list

- .github/workflows/integration.yml
- src/app/core/identity-provider.module.ts
- src/app/core/identity-provider/auth0.identity-provider.ts
- src/app/core/identity-provider/identity-provider.factory.ts
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.html
- src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.spec.ts
- src/app/pages/login/login-page.component.html
- src/app/pages/login/login-page.component.spec.ts
- src/app/shared/components/login/auth0-signin/auth0-signin.component.html
- src/app/shared/components/login/auth0-signin/auth0-signin.component.spec.ts
- src/app/shared/components/login/auth0-signin/auth0-signin.component.ts
- src/app/shared/components/login/identity-provider-login/identity-provider-login.component.html
- src/app/shared/components/login/identity-provider-login/identity-provider-login.component.ts
- src/app/shared/components/login/login-modal/login-modal.component.html
- src/app/shared/components/login/login-modal/login-modal.component.spec.ts
- src/app/shared/shared.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
> chore: fixes for SSO with Auth0 for B2C 

- e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
- src/app/extensions/quoting/facades/quote-context.facade.ts
- src/app/extensions/quoting/services/quoting/quoting.service.spec.ts
- src/app/extensions/quoting/services/quoting/quoting.service.ts
- src/app/extensions/quoting/store/quoting/quoting.actions.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.ts
Follow-up to #367: create QuoteRequests from QuoteRequests via REST API
[ ] Yes
[x] No
> refactor: use API for creating quote request from quote request

- src/app/core/facades/checkout.facade.ts
- src/app/core/store/customer/basket/basket-validation.effects.spec.ts
- src/app/core/store/customer/basket/basket-validation.effects.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/core/store/customer/customer-store.spec.ts
- src/app/pages/basket/basket-page.component.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
The user has always step through all basket steps after he has entered checkout.
Issue Number: Closes #473
After the user has entered checkout the user is navigated to the first basket step, where data are missing. All other basket steps are skipped. If he jumps back he has to step through all remaining steps, nevertheless. 
[ ] Yes
[x] No
> feat: checkout - simple basket acceleration

- scripts/cleanup-testbed.ts
- src/app/core/configuration.module.ts
- src/app/core/configurations/injection-keys.ts
- src/app/core/services/products/products.service.spec.ts
- src/app/core/store/core/configuration/configuration.effects.spec.ts
- src/app/core/store/core/configuration/configuration.integration.spec.ts
- src/app/core/store/customer/customer-store.spec.ts
- src/app/core/store/shopping/filter/filter.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/store/shopping/search/search.effects.spec.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/app/core/utils/cookies/cookies.service.spec.ts
- src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.spec.ts
- src/app/pages/product/product-links/product-links.component.spec.ts
- src/app/shared/components/login/login-form/login-form.component.spec.ts
- src/app/shell/header/sub-category-navigation/sub-category-navigation.component.spec.ts
- tslint.json
InjectionTokens are initialized in configuration.module.
InjectionTokens use own factories for init.
Some providers in tests are no longer necessary.
[ ] Yes
[x] No
> refactor: injection token init

- package.json
- projects/organization-management/src/app/services/organization-management-breadcrumb/organization-management-breadcrumb.service.spec.ts
- projects/requisition-management/src/app/services/requisition-management-breadcrumb/requisition-management-breadcrumb.service.spec.ts
- src/app/core/routing/category/category.route.spec.ts
- src/app/core/routing/product/product.route.spec.ts
- src/app/core/services/api/api.service.spec.ts
- src/app/core/store/core/configuration/configuration.effects.spec.ts
- src/app/core/store/core/router/router.integration.spec.ts
- src/app/core/store/customer/orders/orders.effects.spec.ts
- src/app/core/store/customer/user/user.effects.spec.ts
- src/app/core/store/shopping/categories/categories.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/utils/cookies/cookies.service.spec.ts
- src/app/extensions/order-templates/store/order-template/order-template.effects.spec.ts
- src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
- `setTimeout` is mostly replaced with `fakeAsync` where apliccable.
- other `setTimeout` times reduced
- `test:watch` script runs sequentially
- revert updating snapshots for `check` script
[ ] Yes
[x] No
learnings from the Testing Workshop
> test: optimize testing with time

- src/app/pages/product/product-images/product-images.component.html
- src/app/pages/product/product-images/product-images.component.ts
[x] Bugfix
Issue Number: Closes #507
using NgbCarousel.select to set active slide
[ ] Yes
[x] No
> fix: use carousel select method to set active slide

- src/app/core/directives/not-role-toggle.directive.spec.ts
- src/app/core/directives/not-role-toggle.directive.ts
- src/app/core/facades/app.facade.ts
- src/app/core/models/authorization/authorization.interface.ts
- src/app/core/models/authorization/authorization.mapper.spec.ts
- src/app/core/models/authorization/authorization.mapper.ts
- src/app/core/models/authorization/authorization.model.ts
- src/app/core/role-toggle.module.ts
- src/app/core/store/core/error/error.actions.ts
- src/app/core/store/core/error/error.effects.ts
- src/app/core/store/core/error/error.reducer.ts
- src/app/core/store/customer/authorization/authorization.reducer.ts
- src/app/core/store/customer/authorization/authorization.selectors.spec.ts
- src/app/core/store/customer/authorization/authorization.selectors.ts
- src/app/core/utils/authorization-toggle/authorization-toggle.service.spec.ts
- src/app/core/utils/role-toggle/role-toggle.service.spec.ts
- src/app/core/utils/role-toggle/role-toggle.service.ts
- src/app/extensions/sentry/store/sentry-config/sentry-config.effects.ts
- src/app/pages/account/account-user-info/account-user-info.component.spec.ts
- src/app/pages/account/account-user-info/account-user-info.component.ts
- src/app/pages/error/error-page.component.html
- src/app/pages/error/error-page.component.ts
- src/app/pages/error/server-error/server-error.component.html
- src/app/pages/error/server-error/server-error.component.ts
- src/app/shared/shared.module.ts
- src/app/shell/shell.module.ts
prerequisites for punchout functionality:
* "not-has-role" directive
* role ids in authorization store
* triggering of business errors
> feat: punchout prerequisites

- docs/check-dead-links.js
- docs/concepts/state-management.md
- docs/guides/migrations.md
> docs: documentation and migration note for product contexts

- e2e/cypress/integration/framework/index.ts
- e2e/cypress/integration/pages/account/order-templates-details.page.ts
- e2e/cypress/integration/pages/account/wishlists-details.page.ts
- e2e/cypress/integration/pages/checkout/mini-cart.module.ts
- e2e/cypress/integration/pages/quickorder/quickorder.page.ts
- e2e/cypress/integration/pages/shopping/product-detail.page.ts
- e2e/cypress/integration/specs/quickorder/quickorder-handling.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/shopping/paging-product-list-search-page.b2c.e2e-spec.ts
- src/app/core/facades/checkout.facade.ts
- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/models/product/product.helper.ts
- src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
- src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.spec.ts
- src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.ts
- src/app/pages/product/retail-set-parts/retail-set-parts.component.spec.ts
- src/app/shell/header/mini-basket/mini-basket.component.ts
> test: cypress test stabilization

- .github/workflows/integration.yml
- angular.json
- package-lock.json
- package.json
- templates/production/data-testing-id-loader.js
- templates/production/webpack.production.js
> test: run cypress with ngrx runtime checks

- .dockerignore
- .github/workflows/demo-server.yml
- .github/workflows/development.yml
- .github/workflows/integration.yml
- .github/workflows/windows.yml
- Dockerfile
- docker-compose.yml
- docs/guides/development.md
- docs/guides/nginx-startup.md
[x] Bugfix
PWA docker build with production configuration broken. Caused by 82ad5810afcc5bb62a7a505c5818a1a054dd42ba
- repaired
- docker-compose.yml moved to root
- docker builds as part of CI
[ ] Yes
[x] No
> fix: pwa production docker build

- package.json
- src/setupJest.ts
- reduce jest load
- fail test if routes not defined or mocks not supplied
[ ] Yes
[x] No
> refactor: minor refactorings

- src/app/extensions/punchout/pages/punchout-account-routing.module.ts
- src/app/extensions/punchout/pages/punchout-routing.module.ts
- src/app/pages/account/account-page.module.ts
[x] Bugfix
Add route guard for 'punchout' routes depending on the feature toggle
[x] No
> fix: punchout improvements

- src/app/core/models/product-listing/product-listing.mapper.spec.ts
- src/app/core/models/product-listing/product-listing.mapper.ts
- src/app/core/models/product-listing/product-listing.model.ts
- src/app/core/services/filter/filter.service.spec.ts
- src/app/core/services/filter/filter.service.ts
- src/app/core/services/products/products.service.spec.ts
- src/app/core/services/products/products.service.ts
- src/app/core/store/shopping/filter/filter.effects.spec.ts
- src/app/core/store/shopping/filter/filter.effects.ts
- src/app/core/store/shopping/product-listing/product-listing.selectors.spec.ts
- src/app/core/store/shopping/product-listing/product-listing.selectors.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.html
- src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.spec.ts
- src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.ts
- src/app/shared/components/product/product-listing/product-listing.component.html
[x] Feature
Issue Number: Closes #534
ICM managed display names
[ ] Yes
[x] No
> feat: display ICM managed display names for sorting keys on listings

- .dockerignore
- .prettierignore
- Dockerfile
- Dockerfile_noSSR
- docker-compose.yml
- docs/concepts/deployment-angular.md
- nginx/channel.conf.tmpl
- templates/nginx.conf
[x] Feature
No Dockerfile for deployments without SSR
Dockerfile for Deployment without SSR
Simply applying https://github.com/intershop/intershop-pwa/blob/develop/docs/concepts/deployment-angular.md#simple-browser-side-rendering
[ ] Yes
[x] No
For this to work with Multi-Channel support, the `configurationMeta` reducer must be active on the client side, which it isn't currently by default:
https://github.com/intershop/intershop-pwa/blob/7b3d937090e00920996b7a0edec5619924dd6c07/src/app/core/store/core/core-store.module.ts#L36
> feat: deploy PWA without SSR

- docs/guides/cookie-consent.md
> chore: fix dead link

- docs/guides/nginx-startup.md
- nginx/channel.conf.tmpl
- src/app/core/configurations/configuration.meta.ts
[x] Feature
Issue Number: Closes #420
Multi-Channel support is also multi-ICM support 🎉 
[ ] Yes
[x] No
> feat: multi-channel with multi ICM support

- src/app/core/utils/default-error-handler.ts
- src/app/extensions/tacton/store/tacton-config/tacton-config.selectors.ts
- src/app/pages/account/account-user-info/account-user-info.component.ts
- tslint.json
- sentry is part of main bundle
- lazy is part of a lazy-loaded bundle
[ ] Yes
[x] No
> perf: move sentry to lazy loaded bundle by lazy invocation

- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
The formly refactoring removed the "checkbox" type which is still active in the concardis direct debit component.
The component now uses the new "ish-checkbox-field" type.
[ ] Yes
[x] No
> fix: use new checkbox type in directdebit

- .prettierignore
- docs/concepts/project-structure.md
- docs/guides/testing-jest.md
- src/app/core/facades/account.facade.spec.ts
- src/app/core/facades/shopping.facade.spec.ts
- src/app/core/models/price/price.helper.spec.ts
- src/app/core/services/cms/cms.service.spec.ts
- src/app/core/store/customer/addresses/addresses.selectors.ts
- src/app/core/store/customer/authorization/authorization.effects.spec.ts
- src/app/core/store/general/server-config/server-config.effects.spec.ts
- src/app/core/store/shopping/products/products.effects.spec.ts
- src/app/core/utils/dev/html-query-utils.ts
- src/app/core/utils/dev/ngrx-testing.ts
- src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
- src/app/extensions/tacton/services/tacton-self-service-api/tacton-self-service-api.service.spec.ts
- src/app/shared/components/recently/recently-viewed/recently-viewed.component.html
- src/app/shared/components/recently/recently-viewed/recently-viewed.component.spec.ts
- src/jest-serializer/NgrxActionSerializer.js
- tslint-rules/src/meaningfulNamingInTestsRule.ts
[x] Other: Testing Workshop
- documentation updated
- tests improved
- missing tests added
Testing external contributions 😉 
Please decide what to include
> chore: testing workshop input

- .github/workflows/azure-devops.yml
[ ] Bugfix
[ ] Feature
[ ] Other: 
We have to manually merge changes from github/develop into our Azure DevOps project
We trigger a Azure DevOps pipeline to do what we formerly did by hand
[ ] Yes
[X] No
> chore: Add azure devops sync workflow

- e2e/test-schematics.sh
- schematics/src/utils/ts-morph.ts
[x] Bugfix
- `add-destroy` schematic broken since last release
- repaired
- test added
[ ] Yes
[x] No
> fix: repair add-destroy schematic

- src/app/core/models/product/product.interface.ts
- src/app/core/models/product/product.mapper.ts
- src/app/core/models/product/product.model.ts
- src/app/shared/components/product/product-inventory/product-inventory.component.html
- src/app/shared/components/product/product-inventory/product-inventory.component.ts
[x] Feature
availableStock is not used in PWA
availableStock is used in PWA if provided by the ICM
[x] No
> feat: show available stock if available

- src/app/core/directives.module.ts
- src/app/core/directives/product-context-access.directive.ts
- src/app/core/facades/product-context.facade.ts
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.spec.ts
- src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.ts
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.html
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.spec.ts
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.ts
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.html
- src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.spec.ts
- src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
- src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.spec.ts
- src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
- src/app/pages/product/product-brand/product-brand.component.html
- src/app/pages/product/product-brand/product-brand.component.spec.ts
- src/app/pages/product/product-brand/product-brand.component.ts
[x] Feature
- introduce product context access directive for accessing context contents on templates
[ ] Yes
[x] No
This would be very helpful on project customizations, as the impact on source code modification can be kept low, when using the template replacement feature #537
> feat: product context access directive

- package-lock.json
- package.json
- src/app/extensions/seo/seo.module.ts
- src/app/extensions/seo/store/seo/seo.effects.ts
ngx-meta library is not maintained anymore: #fulls1z3/ngx-meta/issues/210
replace with native [Meta](https://angular.io/api/platform-browser/Meta) and [Title](https://angular.io/api/platform-browser/Title) services.
[ ] Yes
[x] No
> refactor: remove ngx-meta and replace with native implementation

- src/app/shared/formly/extensions/critical-default-values.extension.ts
- src/app/shared/formly/extensions/hide-if-empty-options.extension.ts
- src/app/shared/formly/extensions/post-wrappers-extension.ts
- src/app/shared/formly/extensions/translate-select-options.extension.ts
Small in-code documentation update
> docs: describe each formly extension

- src/app/core/configurations/ngrx-state-transfer.ts
[x] Bugfix
tl;dr: Later initialized feature stores lose their state-transfer state if a previous action modifies the store.
Long version:
1. add the following effect to `src/app/core/store/content/pages/pages.effects.ts`:
```typescript
disturb$ = createEffect(() =>
this.store.pipe(
select(getConfigurationState),
mapToProperty('channel'),
whenTruthy(),
mapTo(loadContentPageSuccess({ page: { id: 'asdf' } as any, pagelets: [] }))
)
);
```
2. start the PWA in SSR mode with tracking enabled. It is important that the gtm token is only set via environment variables:
Linux: 
```
$ GTM_TOKEN=GTM-QWERTY FEATURES=tracking npm run start --configuration=production
```
Windows cmd:
```
$ set GTM_TOKEN=GTM-QWERTY
$ set FEATURES=tracking
$ npm run start --configuration=production
```
3. Observe the redux …
> fix: re-apply transferred state for later initialized feature states

- package-lock.json
- package.json
- localization clean is tested on CI
- localization cleanup in precommit
[ ] Yes
[x] No
> chore: sort localizations in pre-commit

- .vscode/settings.json
[x] Other: VSCode experience
Marked nginx config files as `properties` for VSCode
[ ] Yes
[ ] No
> chore: mark nginx files as property files for VSCode

- src/app/core/utils/module-loader/module-loader.service.ts
[x] Other: Cleanup
Logging statement in `ModuleLoaderService` pollutes SSR logs. Statement was left in there by #631.
removed logging statement
[ ] Yes
[x] No
> chore: remove logging statement in module loader

- src/setupJest.ts
Some errors in jest runs are not reported as test failures but just logged to the console.
Jest reports the errors by monitoring the `console.log` and `console.error` output.
[ ] Yes
[x] No
> test: fail if test runs without all required stores

- package-lock.json
- package.json
[x] Application / infrastructure changes
PWA updates job currently fails because custom-webpack has an audit issue.
custom-webpack moved to dev dependencies. Upgrade before the release should be done to fix the audit issue.
[ ] Yes
[x] No
> deps: move custom-webpack to dev dependencies

- docs/guides/code-documentation.md
- package.json
- tsconfig.doc.json
[ x] Bugfix
[ ] Feature
[ ] Other: 
The generated compodoc is no longer providing the expected documentation for the projects artifacts.
Issue Number: Closes #589
Compodoc creates expected documentations
[ ] Yes
[x] No
Solution is related to compodoc documentation (https://compodoc.app/guides/installation.html)
> fix: compodoc should work

- docs/README.md
- docs/concepts/deploy-url.md
- docs/guides/ssr-startup.md
> docs: documentation for deploy url

- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
[x] Bugfix
Issue Number: Closes #680 
Fixed
[ ] Yes
[x] No
> fix: reset children when switching sku in context

- .github/pull_request_template.md
As discussed in our team retrospective, it would be nice to remind everyone to check visual changes with the corresponding departments.
> chore: adapt pr template to include VD and IAD

- src/app/core/utils/api-token/api-token.service.ts
- src/app/pages/contact/contact-page.component.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
See Issue
Issue Number: Closes #648
You will not be logged out anymore after refreshing after contact us submission.
[ ] Yes
[x] No
> fix: fix logout bug after contact us submission

- src/app/core/utils/translate/fallback-missing-translation-handler.ts
[x] Bugfix
Issue Number: Closes #726
Fixed
[ ] Yes
[x] No
> fix: double-check missing translation before reporting

- docker-compose.yml
- docs/README.md
- docs/concepts/multi-site-handling.md
- docs/guides/multi-site-configurations.md
- docs/guides/nginx-startup.md
- nginx/multi-channel.yaml
[ ] Bugfix
[ ] Feature
[ ] Other: 
Currently, no baseHrefs and languages are set in the default multi site config. This is changed in preparation for an updated language switch component.
one domain, different countries via URL path, different languages  
inspired.com/en_us
inspired.com/de_de
inspired com/ca_en
inspired.com/ca_fr
(inspired.com = inspired.com/en_us)
different domains for different countries, different languages
inspired.de/de
inspired.com/en
inspired.ca/en
inspired.ca/fr
subdomains for different countries, different languages
de.inspired.com/de …
> chore: adapt demo multisite config

- e2e/package.json
[ ] Bugfix
[ ] Feature
[x] Other: dependency upgrade 
Cypress 6.x is used.
Cypress 7.x is used.
[ ] Yes
[x] No
The existing e2e tests are not affected by this upgrade.
> deps: upgrade cypress to 7.x

- src/app/pages/checkout-review/checkout-review-page.module.ts
- src/app/pages/checkout-review/checkout-review/checkout-review.component.html
- src/app/pages/checkout-review/checkout-review/checkout-review.component.spec.ts
- src/app/pages/checkout-review/checkout-review/checkout-review.component.ts
- src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.html
- src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.spec.ts
- src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
Checkout Review Page component uses standard form.
Component will use formly.
[ ] Yes
[x] No
> Formly: Checkout Review Page

- .github/workflows/integration.yml
- angular.json
- e2e/test-schematics.sh
- templates/webpack/webpack.custom.ts
[x] Bugfix
Issue Number: Closes #758
fixed
[ ] Yes
[x] No
> fix: repair npm run start:local

- docs/guides/formly.md
- projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
- src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
- src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.spec.ts
- src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
- src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.ts
- src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.ts
- src/app/pages/forgot-password/update-password-form/update-password-form.component.ts
- src/app/shared/components/basket/basket-order-reference/basket-order-reference.component.ts
- src/app/shared/formly-address-forms/configurations/us/address-form-us.configuration.ts
- src/app/shared/formly/components/validation-message/validation-message.component.ts
- src/app/shared/formly/extensions/post-wrappers-extension.ts
- src/app/shared/formly/formly.module.ts
- src/app/shared/formly/wrappers/description-wrapper/description-wrapper.component.html
- src/app/shared/formly/wrappers/input-addon-wrapper/input-addon-wrapper.component.html
[x] Bugfix
[ ] Feature
[ ] Other: 
Currently, descriptions are wrongly rendered below validation error messages in forms.
The postWrappersExtension can now receive an additional index parameter to specifically control the placement of certain wrappers.
[ ] Yes
[x] No
> fix: adapt post wrappers extension and fix occurences

- .azure/azure-pipelines.yml
[ ] Bugfix
[ ] Feature
[ ] Other: 
Azure pipeline is added as part of Azure Deveops project
Pipeline is part of this project. Available as source code so others can check the required steps to produce the artifacts.
[ ] Yes
[x] No
> Add Azure CI pipeline

- templates/webpack/webpack.custom.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
The mobile view of the language switch does not show the different language options.
Issue Number: Closes #757
The language options are displayed in mobile view.
[ ] Yes
[x] No
> fix: styling issue concerning mobile language switch (#769)

- projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.spec.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.spec.ts
- src/app/core/services/api/api.service.errorhandler.spec.ts
- src/app/core/services/api/api.service.spec.ts
- src/app/core/services/cms/cms.service.spec.ts
- src/app/core/store/shopping/products/products.selectors.ts
- src/app/pages/search/search-result/search-result.component.spec.ts
- src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.spec.ts
- src/setupJest.ts
[AB#64713](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64713)
> refactor: typing improvements

- .prettierignore
- dist/healthcheck.js
prettier is not active for scripts in `dist`
activated prettier, applied format
[ ] Yes
[x] No
[AB#64916](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64916)
> style: enable prettier for dist scripts

- e2e/cypress/integration/pages/checkout/checkout-payment.page.ts
- src/app/pages/checkout-payment/checkout-payment-page.module.ts
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
- src/app/pages/checkout-payment/formly/payment-save-checkbox/payment-save-checkbox.component.html
- src/app/pages/checkout-payment/formly/payment-save-checkbox/payment-save-checkbox.component.spec.ts
- src/app/pages/checkout-payment/formly/payment-save-checkbox/payment-save-checkbox.component.ts
- src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.html
- src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.spec.ts
- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.html
- src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.spec.ts
- src/app/pages/checkout-payment/payment-concardis/payment-concardis.component.ts
- src/app/pages/checkout-payment/payment-parameter-form/payment-parameter-form.component.html
- src/app/pages/checkout-payment/payment-parameter-form/payment-parameter-form.component.spec.ts
- src/styles/pages/payment/payment.scss
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[x] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the New Behavior?<br />The save-for-later check boxes on checkout payment page are created using the formly framework.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br />
[AB#65464](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65464)
> refactor: use formly to create the save-for-later checkbox on checkout payment page

- docs/guides/formly.md
- src/app/shared/formly/components/field-tooltip/field-tooltip.component.ts
- src/app/shared/formly/components/validation-icons/validation-icons.component.ts
- src/app/shared/formly/components/validation-message/validation-message.component.ts
- src/app/shared/formly/extensions/hide-if-empty-options.extension.ts
- src/app/shared/formly/extensions/post-wrappers-extension.ts
- src/app/shared/formly/extensions/translate-select-options.extension.ts
- src/app/shared/formly/types/captcha-field/captcha-field.component.ts
- src/app/shared/formly/types/checkbox-field/checkbox-field.component.ts
- src/app/shared/formly/types/email-field/email-field.component.ts
- src/app/shared/formly/types/fieldset-field/fieldset-field.component.ts
- src/app/shared/formly/types/password-field/password-field.component.ts
- src/app/shared/formly/types/phone-field/phone-field.component.ts
- src/app/shared/formly/types/radio-field/radio-field.component.ts
- src/app/shared/formly/types/select-field/select-field.component.ts
- src/app/shared/formly/types/text-input-field/text-input-field.component.ts
- src/app/shared/formly/types/textarea-field/textarea-field.component.ts
- src/app/shared/formly/wrappers/description-wrapper/description-wrapper.component.ts
- src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.ts
- src/app/shared/formly/wrappers/horizontal-wrapper/horizontal-wrapper.component.ts
- src/app/shared/formly/wrappers/input-addon-wrapper/input-addon-wrapper.component.ts
- src/app/shared/formly/wrappers/textarea-description-wrapper/textarea-description-wrapper.component.ts
- src/app/shared/formly/wrappers/tooltip-wrapper/tooltip-wrapper.component.ts
- src/app/shared/formly/wrappers/validation-wrapper/validation-wrapper.component.ts
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[x] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Currently, Formly is mostly documented in formly.md<br /><br />## What Is the New Behavior?<br /><br />Now, every formly component, type, wrapper and extension has a summary and list of relevant templateOptions as well as a guide for using it.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br /> …
> docs: add code documentation for formly things

- docs/guides/forms.md
- src/app/shared/forms/components/checkbox/checkbox.component.ts
- src/app/shared/forms/components/form-element/form-element.component.ts
- src/app/shared/forms/components/input-birthday/input-birthday.component.ts
- src/app/shared/forms/components/input/input.component.ts
- src/app/shared/forms/components/select-address/select-address.component.ts
- src/app/shared/forms/components/select-country/select-country.component.ts
- src/app/shared/forms/components/select-region/select-region.component.ts
- src/app/shared/forms/components/select-title/select-title.component.ts
- src/app/shared/forms/components/select/select.component.ts
- src/app/shared/forms/components/textarea/textarea.component.ts
- src/app/shared/forms/forms.module.ts
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[x] Application / infrastructure changes<br />[ ] Other: <br /><br />This commit marks all unused form components as deprecated. They will be fully removed at a later point in time.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br />
[AB#65724](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65724)
> chore: mark form components as deprecated and update docs

- .dockerignore
- .editorconfig
- docs/check-dead-links.js
- docs/concepts/configuration.md
- docs/concepts/hybrid-approach.md
- docs/concepts/styling-behavior.md
- docs/concepts/testing.md
- docs/guides/angular-component-development.md
- docs/guides/continuous-integration.md
- docs/guides/development.md
- docs/guides/getting-started.md
- docs/guides/migrations.md
- docs/guides/nginx-startup.md
- docs/guides/sentry-error-monitoring.md
- docs/guides/ssr-startup.md
- docs/guides/state-management.md
- docs/guides/testing-cypress.md
- docs/guides/testing-jest.md
- schematics/src/kubernetes-deployment/README.md
- src/environments/environment.model.ts
- src/styles/global/tables.scss
Add missing documentation for new `environment.ts` configuration options.
Issue Number: Closes #770
[AB#65432](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65432)
> docs: improve/extend environment.ts configuration documentation

- scripts/build-multi-pwa.js
Issue Number: Closes: #814
No warnings.
[ ] Yes
[x] No
[AB#66039](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66039)
> chore: prevent ngcc lock file warning

- src/app/core/utils/translate/fallback-missing-translation-handler.ts
[x] Bugfix
If the translation fallback is triggered, the retrieved fallback translations are not compiled using the custom translate compiler.
Fallback translations are properly compiled before usage.
Minor refactoring.
[ ] Yes
[x] No
[AB#66291](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/66291)
> fix: use translate compiler for fallback translations

- projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.html
- projects/requisition-management/src/app/models/requisition/requisition.mapper.spec.ts
- projects/requisition-management/src/app/models/requisition/requisition.mapper.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.html
[x] Bugfix
There might be some data of a requisition not available, especially if the user got deleted. This should not break the page.
page stays intact
[x] No
[AB#69421](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69421)
> no broken page on missing requisition data

- src/app/core/guards/identity-provider-logout.guard.ts
[x] Bugfix
Currently, there are issues when using punchout with an sso system. 
Afterwards, the two systems should work without problems.
[x] No
[AB#69239](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69239)
> fix: enable logout of punchout user in combination with SSO

- nginx/channel.conf.tmpl
- src/app/core/facades/checkout.facade.ts
- src/app/core/facades/product-context.facade.ts
- src/app/core/store/core/viewconf/viewconf.effects.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/utils/api-token/api-token.service.ts
[x] Other: Performance improvements
Product pages take at least 800ms on SSR, other pages at least 400ms.
Some delays can be skipped for SSR.
All pages ~100-250ms (without ICM delay).
404 pages are cached longer in nginx.
[ ] Yes
[x] No
Please merge with rebase, so the individual history stays intact.
[AB#69735](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69735)
> various performance improvements

- docs/concepts/hybrid-approach.md
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[x] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />The current documentation lead to some confusion when setting up a hybrid approach deployment.<br /><br />## What Is the New Behavior?<br /><br />The documentation is updated to be clearer.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br />
[AB#69906](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79 …
> docs: update hybrid approach ssl documentation

- src/app/core/interceptors/universal-log.interceptor.ts
[x] Bugfix
- reported content length is doubled
- errors are not logged with duration
- issues fixed
- using `performance` for more accurate time values
[ ] Yes
[x] No
[AB#69902](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69902)
> chore: improve PWA REST API logging

- CONTRIBUTING.md
There are some major english mistakes in the documentation. 
The major problems are fixed.
[x] No
[AB#71600](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/71600)
> fix: correct some language mistakes in documentation

- projects/organization-management/src/app/components/cost-center-buyer-edit-dialog/cost-center-buyer-edit-dialog.component.ts
- projects/organization-management/src/app/components/cost-center-form/cost-center-form.component.ts
- projects/organization-management/src/app/components/cost-center-users-list/cost-center-users-list.component.html
- projects/organization-management/src/app/components/cost-center-users-list/cost-center-users-list.component.ts
- projects/organization-management/src/app/components/user-budget/user-budget.component.html
- projects/organization-management/src/app/components/user-budget/user-budget.component.spec.ts
- projects/organization-management/src/app/pages/cost-center-buyers/cost-center-buyers-page.component.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.html
- projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.spec.ts
- projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.ts
- src/app/core/models/price/price.pipe.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
<br /><br />## PR Type<br /><br /><br /><br />[x] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br />There are some minor ui issues in the cost center management.<br /><br /><br /><br />Issue Number: Closes #957<br /><br />## What Is the New Behavior?<br />The minor cost center ui issues have been fixed.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br /> …
> fix: unify budget input fields layout in phone view (#957)

- src/app/core/services/localizations/localizations.service.spec.ts
- src/app/core/services/localizations/localizations.service.ts
[x] Bugfix
Issue Number: Closes #971
- error caught, logged and empty translations returned
- testing
[ ] Yes
[x] No
[AB#72527](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/72527)
> fix: catch and log errors from translation API

- src/app/extensions/wishlists/shared/select-wishlist-form/select-wishlist-form.component.ts
- src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
- src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.html
<br /><br />## PR Type<br /><br /><br /><br />[x] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br />
There are some minor bugs:
1. Moving an item from a preferred wishlist to another one is not working. After clicking the move button in the dialog nothing happens.
2. If the user clicks the Terms&Conditions link on the checkout review page the url is not correct and the page cannot be rendered. 
<br /><br /><br /><br />Issue Number: Closes #<br /><br />## What Is the New Behavior?<br />The …
> fix: minor issues

- src/app/core/services/registration-form-configuration/registration-form-configuration.service.spec.ts
- src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
see #997 
[AB#74089](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74089)
> fix: add title to registration form

- src/app/core/store/customer/basket/basket.effects.spec.ts
- src/app/core/store/customer/basket/basket.effects.ts
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[x] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[ ] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br />If the user change the language and this language has a different default currency all product prices are displayed using this new currency, but the basket stays unchanged in the original currency. If the user take any action on this basket like adding or deleting a product, changing the shipping address etc. the basket is recalculated using the new currency.<br /><br /><br /><br />Issue …
> feat: recalculate basket after language/currency change

- package.json
<br /><br />## PR Type<br /><br /><br /><br />[ ] Bugfix<br />[ ] Feature<br />[ ] Code style update (formatting, local variables)<br />[ ] Refactoring (no functional changes, no API changes)<br />[ ] Build-related changes<br />[x] CI-related changes<br />[ ] Documentation content changes<br />[ ] Application / infrastructure changes<br />[ ] Other: <br /><br />## What Is the Current Behavior?<br /><br />Currently, eslint errors in html files will not prevent commits because they do not trigger eslint.<br /><br />Issue Number: Closes #<br /><br />## What Is the New Behavior?<br /><br />Now, html file changes also trigger eslint.<br /><br />## Does this PR Introduce a Breaking Change?<br /><br /><br /><br />[ ] Yes<br />[x] No<br /><br />## Other Information<br /> …
> ci: enable eslint commit hook for html files

- src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
Refer to issue #1008
[AB#74353](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74353)
> fix: sanitize payment parameter form values

- schematics/src/cms-component/files/__name@dasherize@if-flat__/__name@dasherize__.component.scss.template
- schematics/src/component/files/__name@dasherize@if-flat__/__name@dasherize__.component.scss.template
- schematics/src/utils/common.ts
CMS Component Schematics styling import improvement + module determination fix
[AB#74215](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74215)
> fix: schematics bugfixes and improvements

- .github/workflows/development.yml
- Dockerfile
- Dockerfile_reports
- package.json
- schematics/src/helpers/add-destroy/factory.ts
- schematics/src/helpers/lazy-components/schema.json
- schematics/src/lazy-component/factory.ts
- schematics/src/lazy-component/factory_spec.ts
- schematics/src/lazy-component/schema.json
- scripts/check-file-synchronization.js
- templates/Dockerfile_dev
- `npm run synchronize-lazy-components` slow in docker build
- docker build includes build cache
- docker build is run in CI mode (disables angular build cache and schematic lint fixes)
- read CI variable in schematics from env
[ ] Yes
[x] No
[AB#74538](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74538)
> chore: docker build optimization

- 3rd-party-licenses.txt
- CHANGELOG.md
- package-lock.json
- package.json
[AB#75016](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75016)
> chore: release 2.1.0 preparation

- src/app/core/interceptors/payment-payone.interceptor.ts
[ ] Bugfix
[X] Feature
[ ] Other: 
Payone Eps payment method is not supported.
Payone Eps payment method is supported.
[ ] Yes
[X] No
> feat:support Payone Eps payment method.

- src/app/core/directives/product-context-access.directive.ts
- src/app/core/directives/product-context.directive.ts
- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
[x] Bugfix
[x] Feature
Minor improvements to the product context.
[ ] Yes
[x] No
[AB#75164](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75164)
> refactor: product context improvements

- 3rd-party-licenses.txt
- CHANGELOG.md
- docs/guides/google-tag-manager.md
- package-lock.json
- package.json
- src/app/extensions/recently/store/recently/recently.integration.spec.ts
- src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.html
- src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.html
[AB#76417](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76417)
> chore: release 2.3.0 preparation

- .github/workflows/automated-upgrade.yml
- scripts/upgrade-pwa.js
CI pipeline running the automated upgrade script.
Updates the branch [upgrade/automated-upgrade](https://github.com/intershop/intershop-pwa/compare/upgrade/automated-upgrade) on a ~~daily~~ weekly basis as a start for upgrading.
[ ] Yes
[x] No
[AB#75572](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75572)
> build: add pipeline for automated upgrade

- src/app/pages/basket/shopping-basket/shopping-basket.component.html
[ ] Bugfix
[x] Feature
[ ] Other: 
Dynamic promotion messages, maintained in ICM back office as part of a promotion, are not displayed on the shopping cart page. 
Dynamic promotion messages are displayed on the shopping cart page.
[ ] Yes
[x] No
[AB#76432](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76432)
> feat: display dynamic promotion messages on the shopping cart page

- src/app/core/guards/auth.guard.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/viewconf/viewconf.effects.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/core/store/customer/user/user.effects.ts
- src/app/core/store/hybrid/hybrid.effects.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/utils/translate/icm-translate-loader.ts
- src/app/extensions/sentry/store/sentry-config/sentry-config.effects.ts
- src/app/extensions/seo/store/seo/seo.effects.ts
- src/app/extensions/store-locator/store/store-locator-config/store-locator-config.effects.ts
- src/app/extensions/tracking/store/tracking-config/tracking-config.effects.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[ ] No
> refactor: additional tree-shakable simplifications

- docs/concepts/hybrid-approach.md
- docs/guides/migrations.md
- src/app/pages/checkout/checkout-page.guard.ts
[AB#76993](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76993)
> docs: add 2.3 datepicker migration note

- .github/workflows/demo-server-down.yml
- .github/workflows/demo-server-up.yml
[ ] Bugfix
[ ] Feature
[ ] Other: 
Review servers are broken
Review servers work again, though the demo-server-up workflow has to be started manually. Their name will now include the branch name
[ ] Yes
[x] No
[AB#77271](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77271)
> chore: refactor demo server action

- nginx/Dockerfile
- nginx/entrypoint.sh
[ X ] Bugfix
[ ] Feature
[ ] Other: 
Issue Number: Closes #1187
[ ] Yes
[ ] No
- [NGinx org change log](https://nginx.org/en/CHANGES)
- [Pagespeed release notes](https://www.modpagespeed.com/doc/release_notes)
[AB#77437](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77437)
> fix: pin version to the equally latest version

- .eslintrc.json
- src/app/extensions/rating/services/reviews/reviews.service.spec.ts
- src/app/extensions/rating/shared/product-reviews/product-reviews.component.spec.ts
- src/app/extensions/rating/store/product-reviews/product-reviews.effects.spec.ts
- src/app/extensions/rating/store/product-reviews/product-reviews.selectors.spec.ts
- src/typings.d.ts
enable eslint rules 'no-var' and ' prefer-const' plus source code fixes that did not fit these rules
[x] No
[AB#77715](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77715)
> style: enable eslint rules 'no-var' and ' prefer-const'

- docs/guides/product-context.md
- e2e/cypress/integration/specs/checkout/checkout-cost-center-order.b2b.e2e-spec.ts
- e2e/cypress/integration/specs/system/rest-error-handling.b2c.e2e-spec.ts
- scripts/find-dead-code.ts
* fixed failing e2e test
* fixed intended dead code exception
[AB#78320](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78320)
> chore(seo): fix problems introduced by the seo URLS rework

- docs/guides/data-handling-with-mappers.md
`guides/data-handling-with-mappers.md` was out of date so I updated it. 
[AB#78356](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78356)
> docs: update mapper documentation

- docs/guides/migrations.md
- src/app/core/facades/checkout.facade.ts
- src/app/core/icon.module.ts
- src/app/core/services/basket/basket.service.spec.ts
- src/app/core/services/basket/basket.service.ts
- src/app/core/store/customer/basket/basket-items.effects.spec.ts
- src/app/core/store/customer/basket/basket-items.effects.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/core/store/customer/basket/basket.selectors.spec.ts
- src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.ts
- src/app/pages/basket/basket-page.component.html
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/pages/basket/shopping-basket/shopping-basket.component.ts
- src/app/shared/components/basket/mini-basket-content/mini-basket-content.component.html
- src/app/shared/components/basket/mini-basket-content/mini-basket-content.component.spec.ts
- src/app/shared/components/basket/mini-basket-content/mini-basket-content.component.ts
- src/app/shared/components/common/paging/paging.component.html
- src/app/shared/components/common/paging/paging.component.scss
- src/app/shared/components/common/paging/paging.component.spec.ts
- src/app/shared/components/common/paging/paging.component.ts
- src/app/shared/components/line-item/line-item-list/line-item-list.component.html
- src/app/shared/components/line-item/line-item-list/line-item-list.component.spec.ts
- src/app/shared/components/line-item/line-item-list/line-item-list.component.ts
- src/app/shared/shared.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ ] Bugfix
[ ] Feature
[ ] Other: 
In case of large basket ( > 100 items ) the response times after user interactions are unacceptable long, e.g. it takes a really long time to show the mini basket or the screen is blocked to long after adding, updating or deleting basket items.
There are optimizations concerning the IAD as well as the technical handling in respect of large baskets.
- display only a limited number of line items in the mini basket
- display a paging bar in case a basket has more than 25 items ( configurable in the …
> perf: performance improvements in respect of large baskets

- e2e/cypress/e2e/specs/checkout/basket-handling.b2c.e2e-spec.ts
- src/app/core/interceptors/icm-error-mapper.interceptor.spec.ts
- src/app/core/interceptors/icm-error-mapper.interceptor.ts
- src/app/core/models/http-error/http-error.model.ts
- src/app/core/services/basket/basket.service.ts
- src/app/core/store/customer/basket/basket-items.effects.spec.ts
- src/app/core/store/customer/basket/basket.actions.ts
- src/app/core/store/customer/basket/basket.reducer.ts
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/pages/basket/shopping-basket/shopping-basket.component.spec.ts
- src/app/shared/components/basket/basket-error-message/basket-error-message.component.html
- src/app/shared/components/basket/basket-error-message/basket-error-message.component.spec.ts
- src/app/shared/components/basket/basket-error-message/basket-error-message.component.ts
- src/app/shared/components/basket/mini-basket-content/mini-basket-content.component.html
- src/app/shared/components/common/error-message/error-message.component.ts
- src/app/shared/shared.module.ts
[ ] Bugfix
[x] Feature
[ ] Other: 
Display multiple basket errors after adding items to cart, e.g. if items are added with the help of the quick order form. For more information see #1108.
[ ] Yes
[x] No
[AB#78541](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78541)
> feat: display multiple basket errors

- src/app/core/facades/product-context.facade.ts
- src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.spec.ts
- src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
(cherry picked from commit d655d6368c101e912389842db0535029443f4a4b)
see #1066
[AB#78775](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78775)
> fix: disable add-to-basket when quantity is zero (#1066)

- e2e/cypress/e2e/framework/index.ts
- e2e/cypress/support/commands.js
- src/app/shell/header/back-to-top/back-to-top.component.html
- src/app/shell/header/back-to-top/back-to-top.component.spec.ts
- src/app/shell/header/back-to-top/back-to-top.component.ts
- src/app/shell/header/header/header.component.html
- src/app/shell/header/header/header.component.spec.ts
- src/app/shell/shell.module.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
- src/styles/components/header/back-to-top.scss
- src/styles/main.scss
[ ] Bugfix
[x] Feature
[ ] Other: 
PWA does not provide a back to top button.
PWA provides a default back to top button
[ ] Yes
[x] No
Implementing a back to top button is a possible repetitive task in customer projects.
[AB#77233](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77233)
> Add Back To Top Button

- .github/workflows/demo-server-up.yml
[AB#78809](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78809)
> chore: fix demo server comment

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/shellrc.sh
- .vscode/extensions.json
- scripts/check-file-synchronization.js
- `npm install` was re-executed every time because `node_modules` were in RAM -> now in reusable volume
- nodejs version extracted from `package.json` and installed on container creation
- bash completion for `git` and `ng` (also switched default shell to zsh)
- synchronize extension list of vscode and devcontainer
[ ] Yes
[x] No
[AB#79015](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79015)
> chore: devcontainer optimization

- .github/scripts/docker-compose.py
- .github/scripts/requirements.txt
- .github/workflows/demo-server-up.yml
- .prettierignore
[ ] Bugfix
[ ] Feature
[ x ] CI-related changes
[ ] Other: 
Only single container deployments are supported in our GitHub review demo environment. This makes certain aspects of the App not usable (e.g reload in B2B theme, language switch, punchout identity provider override)
We can replicate the `docker-compose.yml` to start [Multi-container app](https://docs.microsoft.com/en-us/azure/app-service/tutorial-multi-container-app) in our Azure AppService plan. With nginx and ssr container in place we solve above shortcomings.
[ ] Yes
[ X ] No …
> chore: enable multi container deployments in our demo environment

- package-lock.json
- src/app/core/directives/server-html.directive.spec.ts
- src/app/core/guards/auth.guard.spec.ts
- src/app/core/routing/category/category.route.spec.ts
- src/app/core/routing/content-page/content-page-route.spec.ts
- src/app/core/routing/product/product.route.spec.ts
- src/app/core/store/content/content-store.spec.ts
- src/app/core/store/customer/basket/basket-payment.effects.spec.ts
- src/app/extensions/contact-us/pages/contact/contact-page.component.spec.ts
- src/app/extensions/order-templates/shared/basket-create-order-template/basket-create-order-template.component.spec.ts
- src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.spec.ts
- src/app/extensions/punchout/identity-provider/punchout-identity-provider.spec.ts
- src/app/extensions/quoting/shared/basket-add-to-quote/basket-add-to-quote.component.spec.ts
- src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.spec.ts
- src/app/pages/account-profile-company/account-profile-company-page.component.spec.ts
- src/app/pages/checkout-address/checkout-address-page.component.spec.ts
- src/app/pages/error/error/error.component.spec.ts
- src/app/pages/error/server-error/server-error.component.spec.ts
- src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
- src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.spec.ts
- src/app/shared/cms/components/cms-dialog/cms-dialog.component.spec.ts
- src/app/shared/cms/components/cms-freestyle/cms-freestyle.component.spec.ts
- src/app/shared/cms/components/cms-text/cms-text.component.spec.ts
- src/app/shared/cms/components/content-pagelet/content-pagelet.component.spec.ts
- src/app/shared/components/search/search-box/search-box.component.spec.ts
- src/app/shell/header/header/header.component.spec.ts
- src/app/shell/header/language-switch/language-switch.component.spec.ts
Fixes cleanup-testbed script issues after dependencies update.
[x] No
[AB#80243](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80243)
> test: fix dead code in basket-payment.effects

- docs/guides/migrations.md
- docs/guides/ssr-startup.md
- src/app/core/store/core/configuration/configuration.effects.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Issue Number: Closes #1274 
Note before starting your PWA in SSR mode: The environment variable 'ICM_IDENTITY_PROVIDER' has been renamed to 'IDENTITY_PROVIDER'. 
[x] Yes
[ ] No
[AB#80086](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80086)
> refactor: rename environment variable 'ICM_IDENTITY_PROVIDER' 

- docs/concepts/progressive-web-app.md
- docs/concepts/styling-behavior.md
- docs/guides/customizations.md
- docs/guides/development.md
- docs/guides/getting-started.md
- docs/guides/multiple-themes.md
- remove duplicate content
- add more description to certain topics
[x] No
[AB#79620](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79620)
> docs: update documentation

- .eslintrc.json
- docs/guides/migrations.md
- package-lock.json
- package.json
- src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.spec.ts
- src/app/extensions/quickorder/shared/direct-order/direct-order.component.spec.ts
- src/app/extensions/quickorder/shared/quickorder-add-products-form/quickorder-add-products-form.component.spec.ts
- src/app/pages/account-addresses/account-addresses/account-addresses.component.spec.ts
- src/app/pages/account-profile-company/account-profile-company/account-profile-company.component.spec.ts
- src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.spec.ts
- src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.spec.ts
- src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.spec.ts
- src/app/pages/registration/registration-page.component.spec.ts
- src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.spec.ts
- src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
- src/app/shared/formly/extensions/translate-placeholder.extension.ts
- src/app/shared/formly/field-library/library-config-replacement.extension.ts
- src/app/shared/formly/types/select-field/select-field.component.html
- src/app/shared/formly/wrappers/description-wrapper/description-wrapper.component.spec.ts
Apply migration guide: https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-6.0.md
[x] Other: dependency update
BREAKING CHANGES: ???
[ ] Yes
[ ] No
[AB#80162](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80162)
> deps: update formly to version 6

- src/app/shared/components/product/product-attributes/product-attributes.component.html
- src/styles/pages/productdetail/productdetail.scss
[x] Feature
Attributes in Product details tab do not have an easily readable style
Added zebra striped table style for attributes in product details tab
[x] No
[AB#81189](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/81189)
> feat: added style for product details attributes

- docs/concepts/hybrid-approach.md
- docs/guides/ssr-startup.md
- server.ts
[ X ] Bugfix
[ ] Feature
[ ] Other: 
PWA Hybrid mode is not working in K8S
PWA Hybrid mode is working in K8S
[ ] Yes
[ X ] No
You need to use [pwa-main](https://github.com/intershop/helm-charts/releases?q=pwa-main&expanded=true) helm chart in version 0.4.0 or higher.
[AB#80963](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80963)
> fix: hybrid reverse proxy

- package-lock.json
- package.json
- src/app/core/models/product-view/product-view.model.ts
[AB#81581](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/81581)
> fix/deps: PM2 5.2.2 + product tile rendering fix

- src/app/extensions/wishlists/store/wishlist/wishlist.selectors.spec.ts
[x] No
[AB#82317](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/82317)
> test: add test for Wishlists Items SKUs selector

- .vscode/intershop.txt
- docs/concepts/hybrid-approach.md
- docs/guides/hybrid-approach-icm-url-rewriting.md
- docs/guides/ssr-startup.md
Added development environment Hybrid Approach documentation and some additional improvements to the whole Hybrid Approach documentation.
[x] No
[AB#84394](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/84394)
> docs: add Hybrid Approch development environment chapter

- schematics/src/address-form-configuration/factory_spec.ts
- schematics/src/cms-component/factory_spec.ts
- schematics/src/component/factory_spec.ts
- schematics/src/eslint-rule/factory_spec.ts
- schematics/src/extension/factory_spec.ts
- schematics/src/field-library-configuration/factory_spec.ts
- schematics/src/helpers/add-destroy/factory_spec.ts
- schematics/src/helpers/move-component/factory_spec.ts
- schematics/src/helpers/override/factory_spec.ts
- schematics/src/lazy-component/factory_spec.ts
- schematics/src/model/factory_spec.ts
- schematics/src/module/factory_spec.ts
- schematics/src/page/factory_spec.ts
- schematics/src/pipe/factory_spec.ts
- schematics/src/service/factory_spec.ts
- schematics/src/store-group/factory_spec.ts
- schematics/src/store/factory_spec.ts
- schematics/src/utils/testHelper.ts
See #1377
Issue Number: Closes #1377
[x] No
[AB#84989](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/84989)
> refactor: remove 'node_modules' imports (#1377)

- projects/requisition-management/src/app/pages/requisition-detail/requisition-detail-page.component.html
- src/app/extensions/quickorder/shared/direct-order/direct-order.component.html
- src/app/pages/account-order/account-order/account-order.component.html
- src/app/pages/basket/shopping-basket/shopping-basket.component.html
- src/app/pages/checkout-receipt/checkout-receipt/checkout-receipt.component.html
- src/app/shared/components/line-item/line-item-list/line-item-list.component.html
- src/styles/global/print.scss
[X] Feature
No print rules exist.
General print rules were introduced to the application without a header, and footer, with a reasonable layout, and nice page breaks.
[X] No
[AB#83954](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/83954)
> feat: print styling

- .eslintrc.json
- docs/guides/angular-component-development.md
- docs/guides/ssr-startup.md
- src/app/core/directives/scroll.directive.ts
- src/app/core/directives/server-html.directive.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/messages/messages.effects.ts
- src/app/core/utils/dom/dom.service.spec.ts
- src/app/core/utils/dom/dom.service.ts
- src/app/core/utils/script-loader/script-loader.service.ts
- src/app/core/utils/theme/theme.service.ts
- src/app/extensions/punchout/services/punchout/punchout.service.ts
- src/app/extensions/seo/store/seo/seo.effects.ts
- src/app/extensions/tacton/pages/configure/tacton-configure-navigation/tacton-configure-navigation.component.ts
- src/app/extensions/tracking/store/tracking-config/tracking-config.effects.ts
- src/app/pages/checkout-payment/payment-payone-creditcard/payment-payone-creditcard.component.ts
- src/app/shared/components/common/in-place-edit/in-place-edit.component.ts
- src/app/shared/components/common/modal-dialog/modal-dialog.component.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
In some cases DOM elements are manipulated accessing the DOM directly. This may cause security issues, might not work on server-side code or cause other side effects.
The Angular Renderer2 is used if DOM manipulations are needed outside of components. A new utility service (DomService) has been introduced to make common DOM manipulations easier.
[ ] Yes
[x] No
[AB#85322](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/85322)
> refactor: use Angular Renderer2 for DOM manipulations

- e2e/cypress/e2e/specs/account/addresses-crud.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/account/edit-user-company.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/account/edit-user-details.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/account/edit-user-email.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/account/edit-user-password.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/account/register-user.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/account/register-user.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/account/user-creation.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/basket-handling.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/basket-promotion-handling.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/checkout-cost-center-order.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/checkout-payments.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/checkout-validation.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/register-before-checkout.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/shopping-prices.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/shopping-prices.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/shopping-user.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/extras/order-templates-management.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/extras/order-templates-shopping.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/extras/price-notifications.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/extras/punchout-management.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/extras/wishlists-management.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/extras/wishlists-shopping.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/organizationmanagement/cost-center-management-crud.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/organizationmanagement/user-management-crud.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/quoting/quote-handling-anonymous-basket-to-quote-request.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/quoting/quote-handling-anonymous-product-to-quote-request.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/quoting/quote-handling.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/shopping/product-reviews.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/system/retain-basket-authenticated.b2c.e2e-spec.ts
[ ] Bugfix
[ ] Feature
[x] Other: test 
The cost-center-order e2e test uses the bboldner account to checkout a basket with a cost center assignment.
This led to test failures if this account is used for other test purposes.
A new user is created to execute this test.
[ ] Yes
[x] No
[AB#85611](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/85611)
> test: fix volatile cost center order e2e test

- src/app/extensions/captcha/shared/captcha-v2/captcha-v2.component.spec.ts
see https://github.com/intershop/intershop-pwa/actions/runs/5166395081/jobs/9306505144
[AB#86527](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/86527)
> test: cleanup testbed in captcha component

- .prettierrc.json
…cript parser
Update .prettierrc.json to make sure that *.mts files are using the typescript parser
[ ] Bugfix
[ ] Feature
[ ] Other: 
Issue Number: N/A
[ ] Yes
[X] No
> Make sure that `*.mts` files are using typescript parser with prettier

- src/app/core/utils/translate/icm-translate-loader.ts
[ x ] Bugfix
[ ] Feature
[ ] Other: 
The PWA fetches from the ICM localization data on SSR. When the PWA tries to change the language from the fallback language (en_US) to a different server supplied confiugration (de_DE), then it is possible that the PWA renders the page with incorrect translations. The selected language would be determined by the last localization REST response.
The PWA would automatically close all current localization REST calls, when the requested PWA language changes during the request.
[ ] Yes
[ x ] No …
> fix: incorrect translation on SSR

- package-lock.json
- package.json
- server.ts
- src/typings.d.ts
[x] Other: dependencies
[x] No
Add typings for `@types/express-http-proxy`
> deps(express-http-proxy): add types

- docs/guides/prometheus-monitoring-dashboard.json
- server.ts
- src/app/app.server.module.ts
- src/app/core/interceptors/universal-prometheus.interceptor.ts
- src/ssr/server-scripts/prometheus.js
[x] Feature
- SSR monitoring aggregates memory consumption by process name
- no monitoring access to max memory
- SSR monitoring reports memory consumption by PM2 process
- access to max memory
[ ] Yes
[x] No
[AB#88694](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88694)
> feat: prometheus reporting improvements

- docs/guides/migrations.md
- src/app/pages/category/category-products/category-products.component.html
- src/app/pages/product/product-master-variations/product-master-variations.component.html
- src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
- src/app/pages/search/search-result/search-result.component.html
- src/app/shared/components/product/product-listing/product-listing.component.spec.ts
- src/app/shared/components/product/product-listing/product-listing.component.ts
[x] No
- missing: add migration note
[AB#89314](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89314)
> refactor: rename 'id' to 'productListingId'

- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/messages/messages.effects.ts
- src/app/core/store/core/viewconf/viewconf.effects.ts
- src/app/core/store/customer/basket/basket.effects.ts
- src/app/core/store/customer/orders/orders.effects.ts
- src/app/core/store/customer/user/user.effects.ts
- src/app/core/store/shopping/search/search.effects.ts
[x] No
[AB#89308](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89308)
> uniform code-style for effects to check for ssr

- .devcontainer/devcontainer.json
- .vscode/extensions.json
[AB#89715](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89715)
> chore: remove obsolete extension recommendations

- .prettierignore
- .vscode/intershop.txt
- docker-compose.yml
- docs/guides/migrations.md
- docs/guides/nginx-startup.md
- nginx/Dockerfile
- nginx/features/cache-off.conf
- nginx/features/cache.conf
- nginx/lua/redis-integration.lua
- nginx/nginx.conf
- nginx/templates/cache-locations.conf.tmpl
- nginx/templates/cache-settings.conf.tmpl
- nginx/templates/multi-channel.conf.tmpl
[X] Feature
Each nginx has its own cache so in a deployment with multiple nginx (for redundancy), the cache hit rate is significantly lower than it could be.
Nginx instances push the cache to a shared redis service and retrieve it from there.
[ ] Yes
[X] No
[AB#89494](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89494)
> feat: shared nginx cache with redis

- .github/workflows/integration.yml
- e2e/cypress/e2e/pages/account/login.page.ts
- e2e/package-lock.json
- e2e/package.json
[ ] Bugfix
[ ] Feature
[x] Other: 
There are flaky e2e myAccount tests due to a long running token request.
The waiting time for the token response has been increased.
The cypress has been updated to version 13.6.
[ ] Yes
[x] No
[AB#91788](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91788)
> test: fix flaky e2e tests

- nginx/Dockerfile
[ ] Bugfix
[ ] Feature
[X] Application / infrastructure changes
[ ] Other: 
Prometheus exporter for NGINX is in version 0.11.0
Prometheus exporter for NGINX is in version 1.0.0
[ ] Yes
[X] No
[GitHub nginx-prometheus-exporter](https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v1.0.0)
There are breaking changes documented but the impact of these are hard to grasp.
[AB#92176](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92176)
> deps: update prometheus nginx exporter

- CHANGELOG.md
Clarified the ICM required version information since there were still misunderstandings.
[x] No
[AB#92712](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92712)
> docs: clarify requirements documentation

- src/app/pages/product/product-detail-actions/product-detail-actions.component.html
- src/app/shared/formly/types/date-picker-field/date-picker-field.component.html
- src/styles/pages/category/product-list.scss
- src/styles/pages/productdetail/productdetail.scss
[x] Bugfix
[ ] Feature
[ ] Other: 
There are some smaller UI issues (wishlist icon, product list item, desired delivery date).
The issues are fixed.
[ ] Yes
[x] No
[AB#94882](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94882)
> fix: small UI issues

- .github/workflows/demo-server-up.yml
(cherry picked from commit 3b48c0f05a8c19fb4232f752cde04753409dd9b3)
[AB#94970](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94970)
> ci: use https links for GitHub branch demo servers

- docs/guides/google-tag-manager.md
- docs/guides/migrations.md
- docs/guides/nginx-startup.md
- docs/guides/optimizations.md
[AB#95143](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95143)
> docs: review + improvement of NGINX and migration parts + extended Google Tag Manager information

- .eslintrc.json
- src/app/core/configurations/configuration.meta.ts
- src/app/core/directives/feature-toggle.directive.spec.ts
- src/app/core/directives/feature-toggle.directive.ts
- src/app/core/directives/not-feature-toggle.directive.spec.ts
- src/app/core/directives/not-feature-toggle.directive.ts
- src/app/core/feature-toggle.module.ts
- src/app/core/guards/feature-toggle.guard.spec.ts
- src/app/core/guards/feature-toggle.guard.ts
- src/app/core/identity-provider/identity-provider.factory.ts
- src/app/core/interceptors/icm-compatibility.interceptor.ts
- src/app/core/pipes/feature-toggle.pipe.spec.ts
- src/app/core/pipes/feature-toggle.pipe.ts
- src/app/core/store/core/configuration/configuration.effects.ts
- src/app/core/store/core/configuration/configuration.reducer.ts
- src/app/core/store/core/server-config/server-config.effects.ts
- src/app/core/utils/feature-event/feature-event.service.ts
- src/app/core/utils/module-loader/module-loader.service.ts
- src/app/pages/account/account-navigation/account-navigation.component.ts
- src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
Feature toggle related functionality is not consistently imported from the module
introduced rule for it
[ ] Yes
[x] No
[AB#96036](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96036)
> refactor: consolidate feature toggle imports

- projects/organization-management/src/app/pages/organization-management-routing.module.ts
- projects/requisition-management/src/app/pages/requisition-management-routing.module.ts
- schematics/src/extension/files/__name@dasherize__/pages/__name@dasherize__-routing.module.ts.template
- src/app/extensions/compare/pages/compare-routing.module.ts
- src/app/extensions/contact-us/pages/contact-us-routing.module.ts
- src/app/extensions/order-templates/pages/order-templates-routing.module.ts
- src/app/extensions/product-notifications/pages/product-notifications-routing.module.ts
- src/app/extensions/punchout/pages/punchout-account-routing.module.ts
- src/app/extensions/punchout/pages/punchout-routing.module.ts
- src/app/extensions/quickorder/pages/quickorder-routing.module.ts
- src/app/extensions/quoting/pages/quoting-routing.module.ts
- src/app/extensions/recently/pages/recently-routing.module.ts
- src/app/extensions/store-locator/pages/store-locator-routing.module.ts
- src/app/extensions/tacton/pages/tacton-routing.module.ts
- src/app/extensions/wishlists/pages/wishlists-routing.module.ts
- src/app/pages/account-order-history/account-order-history-page.module.ts
every routing module exports RouterModule
only app routing module exports RouterModule
[ ] Yes
[x] No
[AB#95141](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95141)
> refactor: remove unused RouterModule exports

- src/app/core/facades/shopping.facade.ts
- src/app/extensions/recently/pages/recently/recently-page.component.spec.ts
- src/app/extensions/recently/pages/recently/recently-page.component.ts
- src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.spec.ts
- src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.ts
- src/app/extensions/recently/store/recently/recently.reducer.ts
- src/app/extensions/recently/store/recently/recently.selectors.ts
- src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.spec.ts
- src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
inspired by the mentioned solution from #1420
[x] Bugfix
[x] No
[AB#96234](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96234)
> fix: handle case where all recently viewed products are failed/offline - improved

- .devcontainer/devcontainer.json
[X] Bugfix
devcontainer doesn't start
simplified install to repair
[ ] Yes
[X] No
[AB#96149](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96149)
> fix: repair devcontainer init

- docs/guides/nginx-startup.md
The documentation does not describe certain details which are needed to correctly configure the sitemap feature.
The documentation includes all needed information to configure the PWA sitemap.
[ ] Yes
[x] No
[AB#96119](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96119)
> docs: update PWA sitemap documentation

- scripts/init-development-environment.js
- src/app/pages/search/search-page.component.html
- src/app/shared/components/product/product-warranty-details/product-warranty-details.component.html
[x] No
[AB#96490](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96490)
> chore: collected small improvements

- .eslintrc.json
- server.ts
- src/app/core/models/attribute/attribute.pipe.spec.ts
- src/app/core/pipes/date.pipe.spec.ts
- src/app/core/pipes/make-href.pipe.spec.ts
- src/app/core/utils/api-token/api-token.service.ts
- src/app/core/utils/preview/preview.service.ts
- src/app/extensions/store-locator/services/stores-map/stores-map.service.ts
- src/app/shared/cms/components/cms-navigation-category/cms-navigation-category.component.spec.ts
- src/app/shared/components/product/product-variation-select-enhanced/product-variation-select-enhanced.component.spec.ts
- src/app/shared/components/product/product-variation-select-swatch/product-variation-select-swatch.component.spec.ts
- src/app/shell/header/back-to-top/back-to-top.component.ts
- src/app/shell/header/header-navigation/header-navigation.component.html
- src/app/shell/header/header-navigation/header-navigation.component.ts
[ ] Bugfix
[ ] Feature
[ ] Other: 
Some stricter rules for [`naming-convention` rule](https://typescript-eslint.io/rules/naming-convention/)
[ ] Yes
[x] No
[AB#95941](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95941)
> refactor: enforce stricter naming convention

- docs/guides/migrations.md
- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/utils/dev/html-query-utils.ts
- src/app/core/utils/product-context-display-properties/product-context-display-properties.service.ts
- src/app/shared/components/product/product-item-variations/product-item-variations.component.html
- src/app/shared/components/product/product-item-variations/product-item-variations.component.spec.ts
- src/app/shared/components/product/product-item-variations/product-item-variations.component.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[X] Refactoring (no functional changes, no API changes)
Logic in `ish-product-item-variations` is confusing.
Refactored component to make it easier to understand and customize.
[X] Yes
[ ] No
BREAKING CHANGE: The `ish-product-item-variations` component has been refactored.
[AB#96248](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/96248)
> refactor: rework product-item-variations component

- docs/guides/customizations.md
- docs/guides/migrations.md
- src/app/core/services/api/api.service.ts
- src/app/core/services/basket/basket.service.ts
- src/app/core/utils/dom/dom.service.ts
- src/app/core/utils/feature-toggle/feature-toggle.service.spec.ts
- src/app/extensions/order-templates/pages/order-templates-routing.module.ts
- src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.scss
- src/app/shared/components/common/loading/loading.component.scss
[x] Bugfix
* fix: improved styling of loading spinner (loading animation placement for long containers, z-index)
* fix: Bootstrap carousel slide content overflow when changing slides
* refactor: fixed missed places for `encodeResourceId` refactoring + documentation improvement (addition for #1704)
* refactor: consolidate feature toggle imports (#1636) - additional cleanup
* chore: documentation improvements
[x] No
[AB#102737](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/102737)
> chore: minor improvements/fixes from current projects

- src/app/extensions/punchout/services/punchout/punchout.service.ts
[x] Bugfix
The method `getCxmlPunchoutSession` used the wrong header for a cXML punchout REST API request.
Also the punchout user methods did not use the correct headers when handling cXML users.
The fitting headers to the according punchout resource are used now.
* introduced header for OCI, cXML and general with according versions
* used punchout resource determination only where necessary
[x] No
[AB#103621](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/103621)
> fix: use correct punchout REST API headers for cXML and OCI punchout

- e2e/cypress/e2e/specs/checkout/checkout-cost-center-no-costcenter.b2b.e2e-spec.ts
- package-lock.json
- package.json
- src/app/core/facades/product-context.facade.spec.ts
- src/app/core/facades/product-context.facade.ts
- src/styles/pages/category/filter-panel.scss
- src/styles/themes/b2b/variables.scss
- src/styles/themes/b2c/variables.scss
[x] Bugfix
[x] Other: test, deps
[x] No
[AB#104012](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/104012)
> fix: mixed improvements

- src/app/core/standalone/component/suggest/search-box/search-box.component.html
- src/app/core/standalone/component/suggest/search-box/search-box.component.ts
- src/app/core/standalone/component/suggest/suggest-products-tile/suggest-products-tile.component.html
- src/app/core/standalone/component/suggest/suggest-products-tile/suggest-products-tile.component.ts
- src/app/shell/header/header-default/__snapshots__/header-default.component.spec.ts.snap
- src/app/shell/header/header-default/header-default.component.html
- src/styles/components/header/search-container.scss
[x] Feature
* show products below each other on mobile and tablet
* truncate product name only on desktop
* add accessibility attributes
* set suggest layer height on mobile dynamically depending on onscreen keyboard height 
* update suggest layer height for desktop
[x] No
> feat: update product display, add accessibility attributes, calculate layer height

- src/app/core/facades/shopping.facade.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.spec.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.ts
- src/app/core/standalone/component/suggest/suggest-products-tile/suggest-products-tile.component.html
- src/app/core/standalone/component/suggest/suggest-products-tile/suggest-products-tile.component.ts
- src/styles/components/header/search-container.scss
[x] Feature
* the product price will not be shown
* the product image not available is shown in case the product image attribute es empty
* the minimum character count to show the suggest is changed from 2 to 3
[x] No
> feat: product price, product image not available, minimum character input

- docs/guides/sparque-integration.md
- src/app/core/facades/shopping.facade.ts
- src/app/core/models/sparque-suggestion/sparque-suggestion.mapper.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.html
- src/app/core/standalone/component/suggest/search-box/search-box.component.spec.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.ts
- src/app/core/standalone/component/suggest/suggest-products-tile/suggest-products-tile.component.ts
- src/app/core/standalone/component/suggest/suggest-search-terms-tile/suggest-search-terms-tile.component.html
- src/app/core/standalone/component/suggest/suggest-search-terms-tile/suggest-search-terms-tile.component.ts
- src/app/core/store/shopping/search/search.actions.ts
- src/app/core/store/shopping/search/search.effects.ts
- src/app/core/store/shopping/search/search.reducer.ts
- src/app/core/store/shopping/search/search.selectors.ts
- src/app/core/store/shopping/shopping-store.spec.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ ] Bugfix
[x] Feature
[ ] Other: 
Issue Number: #102491 (ADO)
The search box can show the recently search terms. This terms are store in the search state and also in the local storage of the browser. Only the last 10 search terms are stored.
> feat: add recently search terms component (#102491)

- .devcontainer/Dockerfile
- docs/README.md
- docs/concepts/configuration.md
- docs/concepts/hybrid-approach.md
- docs/guides/angular-component-development.md
- docs/guides/code-documentation.md
- docs/guides/cookie-consent.md
- docs/guides/copilot.md
- docs/guides/customizations.md
- docs/guides/development.md
- docs/guides/getting-started.md
- docs/guides/migrations.md
- docs/guides/mocking-rest-calls.md
- docs/guides/nginx-startup.md
- docs/guides/ssr-startup.md
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
##PR Type
Renamed _Intershop Copilot_ to _Intershop Copilot for Buyers_
- adjusted localizations
- adjusted documentation
Review of localizations and documentation for PWA 5.3 release
-adjusted guides and concepts
[ ] Yes
[x] No
[AB#104646](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/104646)
> feature: documentation and localization review

- docker-compose.yml
- docs/guides/multi-site-configurations.md
- docs/guides/sparque-integration.md
- nginx/templates/multi-channel.conf.tmpl
- src/app/core/configurations/configuration.meta.ts
- src/app/core/models/sparque/sparque-config.model.ts
- src/app/core/services/api/api.service.ts
- src/app/core/services/sparque-api/sparque-api.service.spec.ts
- src/app/core/services/sparque-api/sparque-api.service.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.html
- src/app/core/store/shopping/search/search.actions.ts
- src/app/core/store/shopping/search/search.reducer.ts
- src/assets/i18n/de_DE.json
- src/assets/i18n/en_US.json
- src/assets/i18n/fr_FR.json
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[ ] No
> feat: add multi site configuration (#104509)

- docs/guides/sparque-integration.md
- e2e/cypress/e2e/specs/filter/filter-search-results.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/filter/filter-search-results.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/shopping/search-box.b2c.e2e-spec.ts
- e2e/cypress/e2e/specs/shopping/search-products.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/shopping/search-products.b2c.e2e-spec.ts
- src/app/core/standalone/component/suggest/search-box/search-box.component.ts
- src/app/core/standalone/component/suggest/suggest-brands-tile/suggest-brands-tile.component.html
- src/app/core/standalone/component/suggest/suggest-categories-tile/suggest-categories-tile.component.html
- src/app/core/standalone/component/suggest/suggest-keywords-tile/suggest-keywords-tile.component.html
- src/app/core/standalone/component/suggest/suggest-products-tile/suggest-products-tile.component.html
- src/app/core/standalone/component/suggest/suggest-search-terms-tile/suggest-search-terms-tile.component.html
[x] Bugfix
[issue description](https://github.com/intershop/intershop-pwa/pull/1760#pullrequestreview-2673564970)
The suggest values are taken as they are and not formatted with _titlecase_. 
[x] No
> fix: remove title case formatting for suggest values

- angular.json
- package-lock.json
* update vulnerable babel dependencies
* remove localforage build warning
[x] Other: dependencies vulnerability fix
[x] No
[AB#105069](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/105069)
> deps: update vulnerable babel dependencies

- .vscode/intershop.txt
- docs/README.md
- docs/guides/accessibility-easy-check.md
- docs/guides/accessibility.md
- docs/guides/migrations.md
Extends the accessibility documentation: How to check the accessibility of PWA pages:
- Automated testing
- Partially automated Testing
- Manual testing
[x] No
[AB#98238](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/98238)
> docs: update and extend accessibility documentation

- CHANGELOG.md
- docs/guides/themes.md
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[x] No
Minor documentation content change
[AB#105685](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/105685)
> docs: add note regarding configurable theme feature configuration short coming

- docs/guides/copilot.md
Request to change the link title, also checked for other occurrences, see ticket 106159 in ADO.  
[AB#106195](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/106195)
> docs: adjusted link title (#106159)

- .vscode/intershop.txt
- CHANGELOG.md
- Dockerfile
- Dockerfile_reports
- docker-compose.yml
- docs/guides/accessibility-easy-check.md
- docs/guides/migrations.md
- docs/guides/nginx-startup.md
- nginx/docker-entrypoint.d/20-ssl.sh
[x] Feature
[x] No
[AB#106809](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/106809)
> chore: improvements (dev certificates, docker-compose + Dockerfile cleanup, use semantic versioning in documentation)

- CHANGELOG.md
- docs/guides/migrations.md
[ ] Bugfix
[ ] Feature
[ ] Other: 
[ ] Yes
[x] No
[AB#107052](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/107052)
> docs: migration guide review

- src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.html
- src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.spec.ts
- src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.ts
[x] Feature
The contact us form doesn't distinguish between registered and anonymous users
Improved contact us form for registered users
* set email field to readonly and use the user's email address
[x] No
[AB#108165](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/108165)
> refactor: improve contact us form for registered users

- src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
[x] Bugfix
[ ] Feature
[ ] Other: 
Issue Number: Closes #1792
Error message is now showing when terms and conditions box is unchecked.
[ ] Yes
[x] No
[AB#106827](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/106827)
> fix: No error message for unchecked terms & conditions in registration form

- docs/guides/sparque-ai.md
[ ] Bugfix
[ ] Feature
[ ] Other: 
The sparque configuration data has so far been rather poorly described.
Issue Number: #107403
The sparque configuration data is better described.
[ ] Yes
[x] No
[AB#108513](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/108513)
> docs: improve SPARQUE.AI documentation

- README.md
[ ] Bugfix
[ ] Feature
[ ] Other: 
Updated since it still mentioned Intershop Commerce Suite. Also eCommerce should be e-commerce according to our glossary. 
[AB#108791](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/108791)
[AB#108789](https://dev.azure.com/intershop-com/Products/_workitems/edit/108789)
> docs: update project description in readme

- .copilotrc
- .editorconfig
- .github/copilot-instructions.md
- .github/instructions/commit-style.instructions.md
- .github/instructions/component-patterns.instructions.md
- .github/instructions/error-handling.instructions.md
- .github/instructions/naming-patterns.instructions.md
- .github/instructions/negative-patterns.instructions.md
- .github/instructions/performance-patterns.instructions.md
- .github/instructions/service-patterns.instructions.md
- .github/instructions/state-management-patterns.instructions.md
- .github/instructions/styles.instructions.md
- .github/instructions/testing-patterns.instructions.md
- .github/instructions/workflows.instructions.md
- .github/pull_request_template.md
- .prettierignore
- .prettierrc
- .vscode/settings.json
[x] Other: GitHub Copilot integration support
The added GitHub Copilot configurations and code style configuration adaptions should result in better Copilot suggestions when developing with the PWA.
[x] No
Official Documentation: https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions
[AB#108792](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/108792)
> feat: integrate GitHub Copilot instructions for Intershop PWA

- e2e/cypress/e2e/specs/checkout/checkout-cost-center-multiple.b2b.e2e-spec.ts
- e2e/cypress/e2e/specs/checkout/checkout-cost-center-no-costcenter.b2b.e2e-spec.ts
Some cost center e2e fail due to timing issues. An error occur: The cart could not be found after switching to the basket page.
A wait time has been added within the tests to prevent the error. The checkout_cost_center_no_cost_center test has been refactored and it creates a new user instead taking an existing one.
[AB#110846](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/110846)
> test: fix flaky cost center e2e tests
